/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AddressRespProtocolListInner } from './address-resp-protocol-list-inner';

/**
 * Address-level aggregation. Groups the protocol-level position summaries of one wallet address.
 * @export
 * @interface AddressResp
 */
export interface AddressResp {
    /**
     * Wallet address.
     * @type {string}
     * @memberof AddressResp
     */
    address?: string;
    /**
     * Total DeFi position value of this address across all chains (USD). Same raw precision as the position values.
     * @type {string}
     * @memberof AddressResp
     */
    addressTotalValue?: string;
    /**
     * Protocol-level position summaries of this address.
     * @type {Array<AddressRespProtocolListInner>}
     * @memberof AddressResp
     */
    protocolList?: Array<AddressRespProtocolListInner>;
}
