/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface B402PaymentRequirementsExtraV2
 */
export interface B402PaymentRequirementsExtraV2 {
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsExtraV2
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsExtraV2
     */
    version: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsExtraV2
     */
    assetTransferMethod: B402PaymentRequirementsExtraV2AssetTransferMethodEnum;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsExtraV2
     */
    signerAddress: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsExtraV2
     */
    spenderAddress?: string | null;
}

export const B402PaymentRequirementsExtraV2AssetTransferMethodEnum = {
    EIP3009: 'eip3009',
    PERMIT2_EXACT: 'permit2-exact',
    PERMIT2_UPTO: 'permit2-upto',
} as const;

export type B402PaymentRequirementsExtraV2AssetTransferMethodEnum =
    (typeof B402PaymentRequirementsExtraV2AssetTransferMethodEnum)[keyof typeof B402PaymentRequirementsExtraV2AssetTransferMethodEnum];
