/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2Accepted } from './b402-payment-payload-v2-accepted';
// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2Extensions } from './b402-payment-payload-v2-extensions';
// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2Payload } from './b402-payment-payload-v2-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2Resource } from './b402-payment-payload-v2-resource';

/**
 *
 * @export
 * @interface B402VerifyRequestV2PaymentPayload
 */
export interface B402VerifyRequestV2PaymentPayload {
    /**
     *
     * @type {number}
     * @memberof B402VerifyRequestV2PaymentPayload
     */
    x402Version: B402VerifyRequestV2PaymentPayloadX402VersionEnum;
    /**
     *
     * @type {B402PaymentPayloadV2Resource}
     * @memberof B402VerifyRequestV2PaymentPayload
     */
    resource: B402PaymentPayloadV2Resource;
    /**
     *
     * @type {B402PaymentPayloadV2Accepted}
     * @memberof B402VerifyRequestV2PaymentPayload
     */
    accepted: B402PaymentPayloadV2Accepted;
    /**
     *
     * @type {B402PaymentPayloadV2Payload}
     * @memberof B402VerifyRequestV2PaymentPayload
     */
    payload: B402PaymentPayloadV2Payload;
    /**
     *
     * @type {B402PaymentPayloadV2Extensions}
     * @memberof B402VerifyRequestV2PaymentPayload
     */
    extensions?: B402PaymentPayloadV2Extensions;
}

export const B402VerifyRequestV2PaymentPayloadX402VersionEnum = {
    X402_VERSION_2: 2,
} as const;

export type B402VerifyRequestV2PaymentPayloadX402VersionEnum =
    (typeof B402VerifyRequestV2PaymentPayloadX402VersionEnum)[keyof typeof B402VerifyRequestV2PaymentPayloadX402VersionEnum];
