/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402VerifyRequestV1PaymentPayload } from './b402-verify-request-v1-payment-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { B402VerifyRequestV1PaymentRequirements } from './b402-verify-request-v1-payment-requirements';

/**
 *
 * @export
 * @interface B402VerifyEnvelopeV1Body
 */
export interface B402VerifyEnvelopeV1Body {
    /**
     *
     * @type {number}
     * @memberof B402VerifyEnvelopeV1Body
     */
    x402Version: B402VerifyEnvelopeV1BodyX402VersionEnum;
    /**
     *
     * @type {B402VerifyRequestV1PaymentPayload}
     * @memberof B402VerifyEnvelopeV1Body
     */
    paymentPayload: B402VerifyRequestV1PaymentPayload;
    /**
     *
     * @type {B402VerifyRequestV1PaymentRequirements}
     * @memberof B402VerifyEnvelopeV1Body
     */
    paymentRequirements: B402VerifyRequestV1PaymentRequirements;
}

export const B402VerifyEnvelopeV1BodyX402VersionEnum = {
    X402_VERSION_1: 1,
} as const;

export type B402VerifyEnvelopeV1BodyX402VersionEnum =
    (typeof B402VerifyEnvelopeV1BodyX402VersionEnum)[keyof typeof B402VerifyEnvelopeV1BodyX402VersionEnum];
