/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2ExtensionsBazaar } from './b402-payment-payload-v2-extensions-bazaar';

/**
 *
 * @export
 * @interface B402PaymentPayloadV2Extensions
 */
export interface B402PaymentPayloadV2Extensions {
    [key: string]: any;

    /**
     *
     * @type {B402PaymentPayloadV2ExtensionsBazaar}
     * @memberof B402PaymentPayloadV2Extensions
     */
    bazaar?: B402PaymentPayloadV2ExtensionsBazaar;
}
