/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface B402Eip3009Authorization
 */
export interface B402Eip3009Authorization {
    /**
     *
     * @type {string}
     * @memberof B402Eip3009Authorization
     */
    from: string;
    /**
     *
     * @type {string}
     * @memberof B402Eip3009Authorization
     */
    to: string;
    /**
     *
     * @type {string}
     * @memberof B402Eip3009Authorization
     */
    value: string;
    /**
     *
     * @type {string}
     * @memberof B402Eip3009Authorization
     */
    validAfter: string;
    /**
     *
     * @type {string}
     * @memberof B402Eip3009Authorization
     */
    validBefore: string;
    /**
     *
     * @type {string}
     * @memberof B402Eip3009Authorization
     */
    nonce: string;
}
