/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface B402Permit2Permitted
 */
export interface B402Permit2Permitted {
    /**
     *
     * @type {string}
     * @memberof B402Permit2Permitted
     */
    token: string;
    /**
     *
     * @type {string}
     * @memberof B402Permit2Permitted
     */
    amount: string;
}
