/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402SettleRequestV2AllOfPaymentPayload } from './b402-settle-request-v2-all-of-payment-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { B402SettleRequestV2AllOfPaymentPayloadAccepted } from './b402-settle-request-v2-all-of-payment-payload-accepted';

/**
 *
 * @export
 * @interface B402SettleRequestV2
 */
export interface B402SettleRequestV2 {
    /**
     *
     * @type {number}
     * @memberof B402SettleRequestV2
     */
    x402Version: B402SettleRequestV2X402VersionEnum;
    /**
     *
     * @type {B402SettleRequestV2AllOfPaymentPayload}
     * @memberof B402SettleRequestV2
     */
    paymentPayload: B402SettleRequestV2AllOfPaymentPayload;
    /**
     *
     * @type {B402SettleRequestV2AllOfPaymentPayloadAccepted}
     * @memberof B402SettleRequestV2
     */
    paymentRequirements: B402SettleRequestV2AllOfPaymentPayloadAccepted;
    /**
     *
     * @type {string}
     * @memberof B402SettleRequestV2
     */
    settleAmount?: string;
}

export const B402SettleRequestV2X402VersionEnum = {
    X402_VERSION_2: 2,
} as const;

export type B402SettleRequestV2X402VersionEnum =
    (typeof B402SettleRequestV2X402VersionEnum)[keyof typeof B402SettleRequestV2X402VersionEnum];
