/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentRequirementsV2Extra } from './b402-payment-requirements-v2-extra';

/**
 *
 * @export
 * @interface B402PaymentPayloadV2Accepted
 */
export interface B402PaymentPayloadV2Accepted {
    /**
     *
     * @type {string}
     * @memberof B402PaymentPayloadV2Accepted
     */
    scheme: B402PaymentPayloadV2AcceptedSchemeEnum;
    /**
     *
     * @type {string}
     * @memberof B402PaymentPayloadV2Accepted
     */
    network: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentPayloadV2Accepted
     */
    amount: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentPayloadV2Accepted
     */
    asset: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentPayloadV2Accepted
     */
    payTo: string;
    /**
     *
     * @type {number}
     * @memberof B402PaymentPayloadV2Accepted
     */
    maxTimeoutSeconds: number;
    /**
     *
     * @type {B402PaymentRequirementsV2Extra}
     * @memberof B402PaymentPayloadV2Accepted
     */
    extra: B402PaymentRequirementsV2Extra;
}

export const B402PaymentPayloadV2AcceptedSchemeEnum = {
    exact: 'exact',
    upto: 'upto',
} as const;

export type B402PaymentPayloadV2AcceptedSchemeEnum =
    (typeof B402PaymentPayloadV2AcceptedSchemeEnum)[keyof typeof B402PaymentPayloadV2AcceptedSchemeEnum];
