/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402SupportedDataV2KindsInnerExtra } from './b402-supported-data-v2-kinds-inner-extra';

/**
 *
 * @export
 * @interface B402SupportedDataV2KindsInner
 */
export interface B402SupportedDataV2KindsInner {
    /**
     *
     * @type {number}
     * @memberof B402SupportedDataV2KindsInner
     */
    x402Version: B402SupportedDataV2KindsInnerX402VersionEnum;
    /**
     *
     * @type {string}
     * @memberof B402SupportedDataV2KindsInner
     */
    scheme: B402SupportedDataV2KindsInnerSchemeEnum;
    /**
     *
     * @type {string}
     * @memberof B402SupportedDataV2KindsInner
     */
    network: string;
    /**
     *
     * @type {B402SupportedDataV2KindsInnerExtra}
     * @memberof B402SupportedDataV2KindsInner
     */
    extra: B402SupportedDataV2KindsInnerExtra;
}

export const B402SupportedDataV2KindsInnerX402VersionEnum = {
    X402_VERSION_2: 2,
} as const;

export type B402SupportedDataV2KindsInnerX402VersionEnum =
    (typeof B402SupportedDataV2KindsInnerX402VersionEnum)[keyof typeof B402SupportedDataV2KindsInnerX402VersionEnum];
export const B402SupportedDataV2KindsInnerSchemeEnum = {
    exact: 'exact',
    upto: 'upto',
} as const;

export type B402SupportedDataV2KindsInnerSchemeEnum =
    (typeof B402SupportedDataV2KindsInnerSchemeEnum)[keyof typeof B402SupportedDataV2KindsInnerSchemeEnum];
