/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2Extensions } from './b402-payment-payload-v2-extensions';
// May contain unused imports in some cases
// @ts-ignore
import type { B402SettleEnvelopeV2BodyAllOfPaymentPayloadAccepted } from './b402-settle-envelope-v2-body-all-of-payment-payload-accepted';
// May contain unused imports in some cases
// @ts-ignore
import type { B402SettleRequestV2AllOfPaymentPayloadPayload } from './b402-settle-request-v2-all-of-payment-payload-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { B402SettleRequestV2AllOfPaymentPayloadResource } from './b402-settle-request-v2-all-of-payment-payload-resource';

/**
 *
 * @export
 * @interface B402SettleEnvelopeV2BodyAllOfPaymentPayload
 */
export interface B402SettleEnvelopeV2BodyAllOfPaymentPayload {
    /**
     *
     * @type {number}
     * @memberof B402SettleEnvelopeV2BodyAllOfPaymentPayload
     */
    x402Version: B402SettleEnvelopeV2BodyAllOfPaymentPayloadX402VersionEnum;
    /**
     *
     * @type {B402SettleRequestV2AllOfPaymentPayloadResource}
     * @memberof B402SettleEnvelopeV2BodyAllOfPaymentPayload
     */
    resource: B402SettleRequestV2AllOfPaymentPayloadResource;
    /**
     *
     * @type {B402SettleEnvelopeV2BodyAllOfPaymentPayloadAccepted}
     * @memberof B402SettleEnvelopeV2BodyAllOfPaymentPayload
     */
    accepted: B402SettleEnvelopeV2BodyAllOfPaymentPayloadAccepted;
    /**
     *
     * @type {B402SettleRequestV2AllOfPaymentPayloadPayload}
     * @memberof B402SettleEnvelopeV2BodyAllOfPaymentPayload
     */
    payload: B402SettleRequestV2AllOfPaymentPayloadPayload;
    /**
     *
     * @type {B402PaymentPayloadV2Extensions}
     * @memberof B402SettleEnvelopeV2BodyAllOfPaymentPayload
     */
    extensions?: B402PaymentPayloadV2Extensions;
}

export const B402SettleEnvelopeV2BodyAllOfPaymentPayloadX402VersionEnum = {
    X402_VERSION_2: 2,
} as const;

export type B402SettleEnvelopeV2BodyAllOfPaymentPayloadX402VersionEnum =
    (typeof B402SettleEnvelopeV2BodyAllOfPaymentPayloadX402VersionEnum)[keyof typeof B402SettleEnvelopeV2BodyAllOfPaymentPayloadX402VersionEnum];
