/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentKindV1Extra } from './b402-payment-kind-v1-extra';

/**
 *
 * @export
 * @interface B402PaymentRequirementsV1
 */
export interface B402PaymentRequirementsV1 {
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    scheme: B402PaymentRequirementsV1SchemeEnum;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    network: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    amount: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    resource?: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    payTo: string;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    asset: string;
    /**
     *
     * @type {number}
     * @memberof B402PaymentRequirementsV1
     */
    maxTimeoutSeconds: number;
    /**
     *
     * @type {string}
     * @memberof B402PaymentRequirementsV1
     */
    mimeType?: string;
    /**
     *
     * @type {{ [key: string]: any | undefined; }}
     * @memberof B402PaymentRequirementsV1
     */
    outputSchema?: { [key: string]: any | undefined };
    /**
     *
     * @type {B402PaymentKindV1Extra}
     * @memberof B402PaymentRequirementsV1
     */
    extra?: B402PaymentKindV1Extra;
}

export const B402PaymentRequirementsV1SchemeEnum = {
    exact: 'exact',
} as const;

export type B402PaymentRequirementsV1SchemeEnum =
    (typeof B402PaymentRequirementsV1SchemeEnum)[keyof typeof B402PaymentRequirementsV1SchemeEnum];
