/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402PaymentPayloadV2Payload } from './b402-payment-payload-v2-payload';

/**
 *
 * @export
 * @interface B402VerifyRequestV1PaymentPayload
 */
export interface B402VerifyRequestV1PaymentPayload {
    /**
     *
     * @type {number}
     * @memberof B402VerifyRequestV1PaymentPayload
     */
    x402Version: B402VerifyRequestV1PaymentPayloadX402VersionEnum;
    /**
     *
     * @type {string}
     * @memberof B402VerifyRequestV1PaymentPayload
     */
    scheme: B402VerifyRequestV1PaymentPayloadSchemeEnum;
    /**
     *
     * @type {string}
     * @memberof B402VerifyRequestV1PaymentPayload
     */
    network: string;
    /**
     *
     * @type {B402PaymentPayloadV2Payload}
     * @memberof B402VerifyRequestV1PaymentPayload
     */
    payload: B402PaymentPayloadV2Payload;
}

export const B402VerifyRequestV1PaymentPayloadX402VersionEnum = {
    X402_VERSION_1: 1,
} as const;

export type B402VerifyRequestV1PaymentPayloadX402VersionEnum =
    (typeof B402VerifyRequestV1PaymentPayloadX402VersionEnum)[keyof typeof B402VerifyRequestV1PaymentPayloadX402VersionEnum];
export const B402VerifyRequestV1PaymentPayloadSchemeEnum = {
    exact: 'exact',
} as const;

export type B402VerifyRequestV1PaymentPayloadSchemeEnum =
    (typeof B402VerifyRequestV1PaymentPayloadSchemeEnum)[keyof typeof B402VerifyRequestV1PaymentPayloadSchemeEnum];
