/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BuildDeFiDepositTransactionResponseDataDataListInner } from './build-de-fi-deposit-transaction-response-data-data-list-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildDeFiDepositTransactionResponseDataPreview } from './build-de-fi-deposit-transaction-response-data-preview';

/**
 * Unified response of the five build endpoints (deposit / redeem / lp-add / lp-remove / claim). `dataList` is ordered: APPROVE items come first, the main action follows — sign and broadcast each item in order. `preview` is non-null only when the request set `simulate=true`. `redeemDelayDays` is populated only by `/transaction/redeem`.
 * @export
 * @interface BuildDeFiDepositTransactionResponseData
 */
export interface BuildDeFiDepositTransactionResponseData {
    /**
     * Ordered unsigned transactions; APPROVE precedes the main action.
     * @type {Array<BuildDeFiDepositTransactionResponseDataDataListInner>}
     * @memberof BuildDeFiDepositTransactionResponseData
     */
    dataList?: Array<BuildDeFiDepositTransactionResponseDataDataListInner>;
    /**
     *
     * @type {BuildDeFiDepositTransactionResponseDataPreview}
     * @memberof BuildDeFiDepositTransactionResponseData
     */
    preview?: BuildDeFiDepositTransactionResponseDataPreview;
    /**
     * Redeem waiting period as a `[min, max]` day pair of decimal strings. Populated **only** by `/transaction/redeem`; `null` on the other build endpoints or when unavailable. Interpretation: `[]` (empty) = instant, no waiting period; `[\"7\",\"7\"]` = fixed 7 days; `[\"7\",\"10\"]` = 7–10 days. The wait starts after the redeem transaction is confirmed on-chain.
     * @type {Array<string>}
     * @memberof BuildDeFiDepositTransactionResponseData
     */
    redeemDelayDays?: Array<string>;
}
