/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BuildSwapTransactionResponseDataRouterResult } from './build-swap-transaction-response-data-router-result';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildSwapTransactionResponseDataTx } from './build-swap-transaction-response-data-tx';

/**
 *
 * @export
 * @interface BuildSwapTransactionResponseData
 */
export interface BuildSwapTransactionResponseData {
    /**
     *
     * @type {BuildSwapTransactionResponseDataRouterResult}
     * @memberof BuildSwapTransactionResponseData
     */
    routerResult?: BuildSwapTransactionResponseDataRouterResult;
    /**
     *
     * @type {BuildSwapTransactionResponseDataTx}
     * @memberof BuildSwapTransactionResponseData
     */
    tx?: BuildSwapTransactionResponseDataTx;
}
