/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * FAQ entry.
 * @export
 * @interface DefiProtocolInfoDtoFaqInner
 */
export interface DefiProtocolInfoDtoFaqInner {
    /**
     * FAQ question text (already translated; quote as-is).
     * @type {string}
     * @memberof DefiProtocolInfoDtoFaqInner
     */
    title?: string;
    /**
     * FAQ answer text (already translated; quote as-is). May contain line-break markup `<Br/>` and paragraph-gap markup `<Gap/>` — interpret them as line / paragraph breaks.
     * @type {string}
     * @memberof DefiProtocolInfoDtoFaqInner
     */
    answer?: string;
}
