/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DeFi protocol summary (list item).
 * @export
 * @interface DefiProtocolDto
 */
export interface DefiProtocolDto {
    /**
     * DeFi protocol identifier.
     * @type {string}
     * @memberof DefiProtocolDto
     */
    defiProtocolId?: string;
    /**
     * Protocol display name.
     * @type {string}
     * @memberof DefiProtocolDto
     */
    protocolName?: string;
    /**
     * Protocol logo image URL (full URL; quote as-is).
     * @type {string}
     * @memberof DefiProtocolDto
     */
    protocolLogo?: string;
    /**
     * Total value locked in the protocol (USD). String, raw precision from the data source.
     * @type {string}
     * @memberof DefiProtocolDto
     */
    tvl?: string;
    /**
     * Highest APY across the protocol\'s investments, in basis points (1 bps = 0.01%). Integer value — use this for sorting / comparing / filtering, never the raw decimal.
     * @type {number | bigint}
     * @memberof DefiProtocolDto
     */
    apyBps?: number | bigint;
    /**
     * Pre-formatted, human-readable APY string for display (e.g. \"12.35%\"). Quote as-is; do not re-compute or transform.
     * @type {string}
     * @memberof DefiProtocolDto
     */
    apyDisplay?: string;
    /**
     * Investment types supported by this protocol — an array here (a protocol may support several). Note: the investment-level investType (in investment list/detail) is a single string. Known values: Earn, LiquidityPool.
     * @type {Array<string>}
     * @memberof DefiProtocolDto
     */
    investType?: Array<string>;
    /**
     * Supported Binance chain IDs.
     * @type {Array<string>}
     * @memberof DefiProtocolDto
     */
    supportedChains?: Array<string>;
}
