/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fundraising round.
 * @export
 * @interface DefiProtocolFundRaisingDto
 */
export interface DefiProtocolFundRaisingDto {
    /**
     * Round name (e.g. \"Strategic\").
     * @type {string}
     * @memberof DefiProtocolFundRaisingDto
     */
    round?: string;
    /**
     * Amount raised. Null when not disclosed.
     * @type {string}
     * @memberof DefiProtocolFundRaisingDto
     */
    amount?: string | null;
    /**
     * Round date.
     * @type {string}
     * @memberof DefiProtocolFundRaisingDto
     */
    date?: string;
    /**
     * Investor names.
     * @type {Array<string>}
     * @memberof DefiProtocolFundRaisingDto
     */
    investors?: Array<string>;
}
