/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Protocol team member.
 * @export
 * @interface DefiProtocolInfoDtoTeamInner
 */
export interface DefiProtocolInfoDtoTeamInner {
    /**
     * Member name.
     * @type {string}
     * @memberof DefiProtocolInfoDtoTeamInner
     */
    name?: string;
    /**
     * Member role / title.
     * @type {string}
     * @memberof DefiProtocolInfoDtoTeamInner
     */
    role?: string;
    /**
     * Member\'s X (Twitter) handle URL. Null when not available.
     * @type {string}
     * @memberof DefiProtocolInfoDtoTeamInner
     */
    twitter?: string | null;
    /**
     * Member\'s LinkedIn URL. Null when not available.
     * @type {string}
     * @memberof DefiProtocolInfoDtoTeamInner
     */
    linkedin?: string | null;
    /**
     * Member biography. Null when not available.
     * @type {string}
     * @memberof DefiProtocolInfoDtoTeamInner
     */
    bio?: string | null;
}
