/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The contract the action interacts with.
 * @export
 * @interface DefiPreviewFeeAndContractInteractWith
 */
export interface DefiPreviewFeeAndContractInteractWith {
    /**
     * Target contract address.
     * @type {string}
     * @memberof DefiPreviewFeeAndContractInteractWith
     */
    address?: string;
}
