/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTokenBasicInfoResponseData } from './get-token-basic-info-response-data';

/**
 *
 * @export
 * @interface GetTokenBasicInfoResponse
 */
export interface GetTokenBasicInfoResponse {
    /**
     *
     * @type {number}
     * @memberof GetTokenBasicInfoResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetTokenBasicInfoResponse
     */
    msg?: string;
    /**
     *
     * @type {GetTokenBasicInfoResponseData}
     * @memberof GetTokenBasicInfoResponse
     */
    data?: GetTokenBasicInfoResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetTokenBasicInfoResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetTokenBasicInfoResponse
     */
    success?: boolean;
}
