/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTokenTradesResponseDataTradesInner } from './get-token-trades-response-data-trades-inner';

/**
 *
 * @export
 * @interface GetTokenTradesResponseData
 */
export interface GetTokenTradesResponseData {
    /**
     * Cursor for the next page. Empty string when no more data.
     * @type {string}
     * @memberof GetTokenTradesResponseData
     */
    cursor?: string;
    /**
     * Trades sorted by trade time (descending).
     * @type {Array<GetTokenTradesResponseDataTradesInner>}
     * @memberof GetTokenTradesResponseData
     */
    trades?: Array<GetTokenTradesResponseDataTradesInner>;
}
