/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetErc20ApproveTransactionResponseDataInner } from './get-erc20-approve-transaction-response-data-inner';

/**
 *
 * @export
 * @interface GetErc20ApproveTransactionResponse
 */
export interface GetErc20ApproveTransactionResponse {
    /**
     *
     * @type {number}
     * @memberof GetErc20ApproveTransactionResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetErc20ApproveTransactionResponse
     */
    msg?: string;
    /**
     * Approve transaction(s) to submit before the swap.
     * @type {Array<GetErc20ApproveTransactionResponseDataInner>}
     * @memberof GetErc20ApproveTransactionResponse
     */
    data?: Array<GetErc20ApproveTransactionResponseDataInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetErc20ApproveTransactionResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetErc20ApproveTransactionResponse
     */
    success?: boolean;
}
