/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetHoldersRankingResponseDataInnerFundingSourceLabel } from './get-holders-ranking-response-data-inner-funding-source-label';

/**
 *
 * @export
 * @interface GetHoldersRankingResponseDataInner
 */
export interface GetHoldersRankingResponseDataInner {
    /**
     * Holder wallet address.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    holderWalletAddress?: string;
    /**
     * Current holding amount.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    holdAmount?: string;
    /**
     * Holding percentage. \"5.23\" means 5.23%.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    holdingPercent?: string;
    /**
     * Native token symbol.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    nativeTokenSymbol?: string;
    /**
     * Native token balance of the address.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    nativeTokenBalance?: string;
    /**
     * Total buy amount.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    boughtAmount?: string;
    /**
     * Average buy price, denominated in USD.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    avgBuyPrice?: string;
    /**
     * Cumulative sold amount (token units).
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    soldAmount?: string;
    /**
     * Average sell price, denominated in USD.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    avgSellPrice?: string;
    /**
     * Maximum historical holding amount.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    maxHoldAmount?: string;
    /**
     * Last trade time, Unix millisecond timestamp.
     * @type {number | bigint}
     * @memberof GetHoldersRankingResponseDataInner
     */
    lastTradeTime?: number | bigint;
    /**
     * Realized PnL, denominated in USD. Positive means profit, negative means loss.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    realizedPnlUsd?: string;
    /**
     * Funding source address, i.e., the originator of the first inbound native-token transfer. Null when no inbound transfer is recorded.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    fundingSource?: string | null;
    /**
     *
     * @type {GetHoldersRankingResponseDataInnerFundingSourceLabel}
     * @memberof GetHoldersRankingResponseDataInner
     */
    fundingSourceLabel?: GetHoldersRankingResponseDataInnerFundingSourceLabel | null;
    /**
     * Transaction hash of the first inbound native-token transfer.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    fundingSourceHash?: string | null;
    /**
     * Time of the first native token inbound transfer, Unix millisecond timestamp.
     * @type {number | bigint}
     * @memberof GetHoldersRankingResponseDataInner
     */
    fundingSourceTime?: number | bigint | null;
    /**
     * Amount of the first native token inbound transfer. e.g. 0.5 means 0.5 ETH.
     * @type {string}
     * @memberof GetHoldersRankingResponseDataInner
     */
    fundingSourceAmount?: string | null;
}
