/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatedQuoteResponseDataInnerDexRouterListInner } from './get-aggregated-quote-response-data-inner-dex-router-list-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatedQuoteResponseDataInnerFromToken } from './get-aggregated-quote-response-data-inner-from-token';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatedQuoteResponseDataInnerToToken } from './get-aggregated-quote-response-data-inner-to-token';

/**
 *
 * @export
 * @interface GetAggregatedQuoteResponseDataInner
 */
export interface GetAggregatedQuoteResponseDataInner {
    /**
     * Per-route quote identifier (UUID, no dashes). Pass to the swap endpoint to lock in this route.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    quoteId?: string;
    /**
     * Source vendor display name. Possible values include LiquidMesh, Lifi, 1inch, Pancake, Jupiter.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    vendorName?: string;
    /**
     * Chain identifier echoed from the request.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    binanceChainId?: string;
    /**
     * Sell amount echoed from the request (smallest unit, integer string).
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    fromTokenAmount?: string;
    /**
     * Estimated buy-token amount returned by the vendor (smallest unit, integer string).
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    toTokenAmount?: string;
    /**
     * Estimated network fee for this route in USD. Null when the vendor does not return one.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    tradeFee?: string | null;
    /**
     * Estimated gas in the chain\'s smallest unit (e.g. wei). May be null on Solana.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    estimateGasFee?: string | null;
    /**
     * Estimated price impact percentage. Null when the vendor does not return one.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    priceImpactPercent?: string | null;
    /**
     * Routing path description, addresses joined with \"--\".
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    router?: string;
    /**
     *
     * @type {GetAggregatedQuoteResponseDataInnerFromToken}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    fromToken?: GetAggregatedQuoteResponseDataInnerFromToken;
    /**
     *
     * @type {GetAggregatedQuoteResponseDataInnerToToken}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    toToken?: GetAggregatedQuoteResponseDataInnerToToken;
    /**
     * Routing path segments. Each segment corresponds to one hop on one DEX protocol; multi-DEX hops are flattened.
     * @type {Array<GetAggregatedQuoteResponseDataInnerDexRouterListInner>}
     * @memberof GetAggregatedQuoteResponseDataInner
     */
    dexRouterList?: Array<GetAggregatedQuoteResponseDataInnerDexRouterListInner>;
}
