/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatorSupportedChainsResponseDataInner } from './get-aggregator-supported-chains-response-data-inner';

/**
 *
 * @export
 * @interface GetAggregatorSupportedChainsResponse
 */
export interface GetAggregatorSupportedChainsResponse {
    /**
     * Business status code. 0 indicates success; any non-zero value indicates a business error.
     * @type {number}
     * @memberof GetAggregatorSupportedChainsResponse
     */
    code?: number;
    /**
     * Status description message.
     * @type {string}
     * @memberof GetAggregatorSupportedChainsResponse
     */
    msg?: string;
    /**
     * List of supported blockchain networks.
     * @type {Array<GetAggregatorSupportedChainsResponseDataInner>}
     * @memberof GetAggregatorSupportedChainsResponse
     */
    data?: Array<GetAggregatorSupportedChainsResponseDataInner>;
    /**
     * Server response timestamp in milliseconds.
     * @type {number | bigint}
     * @memberof GetAggregatorSupportedChainsResponse
     */
    timestamp?: number | bigint;
    /**
     * Convenience flag derived from `code == 0`.
     * @type {boolean}
     * @memberof GetAggregatorSupportedChainsResponse
     */
    success?: boolean;
}
