/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetB402SupportedConfigurationsV1ResponseDataKindsInner } from './get-b402-supported-configurations-v1-response-data-kinds-inner';

/**
 *
 * @export
 * @interface GetB402SupportedConfigurationsV1ResponseData
 */
export interface GetB402SupportedConfigurationsV1ResponseData {
    /**
     *
     * @type {Array<GetB402SupportedConfigurationsV1ResponseDataKindsInner>}
     * @memberof GetB402SupportedConfigurationsV1ResponseData
     */
    kinds?: Array<GetB402SupportedConfigurationsV1ResponseDataKindsInner>;
    /**
     *
     * @type {Array<string>}
     * @memberof GetB402SupportedConfigurationsV1ResponseData
     */
    extensions?: Array<string>;
    /**
     *
     * @type {{ [key: string]: Array<string> | undefined; }}
     * @memberof GetB402SupportedConfigurationsV1ResponseData
     */
    signers?: { [key: string]: Array<string> | undefined };
}
