/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner } from './get-rwa-token-issuance-platforms-response-data-inner-chain-distribution-inner';

/**
 *
 * @export
 * @interface GetRwaTokenIssuancePlatformsResponseDataInner
 */
export interface GetRwaTokenIssuancePlatformsResponseDataInner {
    /**
     * Unique platform identifier. Examples: ondo=Ondo Finance, bstock=bStocks.
     * @type {string}
     * @memberof GetRwaTokenIssuancePlatformsResponseDataInner
     */
    platformId?: string;
    /**
     * Number of underlying assets corresponding to the RWA tokens.
     * @type {number}
     * @memberof GetRwaTokenIssuancePlatformsResponseDataInner
     */
    tickerCount?: number;
    /**
     * RWA token distribution across chains.
     * @type {Array<GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner>}
     * @memberof GetRwaTokenIssuancePlatformsResponseDataInner
     */
    chainDistribution?: Array<GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner>;
    /**
     * Platform official website. Null when unavailable.
     * @type {string}
     * @memberof GetRwaTokenIssuancePlatformsResponseDataInner
     */
    website?: string | null;
    /**
     * Platform logo URL. Null when unavailable.
     * @type {string}
     * @memberof GetRwaTokenIssuancePlatformsResponseDataInner
     */
    logoUrl?: string | null;
}
