/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EVM transaction payload. Required when `binanceChainId` belongs to an EVM chain.
 * @export
 * @interface GetGasLimitRequestEvmTx
 */
export interface GetGasLimitRequestEvmTx {
    /**
     * Sender address.
     * @type {string}
     * @memberof GetGasLimitRequestEvmTx
     */
    from: string;
    /**
     * Destination address (contract or EOA).
     * @type {string}
     * @memberof GetGasLimitRequestEvmTx
     */
    to: string;
    /**
     * Native token amount in wei (integer string). Use \"0\" for ERC-20 transfers.
     * @type {string}
     * @memberof GetGasLimitRequestEvmTx
     */
    value: string;
    /**
     * ABI-encoded calldata (hex). Optional when no contract call is involved.
     * @type {string}
     * @memberof GetGasLimitRequestEvmTx
     */
    data: string;
}
