/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetAddressPortfolioOverviewResponseDataDailyPnlInner
 */
export interface GetAddressPortfolioOverviewResponseDataDailyPnlInner {
    /**
     * Date in YYYY-MM-DD format.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseDataDailyPnlInner
     */
    date?: string;
    /**
     * Realized PnL for this day, denominated in USD. Positive means profit, negative means loss.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseDataDailyPnlInner
     */
    pnlUsd?: string;
}
