/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetHoldersRankingResponseDataInner } from './get-holders-ranking-response-data-inner';

/**
 *
 * @export
 * @interface GetHoldersRankingResponse
 */
export interface GetHoldersRankingResponse {
    /**
     *
     * @type {number}
     * @memberof GetHoldersRankingResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetHoldersRankingResponse
     */
    msg?: string;
    /**
     * Holder list.
     * @type {Array<GetHoldersRankingResponseDataInner>}
     * @memberof GetHoldersRankingResponse
     */
    data?: Array<GetHoldersRankingResponseDataInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetHoldersRankingResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetHoldersRankingResponse
     */
    success?: boolean;
}
