/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetRfqOrderStatusResponseData } from './get-rfq-order-status-response-data';

/**
 *
 * @export
 * @interface GetRfqOrderStatusResponse
 */
export interface GetRfqOrderStatusResponse {
    /**
     *
     * @type {number}
     * @memberof GetRfqOrderStatusResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetRfqOrderStatusResponse
     */
    msg?: string;
    /**
     *
     * @type {GetRfqOrderStatusResponseData}
     * @memberof GetRfqOrderStatusResponse
     */
    data?: GetRfqOrderStatusResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetRfqOrderStatusResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetRfqOrderStatusResponse
     */
    success?: boolean;
}
