/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Position-level metadata. Present for concentrated-liquidity / locked / farming positions; null otherwise. Fields are null when not applicable to the position type.
 * @export
 * @interface GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
 */
export interface GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail {
    /**
     * Position index (e.g. the Uniswap-V3-style position number).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    positionIndex?: string | null;
    /**
     * NFT token ID for concentrated-liquidity positions, prefixed with `#` (e.g. `\"#7225901\"`). Null for non-NFT positions. The `#` prefix may be passed as-is to a transaction build endpoint (`lp-add` / `lp-remove` / `claim` `LP_FEE`) — the service strips it automatically; passing the raw id without `#` is also accepted.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    nftId?: string | null;
    /**
     * Unix timestamp (seconds) when the position unlocks. Null if no lock.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    unlockTime?: string | null;
    /**
     * Whether the unlock time has been reached.
     * @type {boolean}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    unlockTimeReached?: boolean | null;
    /**
     * Lower tick bound for concentrated-liquidity positions.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    tickLower?: string | null;
    /**
     * Upper tick bound for concentrated-liquidity positions.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    tickUpper?: string | null;
    /**
     * Whether the position is currently in-range (active).
     * @type {boolean}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    active?: boolean | null;
    /**
     * Merkle proofs keyed by reward token address. Required when claiming PancakeSwap Infinity (V4) rewards.
     * @type {{ [key: string]: Array<string> | undefined; }}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    proofs?: { [key: string]: Array<string> | undefined } | null;
    /**
     * Staking lifecycle state. Complete value set: active (earning), deactivating (unstaking in progress, rewards stop), inactive (fully unstaked).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    stakeState?: string | null;
    /**
     * Claim types available for this position. Values map to the `claimType` field of `POST /transaction/claim` and determine which companion fields a claim requires.
     * @type {Array<string>}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    claimTypes?: Array<string> | null;
    /**
     * Redemption record ID (for pending redemptions). Null when not a pending redemption.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    redemptionId?: string | null;
}
