/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTokenAdvancedInfoResponseData
 */
export interface GetTokenAdvancedInfoResponseData {
    /**
     * Unique chain identifier.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    binanceChainId?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    tokenContractAddress?: string;
    /**
     * Whether the token is internal to the platform. 0 = no, 1 = yes.
     * @type {number}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    isInternal?: number;
    /**
     * Protocol ID the token belongs to. Null when no protocol is associated.
     * @type {number}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    protocolId?: number | null;
    /**
     * Token launch progress for inner-market tokens, range 0–100.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    progress?: string | null;
    /**
     * Token creation time, Unix millisecond timestamp.
     * @type {number | bigint}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    createTime?: number | bigint;
    /**
     * Token creator wallet address.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    creatorAddress?: string;
    /**
     * Total tokens the developer has ever created.
     * @type {number | bigint}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    devCreatedTokenCount?: number | bigint;
    /**
     * Total tokens the developer has successfully launched (migrated).
     * @type {number | bigint}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    devMigratedTokenCount?: number | bigint;
    /**
     * Developer launch success rate. \"53.5\" means 53.5%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    devMigratedTokenPercent?: string;
    /**
     * Top 10 addresses combined holding percentage. \"40.08\" means 40.08%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    top10HoldingPercent?: string;
    /**
     * Developer holding percentage. \"5.23\" means 5.23%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    devHoldingPercent?: string;
    /**
     * Smart money holding percentage. \"2.15\" means 2.15%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    smartMoneyHoldingPercent?: string;
    /**
     * KOL holding percentage. \"1.5\" means 1.5%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    kolHoldingPercent?: string;
    /**
     * Bundler holding percentage. \"12.3\" means 12.3%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    bundlerHoldingPercent?: string;
    /**
     * Professional holder percentage. \"4.2\" means 4.2%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    proHoldingPercent?: string;
    /**
     * Fresh wallet holding percentage. \"3.8\" means 3.8%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    freshWalletHoldingPercent?: string;
    /**
     * Sniper holding percentage. \"3.1\" means 3.1%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    sniperHoldingPercent?: string;
    /**
     * Insider holding percentage. \"2.5\" means 2.5%.
     * @type {string}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    insiderHoldingPercent?: string;
    /**
     * Number of holding addresses.
     * @type {number | bigint}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    holders?: number | bigint;
    /**
     * Number of Binance MPC wallets holding this token.
     * @type {number | bigint}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    bnHolderCount?: number | bigint;
    /**
     * Number of Binance MPC wallets that traded via Binance Web3 DEX in the last 7 days.
     * @type {number | bigint}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    bnTraderCount7D?: number | bigint;
    /**
     * Token tags.
     * @type {Array<string>}
     * @memberof GetTokenAdvancedInfoResponseData
     */
    tokenTags?: Array<string>;
}
