/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetHotTokenListResponseData } from './get-hot-token-list-response-data';

/**
 *
 * @export
 * @interface GetHotTokenListResponse
 */
export interface GetHotTokenListResponse {
    /**
     *
     * @type {number}
     * @memberof GetHotTokenListResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetHotTokenListResponse
     */
    msg?: string;
    /**
     *
     * @type {GetHotTokenListResponseData}
     * @memberof GetHotTokenListResponse
     */
    data?: GetHotTokenListResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetHotTokenListResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetHotTokenListResponse
     */
    success?: boolean;
}
