/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTransactionSupportedChainsResponseDataInner } from './get-transaction-supported-chains-response-data-inner';

/**
 *
 * @export
 * @interface GetTransactionSupportedChainsResponse
 */
export interface GetTransactionSupportedChainsResponse {
    /**
     * Business status code. 0 indicates success; any non-zero value indicates a business error.
     * @type {number}
     * @memberof GetTransactionSupportedChainsResponse
     */
    code?: number;
    /**
     * Status description message.
     * @type {string}
     * @memberof GetTransactionSupportedChainsResponse
     */
    msg?: string;
    /**
     * List of supported blockchain networks.
     * @type {Array<GetTransactionSupportedChainsResponseDataInner>}
     * @memberof GetTransactionSupportedChainsResponse
     */
    data?: Array<GetTransactionSupportedChainsResponseDataInner>;
    /**
     * Server response timestamp in milliseconds.
     * @type {number | bigint}
     * @memberof GetTransactionSupportedChainsResponse
     */
    timestamp?: number | bigint;
    /**
     * Convenience flag derived from `code == 0`.
     * @type {boolean}
     * @memberof GetTransactionSupportedChainsResponse
     */
    success?: boolean;
}
