/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetErc20ApproveTransactionResponseDataInner
 */
export interface GetErc20ApproveTransactionResponseDataInner {
    /**
     * ABI-encoded calldata for the ERC-20 `approve()` call. Selector + padded spender + padded amount.
     * @type {string}
     * @memberof GetErc20ApproveTransactionResponseDataInner
     */
    data?: string;
    /**
     * DEX router contract address (the spender in the `approve()` call). Configured per chain.
     * @type {string}
     * @memberof GetErc20ApproveTransactionResponseDataInner
     */
    dexContractAddress?: string;
    /**
     * Gas limit ceiling for the approve transaction (integer string, gas units).
     * @type {string}
     * @memberof GetErc20ApproveTransactionResponseDataInner
     */
    gasLimit?: string;
    /**
     * Gas price for the approve transaction (integer string, wei).
     * @type {string}
     * @memberof GetErc20ApproveTransactionResponseDataInner
     */
    gasPrice?: string;
}
