/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Segment\'s sell-token info. Same shape as the top-level `fromToken`.
 * @export
 * @interface GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken
 */
export interface GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken {
    /**
     *
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken
     */
    tokenContractAddress?: string;
    /**
     *
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken
     */
    tokenSymbol?: string;
}
