/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetDeFiPositionsResponseData } from './get-de-fi-positions-response-data';

/**
 *
 * @export
 * @interface GetDeFiPositionsResponse
 */
export interface GetDeFiPositionsResponse {
    /**
     * Business status code. 0 indicates success.
     * @type {number}
     * @memberof GetDeFiPositionsResponse
     */
    code?: number;
    /**
     * Human-readable status message.
     * @type {string}
     * @memberof GetDeFiPositionsResponse
     */
    msg?: string;
    /**
     *
     * @type {GetDeFiPositionsResponseData}
     * @memberof GetDeFiPositionsResponse
     */
    data?: GetDeFiPositionsResponseData;
    /**
     * Server timestamp in milliseconds.
     * @type {number | bigint}
     * @memberof GetDeFiPositionsResponse
     */
    timestamp?: number | bigint;
    /**
     * Whether the request succeeded (mirrors `code == 0`).
     * @type {boolean}
     * @memberof GetDeFiPositionsResponse
     */
    success?: boolean;
}
