/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAddressTrackerTradesResponseData } from './get-address-tracker-trades-response-data';

/**
 *
 * @export
 * @interface GetAddressTrackerTradesResponse
 */
export interface GetAddressTrackerTradesResponse {
    /**
     * Business status code. 0 indicates success.
     * @type {number}
     * @memberof GetAddressTrackerTradesResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetAddressTrackerTradesResponse
     */
    msg?: string;
    /**
     *
     * @type {GetAddressTrackerTradesResponseData}
     * @memberof GetAddressTrackerTradesResponse
     */
    data?: GetAddressTrackerTradesResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetAddressTrackerTradesResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetAddressTrackerTradesResponse
     */
    success?: boolean;
}
