/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Token latest PnL details.
 * @export
 * @interface GetPortfolioTokenLatestPnLResponseData
 */
export interface GetPortfolioTokenLatestPnLResponseData {
    /**
     * Cumulative realized PnL for this token, denominated in USD. Positive means profit, negative means loss.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    realizedPnlUsd?: string;
    /**
     * Realized PnL percentage. No percent sign included.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    realizedPnlPercent?: string;
    /**
     * Cumulative buy spend for this token, denominated in USD.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    buyTxVolume?: string;
    /**
     * Cumulative buy quantity (token units).
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    buyAmount?: string;
    /**
     * Number of buy transactions.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    buyTxCount?: string;
    /**
     * Cumulative sell proceeds for this token, denominated in USD.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    sellTxVolume?: string;
    /**
     * Cumulative sell quantity (token units).
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    sellAmount?: string;
    /**
     * Number of sell transactions.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    sellTxCount?: string;
    /**
     * Average buy price, denominated in USD. Calculated as buyTxVolume / buyAmount.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    buyAvgPrice?: string;
    /**
     * Average sell price, denominated in USD. Calculated as sellTxVolume / sellAmount.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    sellAvgPrice?: string;
    /**
     * Current market value of the address\'s holding in this token, denominated in USD. Returns \"0\" when fully sold.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    tokenBalanceUsd?: string;
    /**
     * Current holding amount (token units). Returns \"0\" when fully sold.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    tokenBalanceAmount?: string;
    /**
     * Maximum historical holding amount (token units).
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    maxBalanceAmount?: string;
    /**
     * Cumulative holding duration in milliseconds. Counts only actual holding periods; gaps between sell and re-buy are excluded. If still holding, counts up to the current time.
     * @type {string}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    holdingDuration?: string;
    /**
     * Whether PnL calculation is meaningful for this token. true=supported; false=not supported. Returns false for stablecoins (USDT/USDC/DAI etc.), native tokens (ETH/BNB/SOL etc.), and wrapped tokens (WETH/WBNB/WSOL etc.). Returns true for regular trading tokens.
     * @type {boolean}
     * @memberof GetPortfolioTokenLatestPnLResponseData
     */
    isPnlSupported?: boolean;
}
