/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetGasPriceResponseData } from './get-gas-price-response-data';

/**
 *
 * @export
 * @interface GetGasPriceResponse
 */
export interface GetGasPriceResponse {
    /**
     * Business status code. 0 indicates success.
     * @type {number}
     * @memberof GetGasPriceResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetGasPriceResponse
     */
    msg?: string;
    /**
     *
     * @type {GetGasPriceResponseData}
     * @memberof GetGasPriceResponse
     */
    data?: GetGasPriceResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetGasPriceResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetGasPriceResponse
     */
    success?: boolean;
}
