/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetHotTokenListResponseDataItemsInner } from './get-hot-token-list-response-data-items-inner';

/**
 *
 * @export
 * @interface GetHotTokenListResponseData
 */
export interface GetHotTokenListResponseData {
    /**
     * Current page number. Null when no more data is available.
     * @type {number}
     * @memberof GetHotTokenListResponseData
     */
    page?: number | null;
    /**
     * Hot token list.
     * @type {Array<GetHotTokenListResponseDataItemsInner>}
     * @memberof GetHotTokenListResponseData
     */
    items?: Array<GetHotTokenListResponseDataItemsInner>;
}
