/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Pool-level metadata. Fields are null when not applicable to the pool type (e.g. `tickSpacing`/`hooks` only for concentrated-liquidity pools).
 * @export
 * @interface GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
 */
export interface GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail {
    /**
     * Pool expiry timestamp (Unix seconds). Null if no expiry.
     * @type {number | bigint}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    expiry?: number | bigint | null;
    /**
     * Fee tier. For PancakeSwap V3-style pools this is the encoded fee (e.g. \"500\" = 0.05%); for V4-style pools a flag-encoded value.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    feeTier?: string | null;
    /**
     * LP fee portion in basis points (V4-style pools).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    lpFee?: string | null;
    /**
     * Tick spacing for concentrated-liquidity pools.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    tickSpacing?: string | null;
    /**
     * Whether the pool uses a dynamic (hook-managed) fee (V4-style pools).
     * @type {boolean}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    isDynamicFee?: boolean | null;
    /**
     * Hook fee portion in basis points (V4-style pools).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    hookFee?: string | null;
    /**
     * Current pool tick (V4-style pools).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    tick?: string | null;
    /**
     * Hook contract address (V4-style pools). Zero address when no hook.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    hooks?: string | null;
    /**
     * Protocol fee on swaps in basis points (V4-style pools).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    swapProtocolFee?: string | null;
    /**
     * Encoded pool parameters, e.g. `0x` + 64-char hex (V4-style pools).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    parameters?: string | null;
    /**
     * Total pool fee in basis points (V4-style pools).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    fee?: string | null;
    /**
     * Spoke pool name (e.g. across-protocol bridges).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    spokeName?: string | null;
    /**
     * Number of reserves in multi-asset pools.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    reserveCount?: string | null;
    /**
     * Vault name for vault-style protocols.
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPoolDetail
     */
    vaultName?: string | null;
}
