/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
 */
export interface GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner {
    /**
     * Chain identifier.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    binanceChainId?: string;
    /**
     * Token contract address. Empty string for the chain\'s native asset.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    tokenContractAddress?: string;
    /**
     * Wallet address echoed from the request.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    address?: string;
    /**
     * Token ticker.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    symbol?: string;
    /**
     * Token amount scaled by decimals.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    balance?: string;
    /**
     * Raw token amount in the smallest unit. Empty string when the chain doesn\'t expose a raw value.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    rawBalance?: string;
    /**
     * Token USD price.
     * @type {string}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    tokenPrice?: string;
    /**
     * Whether the token is risk-flagged.
     * @type {boolean}
     * @memberof GetTokenBalancesByAddressResponseDataInnerTokenAssetsInner
     */
    isRiskToken?: boolean;
}
