/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Buy-token metadata. Same shape as `fromToken`.
 * @export
 * @interface GetAggregatedQuoteResponseDataInnerToToken
 */
export interface GetAggregatedQuoteResponseDataInnerToToken {
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerToToken
     */
    tokenContractAddress?: string;
    /**
     * Token ticker.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerToToken
     */
    tokenSymbol?: string;
    /**
     * Token USD price (decimal string).
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerToToken
     */
    tokenUnitPrice?: string;
    /**
     * Token decimals.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerToToken
     */
    decimal?: string;
    /**
     * Whether the token is a honeypot.
     * @type {boolean}
     * @memberof GetAggregatedQuoteResponseDataInnerToToken
     */
    isHoneyPot?: boolean;
    /**
     * Token tax rate.
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerToToken
     */
    taxRate?: string;
}
