/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTokenTradesResponseDataTradesInnerChangedTokenInfoInner
 */
export interface GetTokenTradesResponseDataTradesInnerChangedTokenInfoInner {
    /**
     * Token amount traded.
     * @type {string}
     * @memberof GetTokenTradesResponseDataTradesInnerChangedTokenInfoInner
     */
    amount?: string;
    /**
     * Token symbol.
     * @type {string}
     * @memberof GetTokenTradesResponseDataTradesInnerChangedTokenInfoInner
     */
    tokenSymbol?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetTokenTradesResponseDataTradesInnerChangedTokenInfoInner
     */
    tokenContractAddress?: string;
}
