/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetRwaUnderlyingInfoResponseDataCompanyInfo } from './get-rwa-underlying-info-response-data-company-info';
// May contain unused imports in some cases
// @ts-ignore
import type { GetRwaUnderlyingInfoResponseDataProtectionsValue } from './get-rwa-underlying-info-response-data-protections-value';

/**
 * Underlying company information and protections.
 * @export
 * @interface GetRwaUnderlyingInfoResponseData
 */
export interface GetRwaUnderlyingInfoResponseData {
    /**
     * Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana).
     * @type {string}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    binanceChainId?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    tokenContractAddress?: string;
    /**
     * Unique platform identifier.
     * @type {string}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    platformId?: string;
    /**
     * Underlying asset ticker symbol.
     * @type {string}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    underlyingTicker?: string;
    /**
     * Underlying asset full name.
     * @type {string}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    underlyingFullName?: string;
    /**
     * Asset type. 1=Stock, 2=Pre-IPO, 3=ETF.
     * @type {number}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    assetType?: number;
    /**
     * Token-to-share exchange ratio. E.g. \"1.003701\" means 1 token ≈ 1.003701 underlying shares.
     * @type {string}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    tokenToShareRatio?: string;
    /**
     * Investor protection mechanisms, keyed by mechanism type. Each entry includes whether it is supported and a related proof/report link. Known keys: dailyAttestationReport, monthlyAttestationReport, collateralReport. New keys may be added per platform.
     * @type {{ [key: string]: GetRwaUnderlyingInfoResponseDataProtectionsValue | undefined; }}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    protections?: { [key: string]: GetRwaUnderlyingInfoResponseDataProtectionsValue | undefined };
    /**
     *
     * @type {GetRwaUnderlyingInfoResponseDataCompanyInfo}
     * @memberof GetRwaUnderlyingInfoResponseData
     */
    companyInfo?: GetRwaUnderlyingInfoResponseDataCompanyInfo | null;
}
