/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Solana transaction payload. Required when `binanceChainId=CT_501`.
 * @export
 * @interface GetGasLimitRequestSolTx
 */
export interface GetGasLimitRequestSolTx {
    /**
     * Base64-encoded unsigned Solana transaction.
     * @type {string}
     * @memberof GetGasLimitRequestSolTx
     */
    base64Tx: string;
}
