/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetB402SupportedConfigurationsV2ResponseData } from './get-b402-supported-configurations-v2-response-data';

/**
 *
 * @export
 * @interface GetB402SupportedConfigurationsV2Response
 */
export interface GetB402SupportedConfigurationsV2Response {
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    errorData?: string | null;
    /**
     *
     * @type {GetB402SupportedConfigurationsV2ResponseData}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    data?: GetB402SupportedConfigurationsV2ResponseData | null;
    /**
     *
     * @type {object}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    subData?: object | null;
    /**
     *
     * @type {object}
     * @memberof GetB402SupportedConfigurationsV2Response
     */
    params?: object | null;
}
