/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetPortfolioDexHistoryResponseData } from './get-portfolio-dex-history-response-data';

/**
 *
 * @export
 * @interface GetPortfolioDexHistoryResponse
 */
export interface GetPortfolioDexHistoryResponse {
    /**
     * Business status code. 0 indicates success.
     * @type {number}
     * @memberof GetPortfolioDexHistoryResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetPortfolioDexHistoryResponse
     */
    msg?: string;
    /**
     *
     * @type {GetPortfolioDexHistoryResponseData}
     * @memberof GetPortfolioDexHistoryResponse
     */
    data?: GetPortfolioDexHistoryResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetPortfolioDexHistoryResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetPortfolioDexHistoryResponse
     */
    success?: boolean;
}
