/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTransactionStatusResponseDataFromTokenDetailsInner
 */
export interface GetTransactionStatusResponseDataFromTokenDetailsInner {
    /**
     * Token ticker. Null when metadata cannot be resolved.
     * @type {string}
     * @memberof GetTransactionStatusResponseDataFromTokenDetailsInner
     */
    symbol?: string | null;
    /**
     * Token amount in the smallest unit (integer string). \"1500000\" = 1.5 USDT (decimals=6).
     * @type {string}
     * @memberof GetTransactionStatusResponseDataFromTokenDetailsInner
     */
    amount?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetTransactionStatusResponseDataFromTokenDetailsInner
     */
    tokenAddress?: string;
}
