/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTransactionStatusResponseDataFromTokenDetailsInner } from './get-transaction-status-response-data-from-token-details-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetTransactionStatusResponseDataToTokenDetailsInner } from './get-transaction-status-response-data-to-token-details-inner';

/**
 * Transaction details. Null when the transaction is not found in any source table.
 * @export
 * @interface GetTransactionStatusResponseData
 */
export interface GetTransactionStatusResponseData {
    /**
     * Chain identifier.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    binanceChainId?: string;
    /**
     * Transaction hash.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    txHash?: string;
    /**
     * Block height the transaction was included in (decimal string).
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    height?: string;
    /**
     * Transaction timestamp (Unix epoch milliseconds, string form).
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    txTime?: string;
    /**
     * Transaction status. Typical values \"success\" or \"failed\".
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    status?: string;
    /**
     * Sender address.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    fromAddress?: string;
    /**
     * Recipient address (typically the DEX router).
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    toAddress?: string;
    /**
     * Error message when `status=failed`; null otherwise.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    errorMsg?: string | null;
    /**
     * Gas limit (decimal string). Null on Solana.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    gasLimit?: string | null;
    /**
     * Gas actually consumed (decimal string, wei). Null on Solana.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    gasUsed?: string | null;
    /**
     * Gas price (decimal string, wei). Null on Solana.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    gasPrice?: string | null;
    /**
     * Transaction fee in the chain\'s native unit. Null on Solana.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    txFee?: string | null;
    /**
     * EIP-1559 priority fee (wei) on EVM, prioritization fee (lamports) on Solana, null on legacy EVM transactions.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    priorityFee?: string | null;
    /**
     * Transaction action; currently fixed to \"Swap\" when an aggregator event is present. Null otherwise.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    txType?: string | null;
    /**
     * DEX router contract address (mirrors `toAddress`). Null when no aggregator event is present.
     * @type {string}
     * @memberof GetTransactionStatusResponseData
     */
    dexRouter?: string | null;
    /**
     * Sell-token details. Populated when an aggregator event is present; null otherwise.
     * @type {Array<GetTransactionStatusResponseDataFromTokenDetailsInner>}
     * @memberof GetTransactionStatusResponseData
     */
    fromTokenDetails?: Array<GetTransactionStatusResponseDataFromTokenDetailsInner> | null;
    /**
     * Buy-token details. Populated when an aggregator event is present; null otherwise.
     * @type {Array<GetTransactionStatusResponseDataToTokenDetailsInner>}
     * @memberof GetTransactionStatusResponseData
     */
    toTokenDetails?: Array<GetTransactionStatusResponseDataToTokenDetailsInner> | null;
}
