/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
 */
export interface GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner {
    /**
     * Sender address.
     * @type {string}
     * @memberof GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
     */
    from?: string;
    /**
     * Receiver address.
     * @type {string}
     * @memberof GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
     */
    to?: string;
    /**
     * Whether the sender is a contract.
     * @type {boolean}
     * @memberof GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
     */
    isFromContract?: boolean | null;
    /**
     * Whether the receiver is a contract.
     * @type {boolean}
     * @memberof GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
     */
    isToContract?: boolean | null;
    /**
     * Internal call amount.
     * @type {string}
     * @memberof GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
     */
    amount?: string;
    /**
     * Internal call status.
     * @type {string}
     * @memberof GetTransactionDetailByHashResponseDataInnerInternalTransactionDetailsInner
     */
    txStatus?: string;
}
