/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTransactionsByAddressResponseDataInner } from './get-transactions-by-address-response-data-inner';

/**
 *
 * @export
 * @interface GetTransactionsByAddressResponse
 */
export interface GetTransactionsByAddressResponse {
    /**
     *
     * @type {number}
     * @memberof GetTransactionsByAddressResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetTransactionsByAddressResponse
     */
    msg?: string;
    /**
     * One entry per queried chain. Each entry contains a transaction list and its own pagination cursor.
     * @type {Array<GetTransactionsByAddressResponseDataInner>}
     * @memberof GetTransactionsByAddressResponse
     */
    data?: Array<GetTransactionsByAddressResponseDataInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetTransactionsByAddressResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetTransactionsByAddressResponse
     */
    success?: boolean;
}
