/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAddressPortfolioOverviewResponseDataDailyPnlInner } from './get-address-portfolio-overview-response-data-daily-pnl-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent } from './get-address-portfolio-overview-response-data-token-count-by-pnl-percent';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner } from './get-address-portfolio-overview-response-data-top-pnl-token-list-inner';

/**
 * Address portfolio overview.
 * @export
 * @interface GetAddressPortfolioOverviewResponseData
 */
export interface GetAddressPortfolioOverviewResponseData {
    /**
     * Total realized PnL within the time frame, denominated in USD. Positive means profit, negative means loss.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    realizedPnlUsd?: string;
    /**
     * Realized PnL percentage within the time frame. \"16.44\" means +16.44%. No percent sign included.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    realizedPnlPercent?: string;
    /**
     * Daily realized PnL breakdown, sorted by date descending (most recent first). Number of entries matches the timeFrame.
     * @type {Array<GetAddressPortfolioOverviewResponseDataDailyPnlInner>}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    dailyPnl?: Array<GetAddressPortfolioOverviewResponseDataDailyPnlInner>;
    /**
     * Win rate within the time frame. \"61.11\" means 61.11%. No percent sign included.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    winRate?: string;
    /**
     *
     * @type {GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    tokenCountByPnlPercent?: GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent;
    /**
     * Number of buy transactions within the time frame.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    buyTxCount?: string;
    /**
     * Number of sell transactions within the time frame.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    sellTxCount?: string;
    /**
     * Total number of distinct tokens traded within the time frame.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    totalTokenCount?: string;
    /**
     * Total buy volume within the time frame, denominated in USD.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    buyTxVolume?: string;
    /**
     * Total sell volume within the time frame, denominated in USD.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    sellTxVolume?: string;
    /**
     * Average buy value per transaction within the time frame, denominated in USD.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    avgBuyValueUsd?: string;
    /**
     * Total realized PnL of the top 3 profit tokens, denominated in USD.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    top3PnlTokenSumUsd?: string;
    /**
     * Percentage of total realized PnL contributed by the top 3 profit tokens. No percent sign included.
     * @type {string}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    top3PnlTokenPercent?: string;
    /**
     * Top 3 tokens by realized PnL. Returns fewer items if fewer than 3 tokens were traded.
     * @type {Array<GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner>}
     * @memberof GetAddressPortfolioOverviewResponseData
     */
    topPnlTokenList?: Array<GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner>;
}
