/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionCollectionDetail } from './get-de-fi-positions-response-data-address-list-inner-protocol-list-inner-pool-list-inner-position-collection-list-inner-position-collection-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInner } from './get-de-fi-positions-response-data-address-list-inner-protocol-list-inner-pool-list-inner-position-collection-list-inner-position-list-inner';

/**
 * A collection of positions grouped under the same underlying asset.
 * @export
 * @interface GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInner
 */
export interface GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInner {
    /**
     * Collection unique identifier (64-char hex, no `0x` prefix).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInner
     */
    positionCollectionId?: string;
    /**
     *
     * @type {GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionCollectionDetail}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInner
     */
    positionCollectionDetail?: GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionCollectionDetail | null;
    /**
     * Total value of all positions in this collection (USD).
     * @type {string}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInner
     */
    positionCollectionTotalValue?: string;
    /**
     * List of positions in this collection.
     * @type {Array<GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInner>}
     * @memberof GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInner
     */
    positionList?: Array<GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInner>;
}
