/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetB402SupportedConfigurationsV2ResponseDataKindsInnerExtra } from './get-b402-supported-configurations-v2-response-data-kinds-inner-extra';

/**
 *
 * @export
 * @interface GetB402SupportedConfigurationsV2ResponseDataKindsInner
 */
export interface GetB402SupportedConfigurationsV2ResponseDataKindsInner {
    /**
     *
     * @type {number}
     * @memberof GetB402SupportedConfigurationsV2ResponseDataKindsInner
     */
    x402Version: number;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV2ResponseDataKindsInner
     */
    scheme: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV2ResponseDataKindsInner
     */
    network: string;
    /**
     *
     * @type {GetB402SupportedConfigurationsV2ResponseDataKindsInnerExtra}
     * @memberof GetB402SupportedConfigurationsV2ResponseDataKindsInner
     */
    extra: GetB402SupportedConfigurationsV2ResponseDataKindsInnerExtra;
}
