/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Legacy EVM gas price tiers (wei, integer string). Null on non-EVM chains.
 * @export
 * @interface GetGasPriceResponseDataEvmLegacyGasPrice
 */
export interface GetGasPriceResponseDataEvmLegacyGasPrice {
    /**
     * Slow tier gas price in wei.
     * @type {string}
     * @memberof GetGasPriceResponseDataEvmLegacyGasPrice
     */
    lowGasPrice?: string;
    /**
     * Average tier gas price in wei.
     * @type {string}
     * @memberof GetGasPriceResponseDataEvmLegacyGasPrice
     */
    mediumGasPrice?: string;
    /**
     * Fast tier gas price in wei.
     * @type {string}
     * @memberof GetGasPriceResponseDataEvmLegacyGasPrice
     */
    highGasPrice?: string;
}
