/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTokenPriceResponseDataInner } from './get-token-price-response-data-inner';

/**
 *
 * @export
 * @interface GetTokenPriceResponse
 */
export interface GetTokenPriceResponse {
    /**
     *
     * @type {number}
     * @memberof GetTokenPriceResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetTokenPriceResponse
     */
    msg?: string;
    /**
     * One price entry per requested token.
     * @type {Array<GetTokenPriceResponseDataInner>}
     * @memberof GetTokenPriceResponse
     */
    data?: Array<GetTokenPriceResponseDataInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetTokenPriceResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetTokenPriceResponse
     */
    success?: boolean;
}
