/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetB402SupportedConfigurationsV2Response1DataKindsInner } from './get-b402-supported-configurations-v2-response1-data-kinds-inner';

/**
 *
 * @export
 * @interface GetB402SupportedConfigurationsV2Response1Data
 */
export interface GetB402SupportedConfigurationsV2Response1Data {
    /**
     *
     * @type {Array<GetB402SupportedConfigurationsV2Response1DataKindsInner>}
     * @memberof GetB402SupportedConfigurationsV2Response1Data
     */
    kinds: Array<GetB402SupportedConfigurationsV2Response1DataKindsInner>;
    /**
     *
     * @type {Array<string>}
     * @memberof GetB402SupportedConfigurationsV2Response1Data
     */
    extensions: Array<string>;
    /**
     *
     * @type {{ [key: string]: Array<string> | undefined; }}
     * @memberof GetB402SupportedConfigurationsV2Response1Data
     */
    signers: { [key: string]: Array<string> | undefined };
}
