/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Historical token launch summary for this developer.
 * @export
 * @interface GetTokenDevInfoResponseDataDevLaunchedInfo
 */
export interface GetTokenDevInfoResponseDataDevLaunchedInfo {
    /**
     * Total number of tokens launched by this developer via launch platforms.
     * @type {string}
     * @memberof GetTokenDevInfoResponseDataDevLaunchedInfo
     */
    totalToken?: string;
    /**
     * Number of tokens successfully migrated to external DEX by this developer.
     * @type {string}
     * @memberof GetTokenDevInfoResponseDataDevLaunchedInfo
     */
    migratedCount?: string;
}
