/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner
 */
export interface GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner {
    /**
     * Token amount in the pool.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner
     */
    tokenAmount?: string;
    /**
     * Token symbol.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner
     */
    tokenSymbol?: string;
    /**
     * Token full name.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner
     */
    tokenName?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner
     */
    tokenContractAddress?: string;
    /**
     * Token logo link. Null when no logo.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner
     */
    tokenLogoUrl?: string | null;
}
