/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTokenTradesResponseData } from './get-token-trades-response-data';

/**
 *
 * @export
 * @interface GetTokenTradesResponse
 */
export interface GetTokenTradesResponse {
    /**
     *
     * @type {number}
     * @memberof GetTokenTradesResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetTokenTradesResponse
     */
    msg?: string;
    /**
     *
     * @type {GetTokenTradesResponseData}
     * @memberof GetTokenTradesResponse
     */
    data?: GetTokenTradesResponseData;
    /**
     *
     * @type {number | bigint}
     * @memberof GetTokenTradesResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetTokenTradesResponse
     */
    success?: boolean;
}
