/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTopTradersResponseDataInner } from './get-top-traders-response-data-inner';

/**
 *
 * @export
 * @interface GetTopTradersResponse
 */
export interface GetTopTradersResponse {
    /**
     *
     * @type {number}
     * @memberof GetTopTradersResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetTopTradersResponse
     */
    msg?: string;
    /**
     * Top profit-making address list.
     * @type {Array<GetTopTradersResponseDataInner>}
     * @memberof GetTopTradersResponse
     */
    data?: Array<GetTopTradersResponseDataInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetTopTradersResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetTopTradersResponse
     */
    success?: boolean;
}
