/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Token tag information.
 * @export
 * @interface GetTokenBasicInfoResponseDataTagList
 */
export interface GetTokenBasicInfoResponseDataTagList {
    /**
     * True indicates the token is listed on major centralized exchanges or widely recognized by the community.
     * @type {boolean}
     * @memberof GetTokenBasicInfoResponseDataTagList
     */
    isRecognized?: boolean | null;
}
