/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra } from './get-b402-supported-configurations-v1-response1-data-kinds-inner-extra';

/**
 *
 * @export
 * @interface GetB402SupportedConfigurationsV1Response1DataKindsInner
 */
export interface GetB402SupportedConfigurationsV1Response1DataKindsInner {
    /**
     *
     * @type {number}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInner
     */
    x402Version?: number;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInner
     */
    scheme?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInner
     */
    network?: string;
    /**
     *
     * @type {GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInner
     */
    extra?: GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra;
}
