/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatedQuoteResponseDataInnerDexRouterListInnerDexProtocol } from './get-aggregated-quote-response-data-inner-dex-router-list-inner-dex-protocol';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken } from './get-aggregated-quote-response-data-inner-dex-router-list-inner-from-token';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAggregatedQuoteResponseDataInnerDexRouterListInnerToToken } from './get-aggregated-quote-response-data-inner-dex-router-list-inner-to-token';

/**
 *
 * @export
 * @interface GetAggregatedQuoteResponseDataInnerDexRouterListInner
 */
export interface GetAggregatedQuoteResponseDataInnerDexRouterListInner {
    /**
     *
     * @type {GetAggregatedQuoteResponseDataInnerDexRouterListInnerDexProtocol}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInner
     */
    dexProtocol?: GetAggregatedQuoteResponseDataInnerDexRouterListInnerDexProtocol;
    /**
     *
     * @type {GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInner
     */
    fromToken?: GetAggregatedQuoteResponseDataInnerDexRouterListInnerFromToken;
    /**
     * Sell-token index after global de-duplication (string form).
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInner
     */
    fromTokenIndex?: string;
    /**
     *
     * @type {GetAggregatedQuoteResponseDataInnerDexRouterListInnerToToken}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInner
     */
    toToken?: GetAggregatedQuoteResponseDataInnerDexRouterListInnerToToken;
    /**
     * Buy-token index after global de-duplication (string form).
     * @type {string}
     * @memberof GetAggregatedQuoteResponseDataInnerDexRouterListInner
     */
    toTokenIndex?: string;
}
