/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Token count breakdown by realized PnL percentage range within the time frame.
 * @export
 * @interface GetLeaderboardResponseDataItemsInnerTokenCountByPnlPercent
 */
export interface GetLeaderboardResponseDataItemsInnerTokenCountByPnlPercent {
    /**
     * Number of tokens with realized PnL >500%.
     * @type {string}
     * @memberof GetLeaderboardResponseDataItemsInnerTokenCountByPnlPercent
     */
    above500Percent?: string;
    /**
     * Number of tokens with realized PnL in [0%, 500%].
     * @type {string}
     * @memberof GetLeaderboardResponseDataItemsInnerTokenCountByPnlPercent
     */
    between0And500Percent?: string;
    /**
     * Number of tokens with realized PnL in [-50%, 0%].
     * @type {string}
     * @memberof GetLeaderboardResponseDataItemsInnerTokenCountByPnlPercent
     */
    betweenNeg50And0Percent?: string;
    /**
     * Number of tokens with realized PnL < -50%.
     * @type {string}
     * @memberof GetLeaderboardResponseDataItemsInnerTokenCountByPnlPercent
     */
    belowNeg50Percent?: string;
}
