/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTokenTradingInfoResponseDataInner
 */
export interface GetTokenTradingInfoResponseDataInner {
    /**
     * Chain unique identifier.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    binanceChainId?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    tokenContractAddress?: string;
    /**
     * Latest token price, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    price?: string;
    /**
     * Token price observation time, Unix millisecond timestamp.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    time?: number | bigint;
    /**
     * Token market cap, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    marketCap?: string;
    /**
     * 5-minute price change percentage. \"0.12\" means a 0.12% increase.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    priceChange5M?: string;
    /**
     * 1-hour price change percentage. \"1.05\" means a 1.05% increase.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    priceChange1H?: string;
    /**
     * 4-hour price change percentage. \"2.30\" means a 2.30% increase.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    priceChange4H?: string;
    /**
     * 24-hour price change percentage. \"-0.85\" means a 0.85% decrease.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    priceChange24H?: string;
    /**
     * Trading volume in the last 5 minutes, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    volume5M?: string;
    /**
     * Trading volume in the last 1 hour, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    volume1H?: string;
    /**
     * Trading volume in the last 4 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    volume4H?: string;
    /**
     * Trading volume in the last 24 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    volume24H?: string;
    /**
     * Buy volume in the last 5 minutes, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyVolume5M?: string;
    /**
     * Buy volume in the last 1 hour, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyVolume1H?: string;
    /**
     * Buy volume in the last 4 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyVolume4H?: string;
    /**
     * Buy volume in the last 24 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyVolume24H?: string;
    /**
     * Sell volume in the last 5 minutes, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellVolume5M?: string;
    /**
     * Sell volume in the last 1 hour, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellVolume1H?: string;
    /**
     * Sell volume in the last 4 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellVolume4H?: string;
    /**
     * Sell volume in the last 24 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellVolume24H?: string;
    /**
     * Number of transactions in the last 5 minutes.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    txs5M?: number | bigint;
    /**
     * Number of transactions in the last 1 hour.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    txs1H?: number | bigint;
    /**
     * Number of transactions in the last 4 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    txs4H?: number | bigint;
    /**
     * Number of transactions in the last 24 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    txs24H?: number | bigint;
    /**
     * Number of buy transactions in the last 5 minutes.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyTxs5M?: number | bigint;
    /**
     * Number of buy transactions in the last 1 hour.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyTxs1H?: number | bigint;
    /**
     * Number of buy transactions in the last 4 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyTxs4H?: number | bigint;
    /**
     * Number of buy transactions in the last 24 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    buyTxs24H?: number | bigint;
    /**
     * Number of sell transactions in the last 5 minutes.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellTxs5M?: number | bigint;
    /**
     * Number of sell transactions in the last 1 hour.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellTxs1H?: number | bigint;
    /**
     * Number of sell transactions in the last 4 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellTxs4H?: number | bigint;
    /**
     * Number of sell transactions in the last 24 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    sellTxs24H?: number | bigint;
    /**
     * 24-hour high price, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    maxPrice?: string;
    /**
     * 24-hour low price, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    minPrice?: string;
    /**
     * Current circulating supply of the token.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    circSupply?: string;
    /**
     * Token liquidity, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    liquidity?: string;
    /**
     * Number of holding addresses.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    holders?: number | bigint;
    /**
     * Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnVolume5M?: string;
    /**
     * Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 1 hour, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnVolume1H?: string;
    /**
     * Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 4 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnVolume4H?: string;
    /**
     * Trading volume from Binance MPC wallets via Binance Web3 DEX in the last 24 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnVolume24H?: string;
    /**
     * Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyVolume5M?: string;
    /**
     * Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 1 hour, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyVolume1H?: string;
    /**
     * Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 4 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyVolume4H?: string;
    /**
     * Buy volume from Binance MPC wallets via Binance Web3 DEX in the last 24 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyVolume24H?: string;
    /**
     * Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellVolume5M?: string;
    /**
     * Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 1 hour, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellVolume1H?: string;
    /**
     * Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 4 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellVolume4H?: string;
    /**
     * Sell volume from Binance MPC wallets via Binance Web3 DEX in the last 24 hours, denominated in USD.
     * @type {string}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellVolume24H?: string;
    /**
     * Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnTxs5M?: number | bigint;
    /**
     * Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 1 hour.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnTxs1H?: number | bigint;
    /**
     * Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 4 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnTxs4H?: number | bigint;
    /**
     * Number of transactions from Binance MPC wallets via Binance Web3 DEX in the last 24 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnTxs24H?: number | bigint;
    /**
     * Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyTxs5M?: number | bigint;
    /**
     * Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 1 hour.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyTxs1H?: number | bigint;
    /**
     * Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 4 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyTxs4H?: number | bigint;
    /**
     * Number of buy transactions from Binance MPC wallets via Binance Web3 DEX in the last 24 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnBuyTxs24H?: number | bigint;
    /**
     * Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 5 minutes.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellTxs5M?: number | bigint;
    /**
     * Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 1 hour.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellTxs1H?: number | bigint;
    /**
     * Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 4 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellTxs4H?: number | bigint;
    /**
     * Number of sell transactions from Binance MPC wallets via Binance Web3 DEX in the last 24 hours.
     * @type {number | bigint}
     * @memberof GetTokenTradingInfoResponseDataInner
     */
    bnSellTxs24H?: number | bigint;
}
