/* tslint:disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetBroadcastOrdersResponseDataOrdersInner
 */
export interface GetBroadcastOrdersResponseDataOrdersInner {
    /**
     * Internal order identifier.
     * @type {string}
     * @memberof GetBroadcastOrdersResponseDataOrdersInner
     */
    orderId?: string;
    /**
     * Chain identifier.
     * @type {string}
     * @memberof GetBroadcastOrdersResponseDataOrdersInner
     */
    binanceChainId?: string;
    /**
     * Sender wallet address.
     * @type {string}
     * @memberof GetBroadcastOrdersResponseDataOrdersInner
     */
    address?: string;
    /**
     * On-chain transaction hash. Null while the order is pending.
     * @type {string}
     * @memberof GetBroadcastOrdersResponseDataOrdersInner
     */
    txHash?: string | null;
    /**
     * Transaction status (server-defined string, e.g. \"pending\", \"success\", \"fail\").
     * @type {string}
     * @memberof GetBroadcastOrdersResponseDataOrdersInner
     */
    txStatus?: string;
    /**
     * Failure reason. Populated when the transaction failed; null otherwise.
     * @type {string}
     * @memberof GetBroadcastOrdersResponseDataOrdersInner
     */
    failReason?: string | null;
}
