/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SearchTokenResponseDataInnerTagList } from './search-token-response-data-inner-tag-list';

/**
 *
 * @export
 * @interface GetTokenBasicInfoResponseData
 */
export interface GetTokenBasicInfoResponseData {
    /**
     * Unique identifier of the chain.
     * @type {string}
     * @memberof GetTokenBasicInfoResponseData
     */
    binanceChainId?: string;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetTokenBasicInfoResponseData
     */
    tokenContractAddress?: string;
    /**
     * Token full name.
     * @type {string}
     * @memberof GetTokenBasicInfoResponseData
     */
    tokenName?: string;
    /**
     * Token symbol.
     * @type {string}
     * @memberof GetTokenBasicInfoResponseData
     */
    tokenSymbol?: string;
    /**
     * Token logo link. Null when no logo is available.
     * @type {string}
     * @memberof GetTokenBasicInfoResponseData
     */
    tokenLogoUrl?: string | null;
    /**
     * Token decimals.
     * @type {number}
     * @memberof GetTokenBasicInfoResponseData
     */
    decimals?: number;
    /**
     * Token creator wallet address.
     * @type {string}
     * @memberof GetTokenBasicInfoResponseData
     */
    creatorAddress?: string;
    /**
     * Token creation time, Unix millisecond timestamp.
     * @type {number | bigint}
     * @memberof GetTokenBasicInfoResponseData
     */
    createTime?: number | bigint;
    /**
     *
     * @type {SearchTokenResponseDataInnerTagList}
     * @memberof GetTokenBasicInfoResponseData
     */
    tagList?: SearchTokenResponseDataInnerTagList;
}
