/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner } from './get-top-liquidity-pools-response-data-inner-liquidity-amount-inner';

/**
 *
 * @export
 * @interface GetTopLiquidityPoolsResponseDataInner
 */
export interface GetTopLiquidityPoolsResponseDataInner {
    /**
     * Pool name, e.g. \"PEPE/WETH\".
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInner
     */
    pool?: string;
    /**
     * DEX protocol name. Null when unknown.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInner
     */
    protocolName?: string | null;
    /**
     * Protocol logo link. Null when no logo.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInner
     */
    protocolLogoUrl?: string | null;
    /**
     * Pool liquidity, denominated in USD.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInner
     */
    liquidityUsd?: string;
    /**
     * Pool contract address.
     * @type {string}
     * @memberof GetTopLiquidityPoolsResponseDataInner
     */
    poolAddress?: string;
    /**
     * Detailed information for each token in the pool.
     * @type {Array<GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner>}
     * @memberof GetTopLiquidityPoolsResponseDataInner
     */
    liquidityAmount?: Array<GetTopLiquidityPoolsResponseDataInnerLiquidityAmountInner>;
}
