/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetTransactionStatusResponseData } from './get-transaction-status-response-data';

/**
 *
 * @export
 * @interface GetTransactionStatusResponse
 */
export interface GetTransactionStatusResponse {
    /**
     *
     * @type {number}
     * @memberof GetTransactionStatusResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof GetTransactionStatusResponse
     */
    msg?: string;
    /**
     *
     * @type {GetTransactionStatusResponseData}
     * @memberof GetTransactionStatusResponse
     */
    data?: GetTransactionStatusResponseData | null;
    /**
     *
     * @type {number | bigint}
     * @memberof GetTransactionStatusResponse
     */
    timestamp?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetTransactionStatusResponse
     */
    success?: boolean;
}
