/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetHotTokenListResponseDataItemsInner
 */
export interface GetHotTokenListResponseDataItemsInner {
    /**
     * Unique identifier of the chain.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    binanceChainId?: string;
    /**
     * Token symbol.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    tokenSymbol?: string;
    /**
     * Token logo URL.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    tokenLogoUrl?: string | null;
    /**
     * Token contract address.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    tokenContractAddress?: string;
    /**
     * Market cap, denominated in USD.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    marketCap?: string;
    /**
     * Trading volume within the specified time, denominated in USD.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    volume?: string;
    /**
     * Price change percentage within the specified time. \"-5.23\" means a 5.23% decrease.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    change?: string;
    /**
     * Number of unique trading addresses.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    uniqueTraders?: string;
    /**
     * Buy transaction count.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    buyTxs?: string;
    /**
     * Sell transaction count.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    sellTxs?: string;
    /**
     * Total transaction count.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    txs?: string;
    /**
     * Liquidity, denominated in USD.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    liquidity?: string;
    /**
     * Token price, denominated in USD.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    price?: string;
    /**
     * Holder count.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    holders?: string;
    /**
     * Net inflow, denominated in USD. Positive means net inflow, negative means net outflow.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    inflowUsd?: string;
    /**
     * Developer holding percentage. \"5.23\" means 5.23%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    devHoldingPercent?: string;
    /**
     * Number of Binance MPC wallets holding this token.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    bnHolderCount?: string;
    /**
     * Top 10 addresses holding percentage. \"35.2\" means 35.2%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    top10HoldingPercent?: string;
    /**
     * Sniper holding percentage. \"8.3\" means 8.3%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    sniperHoldingPercent?: string;
    /**
     * Professional holder percentage. \"12.1\" means 12.1%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    proHoldingPercent?: string;
    /**
     * Fresh wallet holding percentage. \"3.5\" means 3.5%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    freshWalletHoldingPercent?: string;
    /**
     * Smart money holding percentage. \"1.52\" means 1.52%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    smartMoneyHoldingPercent?: string;
    /**
     * KOL holding percentage. \"6.5\" means 6.5%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    kolHoldingPercent?: string;
    /**
     * Insider holding percentage. \"2.8\" means 2.8%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    insiderHoldingPercent?: string;
    /**
     * Bundler holding percentage. \"6.2\" means 6.2%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    bundlerHoldingPercent?: string;
    /**
     * Developer-created token count.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    devCreatedTokenCount?: string;
    /**
     * Developer-migrated token count.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    devMigratedTokenCount?: string;
    /**
     * Developer migrated token percentage. \"33.3\" means 33.3%.
     * @type {string}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    devMigratedTokenPercent?: string;
    /**
     * Token tags.
     * @type {Array<string>}
     * @memberof GetHotTokenListResponseDataItemsInner
     */
    tokenTags?: Array<string>;
}
