/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetBroadcastOrdersResponseDataOrdersInner } from './get-broadcast-orders-response-data-orders-inner';

/**
 *
 * @export
 * @interface GetBroadcastOrdersResponseData
 */
export interface GetBroadcastOrdersResponseData {
    /**
     * Cursor for the next page. Empty string when no more pages.
     * @type {string}
     * @memberof GetBroadcastOrdersResponseData
     */
    cursor?: string;
    /**
     * Order list.
     * @type {Array<GetBroadcastOrdersResponseDataOrdersInner>}
     * @memberof GetBroadcastOrdersResponseData
     */
    orders?: Array<GetBroadcastOrdersResponseDataOrdersInner>;
}
