/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra
 */
export interface GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra {
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra
     */
    version?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra
     */
    assetTransferMethod?: string;
    /**
     *
     * @type {string}
     * @memberof GetB402SupportedConfigurationsV1Response1DataKindsInnerExtra
     */
    facilitatorAddress?: string;
}
