/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { InvestmentPageResultListInner } from './investment-page-result-list-inner';

/**
 * Paginated investment list result.
 * @export
 * @interface ListDeFiInvestmentsResponseData
 */
export interface ListDeFiInvestmentsResponseData {
    /**
     * Current page number (1-based).
     * @type {number}
     * @memberof ListDeFiInvestmentsResponseData
     */
    page?: number;
    /**
     * Page size.
     * @type {number}
     * @memberof ListDeFiInvestmentsResponseData
     */
    size?: number;
    /**
     * Total number of records.
     * @type {number | bigint}
     * @memberof ListDeFiInvestmentsResponseData
     */
    total?: number | bigint;
    /**
     * Investments for the current page.
     * @type {Array<InvestmentPageResultListInner>}
     * @memberof ListDeFiInvestmentsResponseData
     */
    list?: Array<InvestmentPageResultListInner>;
}
