/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Result of `/transaction/lp-add/calculate`. Returns the paired token amounts derived from the single input token. This endpoint is pure computation — it does not touch the chain and does not deduct any fee.
 * @export
 * @interface LpAddCalculateResponse
 */
export interface LpAddCalculateResponse {
    /**
     * Echo of the input token amount (human-readable).
     * @type {string}
     * @memberof LpAddCalculateResponse
     */
    inputTokenAmount?: string;
    /**
     * The paired token contract address derived from the investment.
     * @type {string}
     * @memberof LpAddCalculateResponse
     */
    pairedTokenAddress?: string;
    /**
     * Calculated paired token amount (human-readable).
     * @type {string}
     * @memberof LpAddCalculateResponse
     */
    pairedTokenAmount?: string;
}
