/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Token balance information within a position.
 * @export
 * @interface PositionRespTokenListSupplyInner
 */
export interface PositionRespTokenListSupplyInner {
    /**
     * Token contract address. The native-asset sentinel `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` (40 `e`s) for native coins.
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenAddress?: string;
    /**
     * Token name.
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenName?: string;
    /**
     * Token symbol.
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenSymbol?: string;
    /**
     * Human-readable token amount (NOT the smallest unit).
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenAmount?: string;
    /**
     * Current token price in USD.
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenPrice?: string;
    /**
     * Token value in USD (amount × price).
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenValue?: string;
    /**
     * Token decimals (string).
     * @type {string}
     * @memberof PositionRespTokenListSupplyInner
     */
    tokenDecimals?: string;
}
