/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PositionListRespAddressListInner } from './position-list-resp-address-list-inner';

/**
 * Aggregated DeFi positions response.
 * @export
 * @interface PositionListResp
 */
export interface PositionListResp {
    /**
     * Total value of all DeFi positions of all queried addresses (USD). Same raw precision as addressTotalValue.
     * @type {string}
     * @memberof PositionListResp
     */
    totalValue?: string;
    /**
     * Address-level position summaries.
     * @type {Array<PositionListRespAddressListInner>}
     * @memberof PositionListResp
     */
    addressList?: Array<PositionListRespAddressListInner>;
}
