/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PositionRespTokenListSupplyInner } from './position-resp-token-list-supply-inner';

/**
 * Token breakdown grouped by role. Keys: `supply` (supplied assets), `borrow` (borrowed assets, lending positions), `reward` (claimable rewards), `farming_reward` (MasterChef farming incentives). A key is absent when the position has no tokens in that role.
 * @export
 * @interface PositionRespTokenList
 */
export interface PositionRespTokenList {
    /**
     *
     * @type {Array<PositionRespTokenListSupplyInner>}
     * @memberof PositionRespTokenList
     */
    supply?: Array<PositionRespTokenListSupplyInner>;
    /**
     *
     * @type {Array<PositionRespTokenListSupplyInner>}
     * @memberof PositionRespTokenList
     */
    borrow?: Array<PositionRespTokenListSupplyInner>;
    /**
     *
     * @type {Array<PositionRespTokenListSupplyInner>}
     * @memberof PositionRespTokenList
     */
    reward?: Array<PositionRespTokenListSupplyInner>;
    /**
     *
     * @type {Array<PositionRespTokenListSupplyInner>}
     * @memberof PositionRespTokenList
     */
    farming_reward?: Array<PositionRespTokenListSupplyInner>;
}
