/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Collection metadata. Null when the collection has no metadata. Fields are null when not applicable.
 * @export
 * @interface PositionCollectionRespPositionCollectionDetail
 */
export interface PositionCollectionRespPositionCollectionDetail {
    /**
     * Index of this collection within the pool. For single-asset collections this is the ABI-encoded (left-padded) token address; other pools use their own index format.
     * @type {string}
     * @memberof PositionCollectionRespPositionCollectionDetail
     */
    collectionIndex?: string | null;
    /**
     * Human-readable collection name.
     * @type {string}
     * @memberof PositionCollectionRespPositionCollectionDetail
     */
    collectionDisplayName?: string | null;
    /**
     * Health factor for lending positions. Null for non-lending positions.
     * @type {string}
     * @memberof PositionCollectionRespPositionCollectionDetail
     */
    healthFactor?: string | null;
}
