/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SearchRwaTokenResponseDataInner } from './search-rwa-token-response-data-inner';

/**
 *
 * @export
 * @interface SearchRwaTokenResponse
 */
export interface SearchRwaTokenResponse {
    /**
     * Business status code. 0 indicates success.
     * @type {number}
     * @memberof SearchRwaTokenResponse
     */
    code?: number;
    /**
     * Status message.
     * @type {string}
     * @memberof SearchRwaTokenResponse
     */
    msg?: string;
    /**
     * List of matched tickers and their tokenized assets.
     * @type {Array<SearchRwaTokenResponseDataInner>}
     * @memberof SearchRwaTokenResponse
     */
    data?: Array<SearchRwaTokenResponseDataInner>;
    /**
     * Server response time, Unix millisecond timestamp.
     * @type {number | bigint}
     * @memberof SearchRwaTokenResponse
     */
    timestamp?: number | bigint;
    /**
     * Whether the request was successful.
     * @type {boolean}
     * @memberof SearchRwaTokenResponse
     */
    success?: boolean;
}
