/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SearchTokenResponseDataInnerTagList } from './search-token-response-data-inner-tag-list';

/**
 *
 * @export
 * @interface SearchTokenResponseDataInner
 */
export interface SearchTokenResponseDataInner {
    /**
     * Chain identifier.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    binanceChainId?: string;
    /**
     * Token full name.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    tokenName?: string;
    /**
     * Token symbol.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    tokenSymbol?: string;
    /**
     * Token logo link. Null when no logo is available.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    tokenLogoUrl?: string | null;
    /**
     * Token contract address.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    tokenContractAddress?: string;
    /**
     * Token decimals.
     * @type {number}
     * @memberof SearchTokenResponseDataInner
     */
    decimals?: number;
    /**
     * Block explorer link for the token.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    explorerUrl?: string;
    /**
     * 24-hour price change. \"-5.23\" means a 5.23% decrease. Null when no data.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    change?: string | null;
    /**
     * Number of holder addresses.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    holders?: string;
    /**
     * Token liquidity, denominated in USD.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    liquidity?: string;
    /**
     * Token market cap, denominated in USD.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    marketCap?: string;
    /**
     * Latest token price, denominated in USD.
     * @type {string}
     * @memberof SearchTokenResponseDataInner
     */
    price?: string;
    /**
     *
     * @type {SearchTokenResponseDataInnerTagList}
     * @memberof SearchTokenResponseDataInner
     */
    tagList?: SearchTokenResponseDataInnerTagList;
}
