/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SettleB402PaymentV1ResponseData } from './settle-b402-payment-v1-response-data';

/**
 *
 * @export
 * @interface SettleB402PaymentV1Response
 */
export interface SettleB402PaymentV1Response {
    /**
     *
     * @type {string}
     * @memberof SettleB402PaymentV1Response
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof SettleB402PaymentV1Response
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof SettleB402PaymentV1Response
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof SettleB402PaymentV1Response
     */
    errorData?: string | null;
    /**
     *
     * @type {SettleB402PaymentV1ResponseData}
     * @memberof SettleB402PaymentV1Response
     */
    data?: SettleB402PaymentV1ResponseData | null;
    /**
     *
     * @type {object}
     * @memberof SettleB402PaymentV1Response
     */
    subData?: object | null;
    /**
     *
     * @type {object}
     * @memberof SettleB402PaymentV1Response
     */
    params?: object | null;
}
