/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SimulateTransactionsResponseDataAllowanceChangesInner
 */
export interface SimulateTransactionsResponseDataAllowanceChangesInner {
    /**
     * ERC-20 token contract address.
     * @type {string}
     * @memberof SimulateTransactionsResponseDataAllowanceChangesInner
     */
    tokenAddress?: string;
    /**
     * Token owner address.
     * @type {string}
     * @memberof SimulateTransactionsResponseDataAllowanceChangesInner
     */
    owner?: string;
    /**
     * Spender address whose allowance is changing.
     * @type {string}
     * @memberof SimulateTransactionsResponseDataAllowanceChangesInner
     */
    spender?: string;
    /**
     * Allowance before the transaction (smallest unit, integer string).
     * @type {string}
     * @memberof SimulateTransactionsResponseDataAllowanceChangesInner
     */
    preAmount?: string;
    /**
     * Allowance after the transaction (smallest unit, integer string).
     * @type {string}
     * @memberof SimulateTransactionsResponseDataAllowanceChangesInner
     */
    postAmount?: string;
}
