/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV1RequestBodyPaymentPayload } from './verify-b402-payment-v1-request-body-payment-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV1RequestBodyPaymentRequirements } from './verify-b402-payment-v1-request-body-payment-requirements';

/**
 *
 * @export
 * @interface VerifyB402PaymentV1RequestBody
 */
export interface VerifyB402PaymentV1RequestBody {
    /**
     *
     * @type {number}
     * @memberof VerifyB402PaymentV1RequestBody
     */
    x402Version: VerifyB402PaymentV1RequestBodyX402VersionEnum;
    /**
     *
     * @type {VerifyB402PaymentV1RequestBodyPaymentPayload}
     * @memberof VerifyB402PaymentV1RequestBody
     */
    paymentPayload: VerifyB402PaymentV1RequestBodyPaymentPayload;
    /**
     *
     * @type {VerifyB402PaymentV1RequestBodyPaymentRequirements}
     * @memberof VerifyB402PaymentV1RequestBody
     */
    paymentRequirements: VerifyB402PaymentV1RequestBodyPaymentRequirements;
}

export const VerifyB402PaymentV1RequestBodyX402VersionEnum = {
    X402_VERSION_1: 1,
} as const;

export type VerifyB402PaymentV1RequestBodyX402VersionEnum =
    (typeof VerifyB402PaymentV1RequestBodyX402VersionEnum)[keyof typeof VerifyB402PaymentV1RequestBodyX402VersionEnum];
