/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2RequestBodyPaymentPayloadAccepted } from './verify-b402-payment-v2-request-body-payment-payload-accepted';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions } from './verify-b402-payment-v2-request-body-payment-payload-extensions';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2RequestBodyPaymentPayloadPayload } from './verify-b402-payment-v2-request-body-payment-payload-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2RequestBodyPaymentPayloadResource } from './verify-b402-payment-v2-request-body-payment-payload-resource';

/**
 *
 * @export
 * @interface VerifyB402PaymentV2RequestBodyPaymentPayload
 */
export interface VerifyB402PaymentV2RequestBodyPaymentPayload {
    /**
     *
     * @type {number}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayload
     */
    x402Version: VerifyB402PaymentV2RequestBodyPaymentPayloadX402VersionEnum;
    /**
     *
     * @type {VerifyB402PaymentV2RequestBodyPaymentPayloadResource}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayload
     */
    resource: VerifyB402PaymentV2RequestBodyPaymentPayloadResource;
    /**
     *
     * @type {VerifyB402PaymentV2RequestBodyPaymentPayloadAccepted}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayload
     */
    accepted: VerifyB402PaymentV2RequestBodyPaymentPayloadAccepted;
    /**
     *
     * @type {VerifyB402PaymentV2RequestBodyPaymentPayloadPayload}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayload
     */
    payload: VerifyB402PaymentV2RequestBodyPaymentPayloadPayload;
    /**
     *
     * @type {VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayload
     */
    extensions?: VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions;
}

export const VerifyB402PaymentV2RequestBodyPaymentPayloadX402VersionEnum = {
    X402_VERSION_2: 2,
} as const;

export type VerifyB402PaymentV2RequestBodyPaymentPayloadX402VersionEnum =
    (typeof VerifyB402PaymentV2RequestBodyPaymentPayloadX402VersionEnum)[keyof typeof VerifyB402PaymentV2RequestBodyPaymentPayloadX402VersionEnum];
