/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { B402VerifyResponseV2Data } from './b402-verify-response-v2-data';

/**
 *
 * @export
 * @interface VerifyB402PaymentV1Response1
 */
export interface VerifyB402PaymentV1Response1 {
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV1Response1
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV1Response1
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV1Response1
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV1Response1
     */
    errorData?: string | null;
    /**
     *
     * @type {B402VerifyResponseV2Data}
     * @memberof VerifyB402PaymentV1Response1
     */
    data?: B402VerifyResponseV2Data;
    /**
     *
     * @type {object}
     * @memberof VerifyB402PaymentV1Response1
     */
    subData?: object | null;
    /**
     *
     * @type {object}
     * @memberof VerifyB402PaymentV1Response1
     */
    params?: object | null;
}
