/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2AuthorizationPermitted } from './verify-b402-payment-v2-request-body-payment-payload-payload-permit2-authorization-permitted';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2AuthorizationWitness } from './verify-b402-payment-v2-request-body-payment-payload-payload-permit2-authorization-witness';

/**
 *
 * @export
 * @interface VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
 */
export interface VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization {
    /**
     *
     * @type {VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2AuthorizationPermitted}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
     */
    permitted: VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2AuthorizationPermitted;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
     */
    from: string;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
     */
    spender: string;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
     */
    nonce: string;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
     */
    deadline: string;
    /**
     *
     * @type {VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2AuthorizationWitness}
     * @memberof VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2Authorization
     */
    witness: VerifyB402PaymentV2RequestBodyPaymentPayloadPayloadPermit2AuthorizationWitness;
}
