/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VerifyB402PaymentV2ResponseData
 */
export interface VerifyB402PaymentV2ResponseData {
    /**
     *
     * @type {boolean}
     * @memberof VerifyB402PaymentV2ResponseData
     */
    isValid: boolean;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2ResponseData
     */
    payer?: string | null;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2ResponseData
     */
    invalidReason?: string | null;
    /**
     *
     * @type {string}
     * @memberof VerifyB402PaymentV2ResponseData
     */
    invalidMessage?: string | null;
}
