/* tslint:disable */
/* eslint-disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2Response1 } from './verify-b402-payment-v2-response1';
// May contain unused imports in some cases
// @ts-ignore
import type { VerifyB402PaymentV2Response2 } from './verify-b402-payment-v2-response2';

/**
 * @type VerifyB402PaymentV2Response
 */
export type VerifyB402PaymentV2Response =
    | VerifyB402PaymentV2Response1
    | VerifyB402PaymentV2Response2;
