/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {
    ConfigurationRestAPI,
    TimeUnit,
    RestApiResponse,
    assertParamExists,
    sendRequest,
    type RequestArgs,
} from '@binance/common';
import type {
    GetRwaTokenIssuancePlatformsResponse,
    GetRwaTokenListResponse,
    GetRwaTokenPriceResponse,
    GetRwaUnderlyingInfoResponse,
    GetRwaUnderlyingMarketDataResponse,
    SearchRwaTokenResponse,
} from '../types';

/**
 * RWADataApi - axios parameter creator
 */
const RWADataApiAxiosParamCreator = function (configuration: ConfigurationRestAPI) {
    return {
        /**
         * Return the list of supported RWA token issuance platforms and their basic info.
         *
         * @summary Get RWA Token Issuance Platforms
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds. Default 5000, max 60000.
         * @param {string} [nonce] Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
         * @param {GetRwaTokenIssuancePlatformsPlatformIdEnum} [platformId] Platform identifier (ondo=Ondo Finance, bstock=bStocks). Optional. If not specified, returns all platforms; when specified, returns only that platform.
         *
         * @throws {RequiredError}
         */
        getRwaTokenIssuancePlatforms: async (
            recvWindow?: number | bigint,
            nonce?: string,
            platformId?: GetRwaTokenIssuancePlatformsPlatformIdEnum
        ): Promise<RequestArgs> => {
            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (platformId !== undefined && platformId !== null) {
                localVarQueryParameter['platformId'] = platformId;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/market/rwa/platforms',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Get the list of RWA tokens with underlying asset info. Supports filtering by platform and sector tab.
         *
         * @summary Get RWA Token List
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds. Default 5000, max 60000.
         * @param {string} [nonce] Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
         * @param {string} [binanceChainId] Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana). Optional. If not specified, returns data from all chains.
         * @param {GetRwaTokenListPlatformIdEnum} [platformId] Platform filter (ondo=Ondo Finance, bstock=bStocks). Optional. If not specified, returns all platforms.
         * @param {number} [tabId] Sector tab filter. Optional. If not specified, returns all sectors. Enum: 1=Serenity Call, 2=SpaceX (SpaceX-related and commercial spaceflight concept stocks), 3=Upcoming Earnings, 4=AI Chips, 5=Storage, 6=Energy, 7=Precious Metals, 8=China ADR (Chinese companies listed in the US), 9=Magnificent 7 (the seven largest US tech giants: Apple, Microsoft, Alphabet, Amazon, Nvidia, Meta, Tesla), 10=Crypto, 11=ETF, 12=Tech Leaders, 13=Buffett Portfolio.
         *
         * @throws {RequiredError}
         */
        getRwaTokenList: async (
            recvWindow?: number | bigint,
            nonce?: string,
            binanceChainId?: string,
            platformId?: GetRwaTokenListPlatformIdEnum,
            tabId?: number
        ): Promise<RequestArgs> => {
            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarQueryParameter['binanceChainId'] = binanceChainId;
            }
            if (platformId !== undefined && platformId !== null) {
                localVarQueryParameter['platformId'] = platformId;
            }
            if (tabId !== undefined && tabId !== null) {
                localVarQueryParameter['tabId'] = tabId;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/market/rwa/tokens',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Batch query RWA token prices, including on-chain price and underlying reference price.
         *
         * @summary Get RWA Token Price
         * @param {string} binanceChainId Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
         * @param {string} tokenContractAddresses Comma-separated token contract addresses. Maximum 100 per request.
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds. Default 5000, max 60000.
         * @param {string} [nonce] Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
         *
         * @throws {RequiredError}
         */
        getRwaTokenPrice: async (
            binanceChainId: string,
            tokenContractAddresses: string,
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('getRwaTokenPrice', 'binanceChainId', binanceChainId);
            // verify required parameter 'tokenContractAddresses' is not null or undefined
            assertParamExists('getRwaTokenPrice', 'tokenContractAddresses', tokenContractAddresses);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarQueryParameter['binanceChainId'] = binanceChainId;
            }
            if (tokenContractAddresses !== undefined && tokenContractAddresses !== null) {
                localVarQueryParameter['tokenContractAddresses'] = tokenContractAddresses;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/market/rwa/price',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Get the underlying company information for an RWA token.
         *
         * @summary Get RWA Underlying Info
         * @param {string} binanceChainId Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
         * @param {string} tokenContractAddress Token contract address.
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds. Default 5000, max 60000.
         * @param {string} [nonce] Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
         *
         * @throws {RequiredError}
         */
        getRwaUnderlyingInfo: async (
            binanceChainId: string,
            tokenContractAddress: string,
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('getRwaUnderlyingInfo', 'binanceChainId', binanceChainId);
            // verify required parameter 'tokenContractAddress' is not null or undefined
            assertParamExists('getRwaUnderlyingInfo', 'tokenContractAddress', tokenContractAddress);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarQueryParameter['binanceChainId'] = binanceChainId;
            }
            if (tokenContractAddress !== undefined && tokenContractAddress !== null) {
                localVarQueryParameter['tokenContractAddress'] = tokenContractAddress;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/market/rwa/underlying-profile',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Get market data for the underlying asset of an RWA token.
         *
         * @summary Get RWA Underlying Market Data
         * @param {string} binanceChainId Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
         * @param {string} tokenContractAddress Token contract address.
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds. Default 5000, max 60000.
         * @param {string} [nonce] Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
         *
         * @throws {RequiredError}
         */
        getRwaUnderlyingMarketData: async (
            binanceChainId: string,
            tokenContractAddress: string,
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('getRwaUnderlyingMarketData', 'binanceChainId', binanceChainId);
            // verify required parameter 'tokenContractAddress' is not null or undefined
            assertParamExists(
                'getRwaUnderlyingMarketData',
                'tokenContractAddress',
                tokenContractAddress
            );

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarQueryParameter['binanceChainId'] = binanceChainId;
            }
            if (tokenContractAddress !== undefined && tokenContractAddress !== null) {
                localVarQueryParameter['tokenContractAddress'] = tokenContractAddress;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/market/rwa/underlying-market',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Search RWA tokens by keyword or contract address.
         *
         * @summary Search RWA Token
         * @param {string} keyword Search keyword (ticker, company name, or contract address). Case-insensitive.
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds. Default 5000, max 60000.
         * @param {string} [nonce] Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
         * @param {SearchRwaTokenPlatformIdEnum} [platformId] Platform filter (ondo=Ondo Finance, bstock=bStocks). Optional. If not specified, returns results from all platforms.
         *
         * @throws {RequiredError}
         */
        searchRwaToken: async (
            keyword: string,
            recvWindow?: number | bigint,
            nonce?: string,
            platformId?: SearchRwaTokenPlatformIdEnum
        ): Promise<RequestArgs> => {
            // verify required parameter 'keyword' is not null or undefined
            assertParamExists('searchRwaToken', 'keyword', keyword);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (keyword !== undefined && keyword !== null) {
                localVarQueryParameter['keyword'] = keyword;
            }
            if (platformId !== undefined && platformId !== null) {
                localVarQueryParameter['platformId'] = platformId;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/market/rwa/search',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
    };
};

/**
 * RWADataApi - interface
 * @interface RWADataApi
 */
export interface RWADataApiInterface {
    /**
     * Return the list of supported RWA token issuance platforms and their basic info.
     *
     * @summary Get RWA Token Issuance Platforms
     * @param {GetRwaTokenIssuancePlatformsRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApiInterface
     */
    getRwaTokenIssuancePlatforms(
        requestParameters?: GetRwaTokenIssuancePlatformsRequest
    ): Promise<RestApiResponse<GetRwaTokenIssuancePlatformsResponse>>;
    /**
     * Get the list of RWA tokens with underlying asset info. Supports filtering by platform and sector tab.
     *
     * @summary Get RWA Token List
     * @param {GetRwaTokenListRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApiInterface
     */
    getRwaTokenList(
        requestParameters?: GetRwaTokenListRequest
    ): Promise<RestApiResponse<GetRwaTokenListResponse>>;
    /**
     * Batch query RWA token prices, including on-chain price and underlying reference price.
     *
     * @summary Get RWA Token Price
     * @param {GetRwaTokenPriceRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApiInterface
     */
    getRwaTokenPrice(
        requestParameters: GetRwaTokenPriceRequest
    ): Promise<RestApiResponse<GetRwaTokenPriceResponse>>;
    /**
     * Get the underlying company information for an RWA token.
     *
     * @summary Get RWA Underlying Info
     * @param {GetRwaUnderlyingInfoRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApiInterface
     */
    getRwaUnderlyingInfo(
        requestParameters: GetRwaUnderlyingInfoRequest
    ): Promise<RestApiResponse<GetRwaUnderlyingInfoResponse>>;
    /**
     * Get market data for the underlying asset of an RWA token.
     *
     * @summary Get RWA Underlying Market Data
     * @param {GetRwaUnderlyingMarketDataRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApiInterface
     */
    getRwaUnderlyingMarketData(
        requestParameters: GetRwaUnderlyingMarketDataRequest
    ): Promise<RestApiResponse<GetRwaUnderlyingMarketDataResponse>>;
    /**
     * Search RWA tokens by keyword or contract address.
     *
     * @summary Search RWA Token
     * @param {SearchRwaTokenRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApiInterface
     */
    searchRwaToken(
        requestParameters: SearchRwaTokenRequest
    ): Promise<RestApiResponse<SearchRwaTokenResponse>>;
}

/**
 * Request parameters for getRwaTokenIssuancePlatforms operation in RWADataApi.
 * @interface GetRwaTokenIssuancePlatformsRequest
 */
export interface GetRwaTokenIssuancePlatformsRequest {
    /**
     * Allowed time deviation in milliseconds. Default 5000, max 60000.
     * @type {number | bigint}
     * @memberof RWADataApiGetRwaTokenIssuancePlatforms
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
     * @type {string}
     * @memberof RWADataApiGetRwaTokenIssuancePlatforms
     */
    readonly nonce?: string;

    /**
     * Platform identifier (ondo=Ondo Finance, bstock=bStocks). Optional. If not specified, returns all platforms; when specified, returns only that platform.
     * @type {'ondo' | 'bstock'}
     * @memberof RWADataApiGetRwaTokenIssuancePlatforms
     */
    readonly platformId?: GetRwaTokenIssuancePlatformsPlatformIdEnum;
}

/**
 * Request parameters for getRwaTokenList operation in RWADataApi.
 * @interface GetRwaTokenListRequest
 */
export interface GetRwaTokenListRequest {
    /**
     * Allowed time deviation in milliseconds. Default 5000, max 60000.
     * @type {number | bigint}
     * @memberof RWADataApiGetRwaTokenList
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
     * @type {string}
     * @memberof RWADataApiGetRwaTokenList
     */
    readonly nonce?: string;

    /**
     * Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana). Optional. If not specified, returns data from all chains.
     * @type {string}
     * @memberof RWADataApiGetRwaTokenList
     */
    readonly binanceChainId?: string;

    /**
     * Platform filter (ondo=Ondo Finance, bstock=bStocks). Optional. If not specified, returns all platforms.
     * @type {'ondo' | 'bstock'}
     * @memberof RWADataApiGetRwaTokenList
     */
    readonly platformId?: GetRwaTokenListPlatformIdEnum;

    /**
     * Sector tab filter. Optional. If not specified, returns all sectors. Enum: 1=Serenity Call, 2=SpaceX (SpaceX-related and commercial spaceflight concept stocks), 3=Upcoming Earnings, 4=AI Chips, 5=Storage, 6=Energy, 7=Precious Metals, 8=China ADR (Chinese companies listed in the US), 9=Magnificent 7 (the seven largest US tech giants: Apple, Microsoft, Alphabet, Amazon, Nvidia, Meta, Tesla), 10=Crypto, 11=ETF, 12=Tech Leaders, 13=Buffett Portfolio.
     * @type {number}
     * @memberof RWADataApiGetRwaTokenList
     */
    readonly tabId?: number;
}

/**
 * Request parameters for getRwaTokenPrice operation in RWADataApi.
 * @interface GetRwaTokenPriceRequest
 */
export interface GetRwaTokenPriceRequest {
    /**
     * Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
     * @type {string}
     * @memberof RWADataApiGetRwaTokenPrice
     */
    readonly binanceChainId: string;

    /**
     * Comma-separated token contract addresses. Maximum 100 per request.
     * @type {string}
     * @memberof RWADataApiGetRwaTokenPrice
     */
    readonly tokenContractAddresses: string;

    /**
     * Allowed time deviation in milliseconds. Default 5000, max 60000.
     * @type {number | bigint}
     * @memberof RWADataApiGetRwaTokenPrice
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
     * @type {string}
     * @memberof RWADataApiGetRwaTokenPrice
     */
    readonly nonce?: string;
}

/**
 * Request parameters for getRwaUnderlyingInfo operation in RWADataApi.
 * @interface GetRwaUnderlyingInfoRequest
 */
export interface GetRwaUnderlyingInfoRequest {
    /**
     * Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
     * @type {string}
     * @memberof RWADataApiGetRwaUnderlyingInfo
     */
    readonly binanceChainId: string;

    /**
     * Token contract address.
     * @type {string}
     * @memberof RWADataApiGetRwaUnderlyingInfo
     */
    readonly tokenContractAddress: string;

    /**
     * Allowed time deviation in milliseconds. Default 5000, max 60000.
     * @type {number | bigint}
     * @memberof RWADataApiGetRwaUnderlyingInfo
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
     * @type {string}
     * @memberof RWADataApiGetRwaUnderlyingInfo
     */
    readonly nonce?: string;
}

/**
 * Request parameters for getRwaUnderlyingMarketData operation in RWADataApi.
 * @interface GetRwaUnderlyingMarketDataRequest
 */
export interface GetRwaUnderlyingMarketDataRequest {
    /**
     * Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
     * @type {string}
     * @memberof RWADataApiGetRwaUnderlyingMarketData
     */
    readonly binanceChainId: string;

    /**
     * Token contract address.
     * @type {string}
     * @memberof RWADataApiGetRwaUnderlyingMarketData
     */
    readonly tokenContractAddress: string;

    /**
     * Allowed time deviation in milliseconds. Default 5000, max 60000.
     * @type {number | bigint}
     * @memberof RWADataApiGetRwaUnderlyingMarketData
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
     * @type {string}
     * @memberof RWADataApiGetRwaUnderlyingMarketData
     */
    readonly nonce?: string;
}

/**
 * Request parameters for searchRwaToken operation in RWADataApi.
 * @interface SearchRwaTokenRequest
 */
export interface SearchRwaTokenRequest {
    /**
     * Search keyword (ticker, company name, or contract address). Case-insensitive.
     * @type {string}
     * @memberof RWADataApiSearchRwaToken
     */
    readonly keyword: string;

    /**
     * Allowed time deviation in milliseconds. Default 5000, max 60000.
     * @type {number | bigint}
     * @memberof RWADataApiSearchRwaToken
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier to prevent replay attacks. Falls back to X-OC-SIGN when omitted.
     * @type {string}
     * @memberof RWADataApiSearchRwaToken
     */
    readonly nonce?: string;

    /**
     * Platform filter (ondo=Ondo Finance, bstock=bStocks). Optional. If not specified, returns results from all platforms.
     * @type {'ondo' | 'bstock'}
     * @memberof RWADataApiSearchRwaToken
     */
    readonly platformId?: SearchRwaTokenPlatformIdEnum;
}

/**
 * RWADataApi - object-oriented interface
 * @class RWADataApi
 */
export class RWADataApi implements RWADataApiInterface {
    private readonly configuration: ConfigurationRestAPI;
    private localVarAxiosParamCreator;

    constructor(configuration: ConfigurationRestAPI) {
        this.configuration = configuration;
        this.localVarAxiosParamCreator = RWADataApiAxiosParamCreator(configuration);
    }

    /**
     * Return the list of supported RWA token issuance platforms and their basic info.
     *
     * @summary Get RWA Token Issuance Platforms
     * @param {GetRwaTokenIssuancePlatformsRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetRwaTokenIssuancePlatformsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-token-issuance-platforms Binance API Documentation}
     */
    public async getRwaTokenIssuancePlatforms(
        requestParameters: GetRwaTokenIssuancePlatformsRequest = {}
    ): Promise<RestApiResponse<GetRwaTokenIssuancePlatformsResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getRwaTokenIssuancePlatforms(
            requestParameters?.recvWindow,
            requestParameters?.nonce,
            requestParameters?.platformId
        );
        return sendRequest<GetRwaTokenIssuancePlatformsResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Get the list of RWA tokens with underlying asset info. Supports filtering by platform and sector tab.
     *
     * @summary Get RWA Token List
     * @param {GetRwaTokenListRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetRwaTokenListResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-token-list Binance API Documentation}
     */
    public async getRwaTokenList(
        requestParameters: GetRwaTokenListRequest = {}
    ): Promise<RestApiResponse<GetRwaTokenListResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getRwaTokenList(
            requestParameters?.recvWindow,
            requestParameters?.nonce,
            requestParameters?.binanceChainId,
            requestParameters?.platformId,
            requestParameters?.tabId
        );
        return sendRequest<GetRwaTokenListResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Batch query RWA token prices, including on-chain price and underlying reference price.
     *
     * @summary Get RWA Token Price
     * @param {GetRwaTokenPriceRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetRwaTokenPriceResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-token-price Binance API Documentation}
     */
    public async getRwaTokenPrice(
        requestParameters: GetRwaTokenPriceRequest
    ): Promise<RestApiResponse<GetRwaTokenPriceResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getRwaTokenPrice(
            requestParameters?.binanceChainId,
            requestParameters?.tokenContractAddresses,
            requestParameters?.recvWindow,
            requestParameters?.nonce
        );
        return sendRequest<GetRwaTokenPriceResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Get the underlying company information for an RWA token.
     *
     * @summary Get RWA Underlying Info
     * @param {GetRwaUnderlyingInfoRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetRwaUnderlyingInfoResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-underlying-info Binance API Documentation}
     */
    public async getRwaUnderlyingInfo(
        requestParameters: GetRwaUnderlyingInfoRequest
    ): Promise<RestApiResponse<GetRwaUnderlyingInfoResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getRwaUnderlyingInfo(
            requestParameters?.binanceChainId,
            requestParameters?.tokenContractAddress,
            requestParameters?.recvWindow,
            requestParameters?.nonce
        );
        return sendRequest<GetRwaUnderlyingInfoResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Get market data for the underlying asset of an RWA token.
     *
     * @summary Get RWA Underlying Market Data
     * @param {GetRwaUnderlyingMarketDataRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetRwaUnderlyingMarketDataResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-underlying-market-data Binance API Documentation}
     */
    public async getRwaUnderlyingMarketData(
        requestParameters: GetRwaUnderlyingMarketDataRequest
    ): Promise<RestApiResponse<GetRwaUnderlyingMarketDataResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getRwaUnderlyingMarketData(
            requestParameters?.binanceChainId,
            requestParameters?.tokenContractAddress,
            requestParameters?.recvWindow,
            requestParameters?.nonce
        );
        return sendRequest<GetRwaUnderlyingMarketDataResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Search RWA tokens by keyword or contract address.
     *
     * @summary Search RWA Token
     * @param {SearchRwaTokenRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<SearchRwaTokenResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof RWADataApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#search-rwa-token Binance API Documentation}
     */
    public async searchRwaToken(
        requestParameters: SearchRwaTokenRequest
    ): Promise<RestApiResponse<SearchRwaTokenResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.searchRwaToken(
            requestParameters?.keyword,
            requestParameters?.recvWindow,
            requestParameters?.nonce,
            requestParameters?.platformId
        );
        return sendRequest<SearchRwaTokenResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }
}

export enum GetRwaTokenIssuancePlatformsPlatformIdEnum {
    ondo = 'ondo',
    bstock = 'bstock',
}

export enum GetRwaTokenListPlatformIdEnum {
    ondo = 'ondo',
    bstock = 'bstock',
}

export enum SearchRwaTokenPlatformIdEnum {
    ondo = 'ondo',
    bstock = 'bstock',
}
