/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {
    ConfigurationRestAPI,
    TimeUnit,
    RestApiResponse,
    assertParamExists,
    sendRequest,
    type RequestArgs,
} from '@binance/common';
import type {
    BroadcastTransactionsResponse,
    GetBroadcastOrdersResponse,
    GetGasLimitRequestEvmTx,
    GetGasLimitRequestSolTx,
    GetGasLimitResponse,
    GetGasPriceResponse,
    GetTransactionSupportedChainsResponse,
    SimulateTransactionsRequestEvmTx,
    SimulateTransactionsRequestSolTx,
    SimulateTransactionsResponse,
} from '../types';

/**
 * TransactionApi - axios parameter creator
 */
const TransactionApiAxiosParamCreator = function (configuration: ConfigurationRestAPI) {
    return {
        /**
         * Broadcast a client-signed transaction to the chain via the Binance Web3 API relay. Returns the transaction hash and an internal `orderId` you can use to track on-chain status via the post-transaction service.
         * Optional MEV protection (EVM chains only) routes the transaction through a private mempool to mitigate front-running and sandwich attacks.
         *
         * @summary Broadcast Transactions
         * @param {string} binanceChainId Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana).
         * @param {string} signedTransaction Client-signed raw transaction. EVM chains use a hex-encoded RLP transaction; Solana uses a base64-encoded signed transaction.
         * @param {string} address Sender wallet address. Used for status attribution and signature verification.
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds (default: 5000, max: 60000).
         * @param {string} [nonce] Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
         * @param {boolean} [enableMevProtection] When true, route the transaction through a private mempool for MEV protection.
         *
         * @throws {RequiredError}
         */
        broadcastTransactions: async (
            binanceChainId: string,
            signedTransaction: string,
            address: string,
            recvWindow?: number | bigint,
            nonce?: string,
            enableMevProtection?: boolean
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('broadcastTransactions', 'binanceChainId', binanceChainId);
            // verify required parameter 'signedTransaction' is not null or undefined
            assertParamExists('broadcastTransactions', 'signedTransaction', signedTransaction);
            // verify required parameter 'address' is not null or undefined
            assertParamExists('broadcastTransactions', 'address', address);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarBodyParameter['binanceChainId'] = binanceChainId;
            }

            if (signedTransaction !== undefined && signedTransaction !== null) {
                localVarBodyParameter['signedTransaction'] = signedTransaction;
            }

            if (address !== undefined && address !== null) {
                localVarBodyParameter['address'] = address;
            }

            if (enableMevProtection !== undefined && enableMevProtection !== null) {
                localVarBodyParameter['enableMevProtection'] = enableMevProtection;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/pre-transaction/broadcast-transaction',
                method: 'POST',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Look up broadcast orders previously submitted via `/pre-transaction/broadcast-transaction`. Filter by `txStatus` or `orderId`, paginate with `cursor`.
         *
         * @summary Get Broadcast Orders
         * @param {string} address Sender wallet address whose orders to list.
         * @param {string} binanceChainId Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds (default: 5000, max: 60000).
         * @param {string} [nonce] Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
         * @param {string} [txStatus] Optional filter on transaction status (server-defined string, e.g. "pending", "success", "fail").
         * @param {string} [orderId] Optional filter to fetch a single order by its internal order ID.
         * @param {string} [cursor] Pagination cursor returned by the previous page. Omit on the first request.
         * @param {number} [limit] Page size. Defaults to 20.
         *
         * @throws {RequiredError}
         */
        getBroadcastOrders: async (
            address: string,
            binanceChainId: string,
            recvWindow?: number | bigint,
            nonce?: string,
            txStatus?: string,
            orderId?: string,
            cursor?: string,
            limit?: number
        ): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('getBroadcastOrders', 'address', address);
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('getBroadcastOrders', 'binanceChainId', binanceChainId);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (address !== undefined && address !== null) {
                localVarQueryParameter['address'] = address;
            }
            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarQueryParameter['binanceChainId'] = binanceChainId;
            }
            if (txStatus !== undefined && txStatus !== null) {
                localVarQueryParameter['txStatus'] = txStatus;
            }
            if (orderId !== undefined && orderId !== null) {
                localVarQueryParameter['orderId'] = orderId;
            }
            if (cursor !== undefined && cursor !== null) {
                localVarQueryParameter['cursor'] = cursor;
            }
            if (limit !== undefined && limit !== null) {
                localVarQueryParameter['limit'] = limit;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/post-transaction/orders',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Estimate the gas limit (or compute-unit ceiling on Solana) for an unsigned transaction.
         * Provide either `evmTx` for EVM chains or `solTx` for Solana, matching the value of `binanceChainId`.
         *
         * @summary Get Gas Limit
         * @param {string} binanceChainId Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana). Provide `evmTx` for EVM chains or `solTx` for Solana — exactly one must be present. Note: both `evmTx` and `solTx` are marked required in this schema for rendering purposes only; in practice supply exactly one matching `binanceChainId`.
         * @param {GetGasLimitRequestEvmTx} evmTx
         * @param {GetGasLimitRequestSolTx} solTx
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds (default: 5000, max: 60000).
         * @param {string} [nonce] Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
         *
         * @throws {RequiredError}
         */
        getGasLimit: async (
            binanceChainId: string,
            evmTx: GetGasLimitRequestEvmTx,
            solTx: GetGasLimitRequestSolTx,
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('getGasLimit', 'binanceChainId', binanceChainId);
            // verify required parameter 'evmTx' is not null or undefined
            assertParamExists('getGasLimit', 'evmTx', evmTx);
            // verify required parameter 'solTx' is not null or undefined
            assertParamExists('getGasLimit', 'solTx', solTx);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarBodyParameter['binanceChainId'] = binanceChainId;
            }

            if (evmTx !== undefined && evmTx !== null) {
                localVarBodyParameter['evmTx'] = evmTx;
            }

            if (solTx !== undefined && solTx !== null) {
                localVarBodyParameter['solTx'] = solTx;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/pre-transaction/gas-limit',
                method: 'POST',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Query the current network gas price for the specified chain. The response shape varies by chain family:
         * - EVM chains return both `evmLegacyGasPrice` (legacy gasPrice) and
         * `eip1559GasPrice` (baseFee + priority/max fees) when EIP-1559 is supported.
         * - Solana returns `solanaGasPrice` (compute-unit prices and Jito tips).
         * Fields not applicable to the chain family are returned as `null`.
         *
         * @summary Get Gas Price
         * @param {string} binanceChainId Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds (default: 5000, max: 60000).
         * @param {string} [nonce] Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
         *
         * @throws {RequiredError}
         */
        getGasPrice: async (
            binanceChainId: string,
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('getGasPrice', 'binanceChainId', binanceChainId);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarQueryParameter['binanceChainId'] = binanceChainId;
            }

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/pre-transaction/gas-price',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Return the blockchain networks supported by the Transaction service for gas estimation, simulation, and broadcasting. The list is dynamically configured server-side and may change over time.
         *
         * @summary Get Transaction Supported Chains
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds (default: 5000, max: 60000).
         * @param {string} [nonce] Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
         *
         * @throws {RequiredError}
         */
        getTransactionSupportedChains: async (
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/pre-transaction/supported/chain',
                method: 'GET',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
        /**
         * Simulate transaction execution off-chain to predict its outcome before broadcasting. The response includes the predicted execution status, balance changes per affected account/token, and ERC-20 allowance changes (EVM chains).
         * Provide either `evmTx` (EVM chains) or `solTx` (Solana) matching `binanceChainId`.
         *
         * @summary Simulate Transactions
         * @param {string} binanceChainId Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana). Provide `evmTx` for EVM chains or `solTx` for Solana — exactly one must be present. Note: both `evmTx` and `solTx` are marked required in this schema for rendering purposes only; in practice supply exactly one matching `binanceChainId`.
         * @param {SimulateTransactionsRequestEvmTx} evmTx
         * @param {SimulateTransactionsRequestSolTx} solTx
         * @param {number | bigint} [recvWindow] Allowed time deviation in milliseconds (default: 5000, max: 60000).
         * @param {string} [nonce] Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
         *
         * @throws {RequiredError}
         */
        simulateTransactions: async (
            binanceChainId: string,
            evmTx: SimulateTransactionsRequestEvmTx,
            solTx: SimulateTransactionsRequestSolTx,
            recvWindow?: number | bigint,
            nonce?: string
        ): Promise<RequestArgs> => {
            // verify required parameter 'binanceChainId' is not null or undefined
            assertParamExists('simulateTransactions', 'binanceChainId', binanceChainId);
            // verify required parameter 'evmTx' is not null or undefined
            assertParamExists('simulateTransactions', 'evmTx', evmTx);
            // verify required parameter 'solTx' is not null or undefined
            assertParamExists('simulateTransactions', 'solTx', solTx);

            const localVarQueryParameter: Record<string, unknown> = {};
            const localVarBodyParameter: Record<string, unknown> = {};
            const localVarHeaderParameter: Record<string, unknown> = {};

            if (recvWindow !== undefined && recvWindow !== null) {
                localVarHeaderParameter['recvWindow'] = recvWindow;
            }
            if (nonce !== undefined && nonce !== null) {
                localVarHeaderParameter['nonce'] = nonce;
            }

            if (binanceChainId !== undefined && binanceChainId !== null) {
                localVarBodyParameter['binanceChainId'] = binanceChainId;
            }

            if (evmTx !== undefined && evmTx !== null) {
                localVarBodyParameter['evmTx'] = evmTx;
            }

            if (solTx !== undefined && solTx !== null) {
                localVarBodyParameter['solTx'] = solTx;
            }

            let _timeUnit: TimeUnit | undefined;
            if ('timeUnit' in configuration) _timeUnit = configuration.timeUnit as TimeUnit;

            return {
                endpoint: '/api/v1/dex/pre-transaction/simulate',
                method: 'POST',
                queryParams: localVarQueryParameter,
                bodyParams: localVarBodyParameter,
                headerParams: localVarHeaderParameter,
                timeUnit: _timeUnit,
            };
        },
    };
};

/**
 * TransactionApi - interface
 * @interface TransactionApi
 */
export interface TransactionApiInterface {
    /**
     * Broadcast a client-signed transaction to the chain via the Binance Web3 API relay. Returns the transaction hash and an internal `orderId` you can use to track on-chain status via the post-transaction service.
     * Optional MEV protection (EVM chains only) routes the transaction through a private mempool to mitigate front-running and sandwich attacks.
     *
     * @summary Broadcast Transactions
     * @param {BroadcastTransactionsRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApiInterface
     */
    broadcastTransactions(
        requestParameters: BroadcastTransactionsRequest
    ): Promise<RestApiResponse<BroadcastTransactionsResponse>>;
    /**
     * Look up broadcast orders previously submitted via `/pre-transaction/broadcast-transaction`. Filter by `txStatus` or `orderId`, paginate with `cursor`.
     *
     * @summary Get Broadcast Orders
     * @param {GetBroadcastOrdersRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApiInterface
     */
    getBroadcastOrders(
        requestParameters: GetBroadcastOrdersRequest
    ): Promise<RestApiResponse<GetBroadcastOrdersResponse>>;
    /**
     * Estimate the gas limit (or compute-unit ceiling on Solana) for an unsigned transaction.
     * Provide either `evmTx` for EVM chains or `solTx` for Solana, matching the value of `binanceChainId`.
     *
     * @summary Get Gas Limit
     * @param {GetGasLimitRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApiInterface
     */
    getGasLimit(
        requestParameters: GetGasLimitRequest
    ): Promise<RestApiResponse<GetGasLimitResponse>>;
    /**
     * Query the current network gas price for the specified chain. The response shape varies by chain family:
     * - EVM chains return both `evmLegacyGasPrice` (legacy gasPrice) and
     * `eip1559GasPrice` (baseFee + priority/max fees) when EIP-1559 is supported.
     * - Solana returns `solanaGasPrice` (compute-unit prices and Jito tips).
     * Fields not applicable to the chain family are returned as `null`.
     *
     * @summary Get Gas Price
     * @param {GetGasPriceRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApiInterface
     */
    getGasPrice(
        requestParameters: GetGasPriceRequest
    ): Promise<RestApiResponse<GetGasPriceResponse>>;
    /**
     * Return the blockchain networks supported by the Transaction service for gas estimation, simulation, and broadcasting. The list is dynamically configured server-side and may change over time.
     *
     * @summary Get Transaction Supported Chains
     * @param {GetTransactionSupportedChainsRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApiInterface
     */
    getTransactionSupportedChains(
        requestParameters?: GetTransactionSupportedChainsRequest
    ): Promise<RestApiResponse<GetTransactionSupportedChainsResponse>>;
    /**
     * Simulate transaction execution off-chain to predict its outcome before broadcasting. The response includes the predicted execution status, balance changes per affected account/token, and ERC-20 allowance changes (EVM chains).
     * Provide either `evmTx` (EVM chains) or `solTx` (Solana) matching `binanceChainId`.
     *
     * @summary Simulate Transactions
     * @param {SimulateTransactionsRequest} requestParameters Request parameters.
     *
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApiInterface
     */
    simulateTransactions(
        requestParameters: SimulateTransactionsRequest
    ): Promise<RestApiResponse<SimulateTransactionsResponse>>;
}

/**
 * Request parameters for broadcastTransactions operation in TransactionApi.
 * @interface BroadcastTransactionsRequest
 */
export interface BroadcastTransactionsRequest {
    /**
     * Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana).
     * @type {string}
     * @memberof TransactionApiBroadcastTransactions
     */
    readonly binanceChainId: string;

    /**
     * Client-signed raw transaction. EVM chains use a hex-encoded RLP transaction; Solana uses a base64-encoded signed transaction.
     * @type {string}
     * @memberof TransactionApiBroadcastTransactions
     */
    readonly signedTransaction: string;

    /**
     * Sender wallet address. Used for status attribution and signature verification.
     * @type {string}
     * @memberof TransactionApiBroadcastTransactions
     */
    readonly address: string;

    /**
     * Allowed time deviation in milliseconds (default: 5000, max: 60000).
     * @type {number | bigint}
     * @memberof TransactionApiBroadcastTransactions
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
     * @type {string}
     * @memberof TransactionApiBroadcastTransactions
     */
    readonly nonce?: string;

    /**
     * When true, route the transaction through a private mempool for MEV protection.
     * @type {boolean}
     * @memberof TransactionApiBroadcastTransactions
     */
    readonly enableMevProtection?: boolean;
}

/**
 * Request parameters for getBroadcastOrders operation in TransactionApi.
 * @interface GetBroadcastOrdersRequest
 */
export interface GetBroadcastOrdersRequest {
    /**
     * Sender wallet address whose orders to list.
     * @type {string}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly address: string;

    /**
     * Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
     * @type {string}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly binanceChainId: string;

    /**
     * Allowed time deviation in milliseconds (default: 5000, max: 60000).
     * @type {number | bigint}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
     * @type {string}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly nonce?: string;

    /**
     * Optional filter on transaction status (server-defined string, e.g. "pending", "success", "fail").
     * @type {string}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly txStatus?: string;

    /**
     * Optional filter to fetch a single order by its internal order ID.
     * @type {string}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly orderId?: string;

    /**
     * Pagination cursor returned by the previous page. Omit on the first request.
     * @type {string}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly cursor?: string;

    /**
     * Page size. Defaults to 20.
     * @type {number}
     * @memberof TransactionApiGetBroadcastOrders
     */
    readonly limit?: number;
}

/**
 * Request parameters for getGasLimit operation in TransactionApi.
 * @interface GetGasLimitRequest
 */
export interface GetGasLimitRequest {
    /**
     * Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana). Provide `evmTx` for EVM chains or `solTx` for Solana — exactly one must be present. Note: both `evmTx` and `solTx` are marked required in this schema for rendering purposes only; in practice supply exactly one matching `binanceChainId`.
     * @type {string}
     * @memberof TransactionApiGetGasLimit
     */
    readonly binanceChainId: string;

    /**
     *
     * @type {GetGasLimitRequestEvmTx}
     * @memberof TransactionApiGetGasLimit
     */
    readonly evmTx: GetGasLimitRequestEvmTx;

    /**
     *
     * @type {GetGasLimitRequestSolTx}
     * @memberof TransactionApiGetGasLimit
     */
    readonly solTx: GetGasLimitRequestSolTx;

    /**
     * Allowed time deviation in milliseconds (default: 5000, max: 60000).
     * @type {number | bigint}
     * @memberof TransactionApiGetGasLimit
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
     * @type {string}
     * @memberof TransactionApiGetGasLimit
     */
    readonly nonce?: string;
}

/**
 * Request parameters for getGasPrice operation in TransactionApi.
 * @interface GetGasPriceRequest
 */
export interface GetGasPriceRequest {
    /**
     * Unique chain identifier (e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana).
     * @type {string}
     * @memberof TransactionApiGetGasPrice
     */
    readonly binanceChainId: string;

    /**
     * Allowed time deviation in milliseconds (default: 5000, max: 60000).
     * @type {number | bigint}
     * @memberof TransactionApiGetGasPrice
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
     * @type {string}
     * @memberof TransactionApiGetGasPrice
     */
    readonly nonce?: string;
}

/**
 * Request parameters for getTransactionSupportedChains operation in TransactionApi.
 * @interface GetTransactionSupportedChainsRequest
 */
export interface GetTransactionSupportedChainsRequest {
    /**
     * Allowed time deviation in milliseconds (default: 5000, max: 60000).
     * @type {number | bigint}
     * @memberof TransactionApiGetTransactionSupportedChains
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
     * @type {string}
     * @memberof TransactionApiGetTransactionSupportedChains
     */
    readonly nonce?: string;
}

/**
 * Request parameters for simulateTransactions operation in TransactionApi.
 * @interface SimulateTransactionsRequest
 */
export interface SimulateTransactionsRequest {
    /**
     * Unique chain identifier (e.g. \"1\"=Ethereum, \"56\"=BSC, \"CT_501\"=Solana). Provide `evmTx` for EVM chains or `solTx` for Solana — exactly one must be present. Note: both `evmTx` and `solTx` are marked required in this schema for rendering purposes only; in practice supply exactly one matching `binanceChainId`.
     * @type {string}
     * @memberof TransactionApiSimulateTransactions
     */
    readonly binanceChainId: string;

    /**
     *
     * @type {SimulateTransactionsRequestEvmTx}
     * @memberof TransactionApiSimulateTransactions
     */
    readonly evmTx: SimulateTransactionsRequestEvmTx;

    /**
     *
     * @type {SimulateTransactionsRequestSolTx}
     * @memberof TransactionApiSimulateTransactions
     */
    readonly solTx: SimulateTransactionsRequestSolTx;

    /**
     * Allowed time deviation in milliseconds (default: 5000, max: 60000).
     * @type {number | bigint}
     * @memberof TransactionApiSimulateTransactions
     */
    readonly recvWindow?: number | bigint;

    /**
     * Unique request identifier for anti-replay; falls back to X-OC-SIGN if omitted.
     * @type {string}
     * @memberof TransactionApiSimulateTransactions
     */
    readonly nonce?: string;
}

/**
 * TransactionApi - object-oriented interface
 * @class TransactionApi
 */
export class TransactionApi implements TransactionApiInterface {
    private readonly configuration: ConfigurationRestAPI;
    private localVarAxiosParamCreator;

    constructor(configuration: ConfigurationRestAPI) {
        this.configuration = configuration;
        this.localVarAxiosParamCreator = TransactionApiAxiosParamCreator(configuration);
    }

    /**
     * Broadcast a client-signed transaction to the chain via the Binance Web3 API relay. Returns the transaction hash and an internal `orderId` you can use to track on-chain status via the post-transaction service.
     * Optional MEV protection (EVM chains only) routes the transaction through a private mempool to mitigate front-running and sandwich attacks.
     *
     * @summary Broadcast Transactions
     * @param {BroadcastTransactionsRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<BroadcastTransactionsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#broadcast-transactions Binance API Documentation}
     */
    public async broadcastTransactions(
        requestParameters: BroadcastTransactionsRequest
    ): Promise<RestApiResponse<BroadcastTransactionsResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.broadcastTransactions(
            requestParameters?.binanceChainId,
            requestParameters?.signedTransaction,
            requestParameters?.address,
            requestParameters?.recvWindow,
            requestParameters?.nonce,
            requestParameters?.enableMevProtection
        );
        return sendRequest<BroadcastTransactionsResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Look up broadcast orders previously submitted via `/pre-transaction/broadcast-transaction`. Filter by `txStatus` or `orderId`, paginate with `cursor`.
     *
     * @summary Get Broadcast Orders
     * @param {GetBroadcastOrdersRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetBroadcastOrdersResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-broadcast-orders Binance API Documentation}
     */
    public async getBroadcastOrders(
        requestParameters: GetBroadcastOrdersRequest
    ): Promise<RestApiResponse<GetBroadcastOrdersResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getBroadcastOrders(
            requestParameters?.address,
            requestParameters?.binanceChainId,
            requestParameters?.recvWindow,
            requestParameters?.nonce,
            requestParameters?.txStatus,
            requestParameters?.orderId,
            requestParameters?.cursor,
            requestParameters?.limit
        );
        return sendRequest<GetBroadcastOrdersResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Estimate the gas limit (or compute-unit ceiling on Solana) for an unsigned transaction.
     * Provide either `evmTx` for EVM chains or `solTx` for Solana, matching the value of `binanceChainId`.
     *
     * @summary Get Gas Limit
     * @param {GetGasLimitRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetGasLimitResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-gas-limit Binance API Documentation}
     */
    public async getGasLimit(
        requestParameters: GetGasLimitRequest
    ): Promise<RestApiResponse<GetGasLimitResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getGasLimit(
            requestParameters?.binanceChainId,
            requestParameters?.evmTx,
            requestParameters?.solTx,
            requestParameters?.recvWindow,
            requestParameters?.nonce
        );
        return sendRequest<GetGasLimitResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Query the current network gas price for the specified chain. The response shape varies by chain family:
     * - EVM chains return both `evmLegacyGasPrice` (legacy gasPrice) and
     * `eip1559GasPrice` (baseFee + priority/max fees) when EIP-1559 is supported.
     * - Solana returns `solanaGasPrice` (compute-unit prices and Jito tips).
     * Fields not applicable to the chain family are returned as `null`.
     *
     * @summary Get Gas Price
     * @param {GetGasPriceRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetGasPriceResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-gas-price Binance API Documentation}
     */
    public async getGasPrice(
        requestParameters: GetGasPriceRequest
    ): Promise<RestApiResponse<GetGasPriceResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.getGasPrice(
            requestParameters?.binanceChainId,
            requestParameters?.recvWindow,
            requestParameters?.nonce
        );
        return sendRequest<GetGasPriceResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Return the blockchain networks supported by the Transaction service for gas estimation, simulation, and broadcasting. The list is dynamically configured server-side and may change over time.
     *
     * @summary Get Transaction Supported Chains
     * @param {GetTransactionSupportedChainsRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<GetTransactionSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-transaction-supported-chains Binance API Documentation}
     */
    public async getTransactionSupportedChains(
        requestParameters: GetTransactionSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetTransactionSupportedChainsResponse>> {
        const localVarAxiosArgs =
            await this.localVarAxiosParamCreator.getTransactionSupportedChains(
                requestParameters?.recvWindow,
                requestParameters?.nonce
            );
        return sendRequest<GetTransactionSupportedChainsResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }

    /**
     * Simulate transaction execution off-chain to predict its outcome before broadcasting. The response includes the predicted execution status, balance changes per affected account/token, and ERC-20 allowance changes (EVM chains).
     * Provide either `evmTx` (EVM chains) or `solTx` (Solana) matching `binanceChainId`.
     *
     * @summary Simulate Transactions
     * @param {SimulateTransactionsRequest} requestParameters Request parameters.
     * @returns {Promise<RestApiResponse<SimulateTransactionsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @memberof TransactionApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#simulate-transactions Binance API Documentation}
     */
    public async simulateTransactions(
        requestParameters: SimulateTransactionsRequest
    ): Promise<RestApiResponse<SimulateTransactionsResponse>> {
        const localVarAxiosArgs = await this.localVarAxiosParamCreator.simulateTransactions(
            requestParameters?.binanceChainId,
            requestParameters?.evmTx,
            requestParameters?.solTx,
            requestParameters?.recvWindow,
            requestParameters?.nonce
        );
        return sendRequest<SimulateTransactionsResponse>(
            this.configuration,
            localVarAxiosArgs.endpoint,
            localVarAxiosArgs.method,
            localVarAxiosArgs.queryParams,
            localVarAxiosArgs.bodyParams,
            localVarAxiosArgs.headerParams,
            localVarAxiosArgs?.timeUnit,
            { isSigned: true }
        );
    }
}
