/**
 * Binance Web3 Wallet REST API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the OnchainOS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { jest, expect, beforeEach, describe, it } from '@jest/globals';
import { JSONParse, JSONStringify } from 'json-with-bigint';
import { ConfigurationRestAPI, type RestApiResponse } from '@binance/common';

import {
    MarketApi,
    GetCandlesBarEnum,
    GetHoldersRankingTagFilterEnum,
    GetHotTokenListRankByEnum,
    GetHotTokenListRankingTimeFrameEnum,
    GetTokenTradesTagFilterEnum,
    GetTopTradersTagFilterEnum,
} from '../../../src/rest-api';
import {
    GetCandlesRequest,
    GetHoldersRankingRequest,
    GetHotTokenListRequest,
    GetSupportedChainsRequest,
    GetTokenAdvancedInfoRequest,
    GetTokenBasicInfoRequest,
    GetTokenPriceRequest,
    GetTokenTradesRequest,
    GetTokenTradingInfoRequest,
    GetTopLiquidityPoolsRequest,
    GetTopTradersRequest,
    SearchTokenRequest,
} from '../../../src/rest-api';
import type {
    GetCandlesResponse,
    GetHoldersRankingResponse,
    GetHotTokenListResponse,
    GetSupportedChainsResponse,
    GetTokenAdvancedInfoResponse,
    GetTokenBasicInfoResponse,
    GetTokenPriceResponse,
    GetTokenTradesResponse,
    GetTokenTradingInfoResponse,
    GetTopLiquidityPoolsResponse,
    GetTopTradersResponse,
    SearchTokenResponse,
} from '../../../src/rest-api/types';

describe('MarketApi', () => {
    let client: MarketApi;
    let config: ConfigurationRestAPI;
    let mockResponse: object = {};

    beforeEach(() => {
        config = new ConfigurationRestAPI({
            apiKey: 'test-api-key',
            apiSecret: 'test-api-secret',
            basePath: '',
        });
        client = new MarketApi(config);
    });

    describe('getCandles()', () => {
        it('should execute getCandles() successfully with required parameters only', async () => {
            const params: GetCandlesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        [1.0001, 1.0023, 0.9987, 1.001, 125000.5, 1748600000000, 42],
                        [1.001, 1.0035, 1.0001, 1.0028, 187500.3, 1748600060000, 38],
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getCandles').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetCandlesResponse>)
            );
            const response = await client.getCandles(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getCandles() successfully with optional parameters', async () => {
            const params: GetCandlesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
                bar: GetCandlesBarEnum.BAR_1s,
                after: 1748600000000,
                before: 1748000000000,
                limit: 100,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        [1.0001, 1.0023, 0.9987, 1.001, 125000.5, 1748600000000, 42],
                        [1.001, 1.0035, 1.0001, 1.0028, 187500.3, 1748600060000, 38],
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getCandles').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetCandlesResponse>)
            );
            const response = await client.getCandles(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetCandlesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getCandles(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getCandles.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetCandlesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getCandles(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getCandles.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetCandlesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getCandles').mockRejectedValueOnce(mockError);
            await expect(client.getCandles(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getHoldersRanking()', () => {
        it('should execute getHoldersRanking() successfully with required parameters only', async () => {
            const params: GetHoldersRankingRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            holderWalletAddress: '0x28c6c06298d514db089934071355e5743bf21d60',
                            holdAmount: '18580000',
                            holdingPercent: '5.23',
                            nativeTokenSymbol: 'ETH',
                            nativeTokenBalance: '12.5',
                            boughtAmount: '18580000',
                            avgBuyPrice: '0.000105',
                            soldAmount: '15000000',
                            avgSellPrice: '0.000195',
                            maxHoldAmount: '30000000',
                            lastTradeTime: 1716892020000,
                            realizedPnlUsd: '1277.84',
                            fundingSource: '0x28c6c06298d514db089934071355e5743bf21d60',
                            fundingSourceLabel: { tagName: 'cex', tagValue: 'Binance' },
                            fundingSourceHash: '0x3a2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
                            fundingSourceTime: 1714000000000,
                            fundingSourceAmount: '0.5',
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getHoldersRanking').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetHoldersRankingResponse>)
            );
            const response = await client.getHoldersRanking(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getHoldersRanking() successfully with optional parameters', async () => {
            const params: GetHoldersRankingRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
                tagFilter: GetHoldersRankingTagFilterEnum.TAG_FILTER_1,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            holderWalletAddress: '0x28c6c06298d514db089934071355e5743bf21d60',
                            holdAmount: '18580000',
                            holdingPercent: '5.23',
                            nativeTokenSymbol: 'ETH',
                            nativeTokenBalance: '12.5',
                            boughtAmount: '18580000',
                            avgBuyPrice: '0.000105',
                            soldAmount: '15000000',
                            avgSellPrice: '0.000195',
                            maxHoldAmount: '30000000',
                            lastTradeTime: 1716892020000,
                            realizedPnlUsd: '1277.84',
                            fundingSource: '0x28c6c06298d514db089934071355e5743bf21d60',
                            fundingSourceLabel: { tagName: 'cex', tagValue: 'Binance' },
                            fundingSourceHash: '0x3a2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
                            fundingSourceTime: 1714000000000,
                            fundingSourceAmount: '0.5',
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getHoldersRanking').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetHoldersRankingResponse>)
            );
            const response = await client.getHoldersRanking(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetHoldersRankingRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getHoldersRanking(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getHoldersRanking.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetHoldersRankingRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getHoldersRanking(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getHoldersRanking.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetHoldersRankingRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getHoldersRanking').mockRejectedValueOnce(mockError);
            await expect(client.getHoldersRanking(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getHotTokenList()', () => {
        it('should execute getHotTokenList() successfully with required parameters only', async () => {
            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        page: 1,
                        items: [
                            {
                                binanceChainId: '1',
                                tokenSymbol: 'PEPE',
                                tokenLogoUrl: 'https://static.onchainos.com/tokens/pepe.png',
                                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                marketCap: '5830000.50',
                                volume: '1250000.30',
                                change: '12.5',
                                uniqueTraders: '2341',
                                buyTxs: '1523',
                                sellTxs: '987',
                                txs: '2510',
                                liquidity: '680000.00',
                                price: '0.00000702',
                                holders: '45832',
                                inflowUsd: '125000.50',
                                devHoldingPercent: '5.5',
                                bnHolderCount: '1203',
                                top10HoldingPercent: '35.2',
                                sniperHoldingPercent: '8.3',
                                proHoldingPercent: '12.1',
                                freshWalletHoldingPercent: '3.5',
                                smartMoneyHoldingPercent: '1.52',
                                kolHoldingPercent: '6.5',
                                insiderHoldingPercent: '2.8',
                                bundlerHoldingPercent: '6.2',
                                devCreatedTokenCount: '3',
                                devMigratedTokenCount: '1',
                                devMigratedTokenPercent: '33.3',
                                tokenTags: ['Alpha'],
                            },
                        ],
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getHotTokenList').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetHotTokenListResponse>)
            );
            const response = await client.getHotTokenList();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getHotTokenList() successfully with optional parameters', async () => {
            const params: GetHotTokenListRequest = {
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
                binanceChainId: '1',
                rankBy: GetHotTokenListRankByEnum.RANK_BY_1,
                rankingTimeFrame: GetHotTokenListRankingTimeFrameEnum.RANKING_TIME_FRAME_1,
                priceChangePercentMin: '5',
                priceChangePercentMax: '100',
                volumeMin: '10000',
                volumeMax: '1000000',
                txsMin: '100',
                txsMax: '10000',
                marketCapMin: '100000',
                marketCapMax: '100000000',
                liquidityMin: '10000',
                liquidityMax: '10000000',
                devHoldingPercentMin: '0',
                devHoldingPercentMax: '10',
                inflowUsdMin: '0',
                inflowUsdMax: '1000000',
                holdersMin: '100',
                holdersMax: '100000',
                bnHolderCountMin: '0',
                bnHolderCountMax: '10000',
                top10HoldingPercentMin: '0',
                top10HoldingPercentMax: '100',
                sniperHoldingPercentMin: '0',
                sniperHoldingPercentMax: '100',
                smartMoneyHoldingPercentMin: '0',
                smartMoneyHoldingPercentMax: '100',
                kolHoldingPercentMin: '0',
                kolHoldingPercentMax: '100',
                proHoldingPercentMin: '0',
                proHoldingPercentMax: '100',
                freshWalletHoldingPercentMin: '0',
                freshWalletHoldingPercentMax: '100',
                insiderHoldingPercentMin: '0',
                insiderHoldingPercentMax: '100',
                bundlerHoldingPercentMin: '0',
                bundlerHoldingPercentMax: '100',
                devCreatedTokenCountMin: '0',
                devCreatedTokenCountMax: '100',
                devMigratedTokenCountMin: '0',
                devMigratedTokenCountMax: '100',
                devMigratedTokenPercentMin: '0',
                devMigratedTokenPercentMax: '100',
                isDevSoldAll: false,
                isDevBurned: false,
                isMint: false,
                isFreeze: false,
                isHideWashTradingTokens: true,
                isHideDevWashTradingTokens: true,
                isHideInternalWashTradingTokens: true,
                pageId: 1,
                size: 100,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        page: 1,
                        items: [
                            {
                                binanceChainId: '1',
                                tokenSymbol: 'PEPE',
                                tokenLogoUrl: 'https://static.onchainos.com/tokens/pepe.png',
                                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                marketCap: '5830000.50',
                                volume: '1250000.30',
                                change: '12.5',
                                uniqueTraders: '2341',
                                buyTxs: '1523',
                                sellTxs: '987',
                                txs: '2510',
                                liquidity: '680000.00',
                                price: '0.00000702',
                                holders: '45832',
                                inflowUsd: '125000.50',
                                devHoldingPercent: '5.5',
                                bnHolderCount: '1203',
                                top10HoldingPercent: '35.2',
                                sniperHoldingPercent: '8.3',
                                proHoldingPercent: '12.1',
                                freshWalletHoldingPercent: '3.5',
                                smartMoneyHoldingPercent: '1.52',
                                kolHoldingPercent: '6.5',
                                insiderHoldingPercent: '2.8',
                                bundlerHoldingPercent: '6.2',
                                devCreatedTokenCount: '3',
                                devMigratedTokenCount: '1',
                                devMigratedTokenPercent: '33.3',
                                tokenTags: ['Alpha'],
                            },
                        ],
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getHotTokenList').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetHotTokenListResponse>)
            );
            const response = await client.getHotTokenList(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getHotTokenList').mockRejectedValueOnce(mockError);
            await expect(client.getHotTokenList()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getSupportedChains()', () => {
        it('should execute getSupportedChains() successfully with required parameters only', async () => {
            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            name: 'Ethereum',
                            shortName: 'ETH',
                            logoUrl:
                                'https://onchainos.bnbstatic.com/image/admin_mgs_image_upload/20250228/b549e557-76ca-4873-88ef-3a107cf2c9fe.png',
                            caseSensitive: false,
                            nativeTokenSymbol: 'ETH',
                            nativeTokenDecimals: 18,
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getSupportedChains').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetSupportedChainsResponse>)
            );
            const response = await client.getSupportedChains();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getSupportedChains() successfully with optional parameters', async () => {
            const params: GetSupportedChainsRequest = {
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            name: 'Ethereum',
                            shortName: 'ETH',
                            logoUrl:
                                'https://onchainos.bnbstatic.com/image/admin_mgs_image_upload/20250228/b549e557-76ca-4873-88ef-3a107cf2c9fe.png',
                            caseSensitive: false,
                            nativeTokenSymbol: 'ETH',
                            nativeTokenDecimals: 18,
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getSupportedChains').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetSupportedChainsResponse>)
            );
            const response = await client.getSupportedChains(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getSupportedChains').mockRejectedValueOnce(mockError);
            await expect(client.getSupportedChains()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTokenAdvancedInfo()', () => {
        it('should execute getTokenAdvancedInfo() successfully with required parameters only', async () => {
            const params: GetTokenAdvancedInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        binanceChainId: '1',
                        tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                        isInternal: 0,
                        protocolId: 1,
                        progress: '75',
                        createTime: 1714000000000,
                        creatorAddress: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
                        devCreatedTokenCount: 15,
                        devMigratedTokenCount: 8,
                        devMigratedTokenPercent: '53.5',
                        top10HoldingPercent: '40.08',
                        devHoldingPercent: '5.23',
                        smartMoneyHoldingPercent: '2.15',
                        kolHoldingPercent: '1.5',
                        bundlerHoldingPercent: '12.3',
                        proHoldingPercent: '4.2',
                        freshWalletHoldingPercent: '3.8',
                        sniperHoldingPercent: '3.1',
                        insiderHoldingPercent: '2.5',
                        holders: 45832,
                        bnHolderCount: 1203,
                        bnTraderCount7D: 250,
                        tokenTags: ['Alpha'],
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenAdvancedInfo').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenAdvancedInfoResponse>)
            );
            const response = await client.getTokenAdvancedInfo(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTokenAdvancedInfo() successfully with optional parameters', async () => {
            const params: GetTokenAdvancedInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        binanceChainId: '1',
                        tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                        isInternal: 0,
                        protocolId: 1,
                        progress: '75',
                        createTime: 1714000000000,
                        creatorAddress: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
                        devCreatedTokenCount: 15,
                        devMigratedTokenCount: 8,
                        devMigratedTokenPercent: '53.5',
                        top10HoldingPercent: '40.08',
                        devHoldingPercent: '5.23',
                        smartMoneyHoldingPercent: '2.15',
                        kolHoldingPercent: '1.5',
                        bundlerHoldingPercent: '12.3',
                        proHoldingPercent: '4.2',
                        freshWalletHoldingPercent: '3.8',
                        sniperHoldingPercent: '3.1',
                        insiderHoldingPercent: '2.5',
                        holders: 45832,
                        bnHolderCount: 1203,
                        bnTraderCount7D: 250,
                        tokenTags: ['Alpha'],
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenAdvancedInfo').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenAdvancedInfoResponse>)
            );
            const response = await client.getTokenAdvancedInfo(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetTokenAdvancedInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getTokenAdvancedInfo(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getTokenAdvancedInfo.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetTokenAdvancedInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getTokenAdvancedInfo(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getTokenAdvancedInfo.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetTokenAdvancedInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTokenAdvancedInfo').mockRejectedValueOnce(mockError);
            await expect(client.getTokenAdvancedInfo(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTokenBasicInfo()', () => {
        it('should execute getTokenBasicInfo() successfully with required parameters only', async () => {
            const params: GetTokenBasicInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        binanceChainId: '1',
                        tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                        tokenName: 'Tether USD',
                        tokenSymbol: 'USDT',
                        tokenLogoUrl: 'https://static.onchainos.com/tokens/usdt.png',
                        decimals: 6,
                        creatorAddress: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
                        createTime: 1716892020000,
                        tagList: { isRecognized: true },
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenBasicInfo').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenBasicInfoResponse>)
            );
            const response = await client.getTokenBasicInfo(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTokenBasicInfo() successfully with optional parameters', async () => {
            const params: GetTokenBasicInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        binanceChainId: '1',
                        tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                        tokenName: 'Tether USD',
                        tokenSymbol: 'USDT',
                        tokenLogoUrl: 'https://static.onchainos.com/tokens/usdt.png',
                        decimals: 6,
                        creatorAddress: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
                        createTime: 1716892020000,
                        tagList: { isRecognized: true },
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenBasicInfo').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenBasicInfoResponse>)
            );
            const response = await client.getTokenBasicInfo(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetTokenBasicInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getTokenBasicInfo(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getTokenBasicInfo.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetTokenBasicInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getTokenBasicInfo(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getTokenBasicInfo.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetTokenBasicInfoRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTokenBasicInfo').mockRejectedValueOnce(mockError);
            await expect(client.getTokenBasicInfo(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTokenPrice()', () => {
        it('should execute getTokenPrice() successfully with required parameters only', async () => {
            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                            price: '1.0002',
                            time: 1748601600000,
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenPrice').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenPriceResponse>)
            );
            const response = await client.getTokenPrice();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTokenPrice() successfully with optional parameters', async () => {
            const params: GetTokenPriceRequest = {
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                            price: '1.0002',
                            time: 1748601600000,
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenPrice').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenPriceResponse>)
            );
            const response = await client.getTokenPrice(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTokenPrice').mockRejectedValueOnce(mockError);
            await expect(client.getTokenPrice()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTokenTrades()', () => {
        it('should execute getTokenTrades() successfully with required parameters only', async () => {
            const params: GetTokenTradesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        cursor: 'eyJ0aW1lIjoxNzQ4NTk5MDAwMDAwLCJpZCI6Nzh9',
                        trades: [
                            {
                                binanceChainId: '1',
                                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                txHash: '0xabc123def4567890abc123def4567890abc123def4567890abc123def4567890',
                                userAddress: '0x28c6c06298d514db089934071355e5743bf21d60',
                                dexName: 'Uniswap V3',
                                type: 'buy',
                                price: '0.00000702',
                                volume: '1500.50',
                                time: 1748601600000,
                                changedTokenInfo: [
                                    {
                                        amount: '1500000',
                                        tokenSymbol: 'PEPE',
                                        tokenContractAddress:
                                            '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                    },
                                ],
                            },
                        ],
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenTrades').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenTradesResponse>)
            );
            const response = await client.getTokenTrades(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTokenTrades() successfully with optional parameters', async () => {
            const params: GetTokenTradesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
                cursor: 'eyJ0aW1lIjoxNzQ4NjAwMDAwMDAwLCJpZCI6MTIzfQ==',
                limit: 100,
                tagFilter: GetTokenTradesTagFilterEnum.TAG_FILTER_1,
                walletAddressFilter: '0x28c6c06298d514db089934071355e5743bf21d60',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: {
                        cursor: 'eyJ0aW1lIjoxNzQ4NTk5MDAwMDAwLCJpZCI6Nzh9',
                        trades: [
                            {
                                binanceChainId: '1',
                                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                txHash: '0xabc123def4567890abc123def4567890abc123def4567890abc123def4567890',
                                userAddress: '0x28c6c06298d514db089934071355e5743bf21d60',
                                dexName: 'Uniswap V3',
                                type: 'buy',
                                price: '0.00000702',
                                volume: '1500.50',
                                time: 1748601600000,
                                changedTokenInfo: [
                                    {
                                        amount: '1500000',
                                        tokenSymbol: 'PEPE',
                                        tokenContractAddress:
                                            '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                    },
                                ],
                            },
                        ],
                    },
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenTrades').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenTradesResponse>)
            );
            const response = await client.getTokenTrades(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetTokenTradesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getTokenTrades(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getTokenTrades.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetTokenTradesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getTokenTrades(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getTokenTrades.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetTokenTradesRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTokenTrades').mockRejectedValueOnce(mockError);
            await expect(client.getTokenTrades(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTokenTradingInfo()', () => {
        it('should execute getTokenTradingInfo() successfully with required parameters only', async () => {
            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                            price: '1.0002',
                            time: 1748601600000,
                            marketCap: '83500000.00',
                            priceChange5M: '0.12',
                            priceChange1H: '1.05',
                            priceChange4H: '2.30',
                            priceChange24H: '-0.85',
                            volume5M: '12500.50',
                            volume1H: '120000.30',
                            volume4H: '550000.20',
                            volume24H: '1250000.50',
                            buyVolume5M: '6800.00',
                            buyVolume1H: '65000.00',
                            buyVolume4H: '300000.00',
                            buyVolume24H: '680000.30',
                            sellVolume5M: '5700.00',
                            sellVolume1H: '55000.00',
                            sellVolume4H: '250000.00',
                            sellVolume24H: '570000.20',
                            txs5M: 60,
                            txs1H: 720,
                            txs4H: 2880,
                            txs24H: 1523,
                            buyTxs5M: 33,
                            buyTxs1H: 380,
                            buyTxs4H: 1500,
                            buyTxs24H: 812,
                            sellTxs5M: 27,
                            sellTxs1H: 340,
                            sellTxs4H: 1380,
                            sellTxs24H: 711,
                            maxPrice: '1.0023',
                            minPrice: '0.9987',
                            circSupply: '83000000000',
                            liquidity: '1250000.50',
                            holders: 45832,
                            bnVolume5M: '0',
                            bnVolume1H: '0',
                            bnVolume4H: '0',
                            bnVolume24H: '35000.80',
                            bnBuyVolume5M: '0',
                            bnBuyVolume1H: '0',
                            bnBuyVolume4H: '0',
                            bnBuyVolume24H: '20000.50',
                            bnSellVolume5M: '0',
                            bnSellVolume1H: '0',
                            bnSellVolume4H: '0',
                            bnSellVolume24H: '15000.30',
                            bnTxs5M: 0,
                            bnTxs1H: 0,
                            bnTxs4H: 0,
                            bnTxs24H: 156,
                            bnBuyTxs5M: 0,
                            bnBuyTxs1H: 0,
                            bnBuyTxs4H: 0,
                            bnBuyTxs24H: 89,
                            bnSellTxs5M: 0,
                            bnSellTxs1H: 0,
                            bnSellTxs4H: 0,
                            bnSellTxs24H: 67,
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenTradingInfo').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenTradingInfoResponse>)
            );
            const response = await client.getTokenTradingInfo();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTokenTradingInfo() successfully with optional parameters', async () => {
            const params: GetTokenTradingInfoRequest = {
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                            price: '1.0002',
                            time: 1748601600000,
                            marketCap: '83500000.00',
                            priceChange5M: '0.12',
                            priceChange1H: '1.05',
                            priceChange4H: '2.30',
                            priceChange24H: '-0.85',
                            volume5M: '12500.50',
                            volume1H: '120000.30',
                            volume4H: '550000.20',
                            volume24H: '1250000.50',
                            buyVolume5M: '6800.00',
                            buyVolume1H: '65000.00',
                            buyVolume4H: '300000.00',
                            buyVolume24H: '680000.30',
                            sellVolume5M: '5700.00',
                            sellVolume1H: '55000.00',
                            sellVolume4H: '250000.00',
                            sellVolume24H: '570000.20',
                            txs5M: 60,
                            txs1H: 720,
                            txs4H: 2880,
                            txs24H: 1523,
                            buyTxs5M: 33,
                            buyTxs1H: 380,
                            buyTxs4H: 1500,
                            buyTxs24H: 812,
                            sellTxs5M: 27,
                            sellTxs1H: 340,
                            sellTxs4H: 1380,
                            sellTxs24H: 711,
                            maxPrice: '1.0023',
                            minPrice: '0.9987',
                            circSupply: '83000000000',
                            liquidity: '1250000.50',
                            holders: 45832,
                            bnVolume5M: '0',
                            bnVolume1H: '0',
                            bnVolume4H: '0',
                            bnVolume24H: '35000.80',
                            bnBuyVolume5M: '0',
                            bnBuyVolume1H: '0',
                            bnBuyVolume4H: '0',
                            bnBuyVolume24H: '20000.50',
                            bnSellVolume5M: '0',
                            bnSellVolume1H: '0',
                            bnSellVolume4H: '0',
                            bnSellVolume24H: '15000.30',
                            bnTxs5M: 0,
                            bnTxs1H: 0,
                            bnTxs4H: 0,
                            bnTxs24H: 156,
                            bnBuyTxs5M: 0,
                            bnBuyTxs1H: 0,
                            bnBuyTxs4H: 0,
                            bnBuyTxs24H: 89,
                            bnSellTxs5M: 0,
                            bnSellTxs1H: 0,
                            bnSellTxs4H: 0,
                            bnSellTxs24H: 67,
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTokenTradingInfo').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTokenTradingInfoResponse>)
            );
            const response = await client.getTokenTradingInfo(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTokenTradingInfo').mockRejectedValueOnce(mockError);
            await expect(client.getTokenTradingInfo()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTopLiquidityPools()', () => {
        it('should execute getTopLiquidityPools() successfully with required parameters only', async () => {
            const params: GetTopLiquidityPoolsRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            pool: 'PEPE/WETH',
                            protocolName: 'Uniswap V3',
                            protocolLogoUrl: 'https://static.onchainos.com/protocols/uniswap.png',
                            liquidityUsd: '680000.00',
                            poolAddress: '0x11950d141ecb863f01007add7d1a342041227b58',
                            liquidityAmount: [
                                {
                                    tokenAmount: '1500000000',
                                    tokenSymbol: 'PEPE',
                                    tokenName: 'Pepe',
                                    tokenContractAddress:
                                        '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                    tokenLogoUrl: 'https://static.onchainos.com/tokens/pepe.png',
                                },
                            ],
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTopLiquidityPools').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTopLiquidityPoolsResponse>)
            );
            const response = await client.getTopLiquidityPools(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTopLiquidityPools() successfully with optional parameters', async () => {
            const params: GetTopLiquidityPoolsRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            pool: 'PEPE/WETH',
                            protocolName: 'Uniswap V3',
                            protocolLogoUrl: 'https://static.onchainos.com/protocols/uniswap.png',
                            liquidityUsd: '680000.00',
                            poolAddress: '0x11950d141ecb863f01007add7d1a342041227b58',
                            liquidityAmount: [
                                {
                                    tokenAmount: '1500000000',
                                    tokenSymbol: 'PEPE',
                                    tokenName: 'Pepe',
                                    tokenContractAddress:
                                        '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                                    tokenLogoUrl: 'https://static.onchainos.com/tokens/pepe.png',
                                },
                            ],
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTopLiquidityPools').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTopLiquidityPoolsResponse>)
            );
            const response = await client.getTopLiquidityPools(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetTopLiquidityPoolsRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getTopLiquidityPools(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getTopLiquidityPools.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetTopLiquidityPoolsRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getTopLiquidityPools(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getTopLiquidityPools.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetTopLiquidityPoolsRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTopLiquidityPools').mockRejectedValueOnce(mockError);
            await expect(client.getTopLiquidityPools(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('getTopTraders()', () => {
        it('should execute getTopTraders() successfully with required parameters only', async () => {
            const params: GetTopTradersRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            holderWalletAddress: '0x28c6c06298d514db089934071355e5743bf21d60',
                            holdAmount: '18580000',
                            holdingPercent: '3.5',
                            boughtAmount: '25000000',
                            avgBuyPrice: '0.000105',
                            soldAmount: '20000000',
                            avgSellPrice: '0.000195',
                            maxHoldAmount: '30000000',
                            lastTradeTime: 1716892020000,
                            realizedPnlUsd: '1800.30',
                            fundingSource: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
                            fundingSourceLabel: { tagName: 'cex', tagValue: 'Binance' },
                            fundingSourceHash: '0x3a2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
                            fundingSourceTime: 1714000000000,
                            fundingSourceAmount: '0.5',
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTopTraders').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTopTradersResponse>)
            );
            const response = await client.getTopTraders(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute getTopTraders() successfully with optional parameters', async () => {
            const params: GetTopTradersRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
                tagFilter: GetTopTradersTagFilterEnum.TAG_FILTER_1,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            holderWalletAddress: '0x28c6c06298d514db089934071355e5743bf21d60',
                            holdAmount: '18580000',
                            holdingPercent: '3.5',
                            boughtAmount: '25000000',
                            avgBuyPrice: '0.000105',
                            soldAmount: '20000000',
                            avgSellPrice: '0.000195',
                            maxHoldAmount: '30000000',
                            lastTradeTime: 1716892020000,
                            realizedPnlUsd: '1800.30',
                            fundingSource: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
                            fundingSourceLabel: { tagName: 'cex', tagValue: 'Binance' },
                            fundingSourceHash: '0x3a2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
                            fundingSourceTime: 1714000000000,
                            fundingSourceAmount: '0.5',
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'getTopTraders').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<GetTopTradersResponse>)
            );
            const response = await client.getTopTraders(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when binanceChainId is missing', async () => {
            const _params: GetTopTradersRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.binanceChainId;

            await expect(client.getTopTraders(params)).rejects.toThrow(
                'Required parameter binanceChainId was null or undefined when calling getTopTraders.'
            );
        });

        it('should throw RequiredError when tokenContractAddress is missing', async () => {
            const _params: GetTopTradersRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };
            const params = Object.assign({ ..._params });
            delete params?.tokenContractAddress;

            await expect(client.getTopTraders(params)).rejects.toThrow(
                'Required parameter tokenContractAddress was null or undefined when calling getTopTraders.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: GetTopTradersRequest = {
                binanceChainId: '1',
                tokenContractAddress: '0x6982508145454ce325ddbe47a25d4ec3d2311933',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'getTopTraders').mockRejectedValueOnce(mockError);
            await expect(client.getTopTraders(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('searchToken()', () => {
        it('should execute searchToken() successfully with required parameters only', async () => {
            const params: SearchTokenRequest = {
                chains: '1,56,CT_501',
                search: 'USDT',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            tokenName: 'Tether USD',
                            tokenSymbol: 'USDT',
                            tokenLogoUrl: 'https://static.onchainos.com/tokens/usdt.png',
                            tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                            decimals: 6,
                            explorerUrl:
                                'https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7',
                            change: '-5.23',
                            holders: '45832',
                            liquidity: '1250000.50',
                            marketCap: '83500000.00',
                            price: '1.0001',
                            tagList: { isRecognized: true },
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'searchToken').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<SearchTokenResponse>)
            );
            const response = await client.searchToken(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute searchToken() successfully with optional parameters', async () => {
            const params: SearchTokenRequest = {
                chains: '1,56,CT_501',
                search: 'USDT',
                recvWindow: 5000,
                nonce: 'unique-nonce-string',
            };

            mockResponse = JSONParse(
                JSONStringify({
                    code: 0,
                    msg: 'success',
                    data: [
                        {
                            binanceChainId: '1',
                            tokenName: 'Tether USD',
                            tokenSymbol: 'USDT',
                            tokenLogoUrl: 'https://static.onchainos.com/tokens/usdt.png',
                            tokenContractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
                            decimals: 6,
                            explorerUrl:
                                'https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7',
                            change: '-5.23',
                            holders: '45832',
                            liquidity: '1250000.50',
                            marketCap: '83500000.00',
                            price: '1.0001',
                            tagList: { isRecognized: true },
                        },
                    ],
                    timestamp: 1748601600000,
                    success: true,
                })
            );

            const spy = jest.spyOn(client, 'searchToken').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<SearchTokenResponse>)
            );
            const response = await client.searchToken(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when chains is missing', async () => {
            const _params: SearchTokenRequest = {
                chains: '1,56,CT_501',
                search: 'USDT',
            };
            const params = Object.assign({ ..._params });
            delete params?.chains;

            await expect(client.searchToken(params)).rejects.toThrow(
                'Required parameter chains was null or undefined when calling searchToken.'
            );
        });

        it('should throw RequiredError when search is missing', async () => {
            const _params: SearchTokenRequest = {
                chains: '1,56,CT_501',
                search: 'USDT',
            };
            const params = Object.assign({ ..._params });
            delete params?.search;

            await expect(client.searchToken(params)).rejects.toThrow(
                'Required parameter search was null or undefined when calling searchToken.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: SearchTokenRequest = {
                chains: '1,56,CT_501',
                search: 'USDT',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'searchToken').mockRejectedValueOnce(mockError);
            await expect(client.searchToken(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });
});
