/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConfigurationRestAPI, RestApiResponse, sendRequest } from '@binance/common';
import { GeneralDataApi } from './modules/general-data-api';
import { RWADataApi } from './modules/rwadata-api';
import { TradingApi } from './modules/trading-api';
import { TransactionApi } from './modules/transaction-api';
import { WalletApi } from './modules/wallet-api';

import type {
    GetAddressTrackerTradesRequest,
    GetCandlesRequest,
    GetHoldersRankingRequest,
    GetHotTokenListRequest,
    GetLeaderboardListRequest,
    GetLeaderboardSupportedChainsRequest,
    GetPortfolioDexHistoryRequest,
    GetPortfolioOverviewRequest,
    GetPortfolioRecentPnLRequest,
    GetPortfolioSupportedChainsRequest,
    GetPortfolioTokenLatestPnLRequest,
    GetSupportedChainsRequest,
    GetTokenAdvancedInfoRequest,
    GetTokenBasicInfoRequest,
    GetTokenDevInfoRequest,
    GetTokenPriceRequest,
    GetTokenTradesRequest,
    GetTokenTradingInfoRequest,
    GetTopLiquidityPoolsRequest,
    GetTopTradersRequest,
    SearchTokenRequest,
} from './modules/general-data-api';
import type {
    GetRwaTokenIssuancePlatformsRequest,
    GetRwaTokenListRequest,
    GetRwaTokenPriceRequest,
    GetRwaUnderlyingInfoRequest,
    GetRwaUnderlyingMarketDataRequest,
    SearchRwaTokenRequest,
} from './modules/rwadata-api';
import type {
    BuildSolanaSwapInstructionsRequest,
    BuildSwapTransactionRequest,
    GetAggregatedQuoteRequest,
    GetAggregatorSupportedChainsRequest,
    GetErc20ApproveTransactionRequest,
    GetRfqOrderStatusRequest,
    GetTransactionStatusRequest,
    SubmitRfqOrderRequest,
} from './modules/trading-api';
import type {
    BroadcastTransactionsRequest,
    GetBroadcastOrdersRequest,
    GetGasLimitRequest,
    GetGasPriceRequest,
    GetTransactionSupportedChainsRequest,
    SimulateTransactionsRequest,
} from './modules/transaction-api';
import type {
    GetAllTokenBalancesByAddressRequest,
    GetTokenBalancesByAddressRequest,
    GetTransactionDetailByHashRequest,
    GetTransactionsByAddressRequest,
    GetWalletSupportedChainsRequest,
} from './modules/wallet-api';

import type {
    GetAddressTrackerTradesResponse,
    GetCandlesResponse,
    GetHoldersRankingResponse,
    GetHotTokenListResponse,
    GetLeaderboardListResponse,
    GetLeaderboardSupportedChainsResponse,
    GetPortfolioDexHistoryResponse,
    GetPortfolioOverviewResponse,
    GetPortfolioRecentPnLResponse,
    GetPortfolioSupportedChainsResponse,
    GetPortfolioTokenLatestPnLResponse,
    GetSupportedChainsResponse,
    GetTokenAdvancedInfoResponse,
    GetTokenBasicInfoResponse,
    GetTokenDevInfoResponse,
    GetTokenPriceResponse,
    GetTokenTradesResponse,
    GetTokenTradingInfoResponse,
    GetTopLiquidityPoolsResponse,
    GetTopTradersResponse,
    SearchTokenResponse,
} from './types';
import type {
    GetRwaTokenIssuancePlatformsResponse,
    GetRwaTokenListResponse,
    GetRwaTokenPriceResponse,
    GetRwaUnderlyingInfoResponse,
    GetRwaUnderlyingMarketDataResponse,
    SearchRwaTokenResponse,
} from './types';
import type {
    BuildSolanaSwapInstructionsResponse,
    BuildSwapTransactionResponse,
    GetAggregatedQuoteResponse,
    GetAggregatorSupportedChainsResponse,
    GetErc20ApproveTransactionResponse,
    GetRfqOrderStatusResponse,
    GetTransactionStatusResponse,
    SubmitRfqOrderResponse,
} from './types';
import type {
    BroadcastTransactionsResponse,
    GetBroadcastOrdersResponse,
    GetGasLimitResponse,
    GetGasPriceResponse,
    GetTransactionSupportedChainsResponse,
    SimulateTransactionsResponse,
} from './types';
import type {
    GetAllTokenBalancesByAddressResponse,
    GetTokenBalancesByAddressResponse,
    GetTransactionDetailByHashResponse,
    GetTransactionsByAddressResponse,
    GetWalletSupportedChainsResponse,
} from './types';

export class RestAPI {
    private configuration: ConfigurationRestAPI;
    private generalDataApi: GeneralDataApi;
    private rWADataApi: RWADataApi;
    private tradingApi: TradingApi;
    private transactionApi: TransactionApi;
    private walletApi: WalletApi;

    constructor(configuration: ConfigurationRestAPI) {
        this.configuration = configuration;
        this.generalDataApi = new GeneralDataApi(configuration);
        this.rWADataApi = new RWADataApi(configuration);
        this.tradingApi = new TradingApi(configuration);
        this.transactionApi = new TransactionApi(configuration);
        this.walletApi = new WalletApi(configuration);
    }

    /**
     * Generic function to send a request.
     * @param endpoint - The API endpoint to call.
     * @param method - HTTP method to use (GET, POST, DELETE, etc.).
     * @param queryParams - Query parameters for the request.
     * @param bodyParams - Body parameters for the request.
     *
     * @returns A promise resolving to the response data object.
     */
    sendRequest<T>(
        endpoint: string,
        method: 'GET' | 'POST' | 'DELETE' | 'PUT' | 'PATCH',
        queryParams: Record<string, unknown> = {},
        bodyParams: Record<string, unknown> = {}
    ): Promise<RestApiResponse<T>> {
        return sendRequest<T>(
            this.configuration,
            endpoint,
            method,
            queryParams,
            bodyParams,
            undefined,
            undefined
        );
    }

    /**
     * Generic function to send a signed request.
     * @param endpoint - The API endpoint to call.
     * @param method - HTTP method to use (GET, POST, DELETE, etc.).
     * @param queryParams - Query parameters for the request.
     * @param bodyParams - Body parameters for the request.
     *
     * @returns A promise resolving to the response data object.
     */
    sendSignedRequest<T>(
        endpoint: string,
        method: 'GET' | 'POST' | 'DELETE' | 'PUT' | 'PATCH',
        queryParams: Record<string, unknown> = {},
        bodyParams: Record<string, unknown> = {}
    ): Promise<RestApiResponse<T>> {
        return sendRequest<T>(
            this.configuration,
            endpoint,
            method,
            queryParams,
            bodyParams,
            undefined,
            undefined,
            { isSigned: true }
        );
    }

    /**
     * Return the latest DEX trades from tracked addresses (smart money, KOL, or custom address list). Supports filtering by trade type, chain, volume, market cap, and risk token visibility.
     * This endpoint is not cursor-paginated. trackerType=1/2 (Smart Money / KOL) return a single fixed-size set determined by the downstream public query cap; trackerType=3 (custom address list) returns up to `limit` trades (omit `limit` to use the downstream default).
     *
     * @summary Get Address Tracker Trades
     * @param {GetAddressTrackerTradesRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetAddressTrackerTradesResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-address-tracker-trades Binance API Documentation}
     */
    getAddressTrackerTrades(
        requestParameters: GetAddressTrackerTradesRequest
    ): Promise<RestApiResponse<GetAddressTrackerTradesResponse>> {
        return this.generalDataApi.getAddressTrackerTrades(requestParameters);
    }

    /**
     * Return candlestick (K-line) data for a token.
     *
     * @summary Get Candles
     * @param {GetCandlesRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetCandlesResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-candles Binance API Documentation}
     */
    getCandles(requestParameters: GetCandlesRequest): Promise<RestApiResponse<GetCandlesResponse>> {
        return this.generalDataApi.getCandles(requestParameters);
    }

    /**
     * Return the holders ranking list for a token, including holding amount, holding percentage, native-token balance, average buy/sell price, realized PnL, and funding source. Up to 100 records. Pagination is not supported.
     *
     * @summary Get Holders Ranking
     * @param {GetHoldersRankingRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetHoldersRankingResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-holders-ranking Binance API Documentation}
     */
    getHoldersRanking(
        requestParameters: GetHoldersRankingRequest
    ): Promise<RestApiResponse<GetHoldersRankingResponse>> {
        return this.generalDataApi.getHoldersRanking(requestParameters);
    }

    /**
     * Get hot token ranking list. Supports sorting by volume, price change, market cap, etc., with filters for holding distribution, developer behavior, liquidity, and more.
     *
     * @summary Get Hot Token List
     * @param {GetHotTokenListRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetHotTokenListResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-hot-token-list Binance API Documentation}
     */
    getHotTokenList(
        requestParameters: GetHotTokenListRequest
    ): Promise<RestApiResponse<GetHotTokenListResponse>> {
        return this.generalDataApi.getHotTokenList(requestParameters);
    }

    /**
     * Return a paginated leaderboard of top-performing wallet addresses, supporting filtering and sorting by time frame, wallet type, realized PnL, win rate, transaction count, and volume.
     *
     * @summary Get Leaderboard List
     * @param {GetLeaderboardListRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetLeaderboardListResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-leaderboard-list Binance API Documentation}
     */
    getLeaderboardList(
        requestParameters: GetLeaderboardListRequest
    ): Promise<RestApiResponse<GetLeaderboardListResponse>> {
        return this.generalDataApi.getLeaderboardList(requestParameters);
    }

    /**
     * Return the list of blockchains supported by the leaderboard feature.
     *
     * @summary Get Leaderboard Supported Chains
     * @param {GetLeaderboardSupportedChainsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetLeaderboardSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-leaderboard-supported-chains Binance API Documentation}
     */
    getLeaderboardSupportedChains(
        requestParameters: GetLeaderboardSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetLeaderboardSupportedChainsResponse>> {
        return this.generalDataApi.getLeaderboardSupportedChains(requestParameters);
    }

    /**
     * Return a paginated list of an address's DEX transaction history, sorted by time descending. Up to 1000 records total; up to 100 per page. Supports filtering by time range, token, and trade type.
     *
     * @summary Get Portfolio DEX History
     * @param {GetPortfolioDexHistoryRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetPortfolioDexHistoryResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-portfolio-dex-history Binance API Documentation}
     */
    getPortfolioDexHistory(
        requestParameters: GetPortfolioDexHistoryRequest
    ): Promise<RestApiResponse<GetPortfolioDexHistoryResponse>> {
        return this.generalDataApi.getPortfolioDexHistory(requestParameters);
    }

    /**
     * Return a summary of an address's trading performance over a specified time frame, including realized PnL, daily PnL breakdown, win rate, token count by PnL range, buy/sell statistics, and top 3 profit tokens.
     *
     * @summary Get Portfolio Overview
     * @param {GetPortfolioOverviewRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetPortfolioOverviewResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-portfolio-overview Binance API Documentation}
     */
    getPortfolioOverview(
        requestParameters: GetPortfolioOverviewRequest
    ): Promise<RestApiResponse<GetPortfolioOverviewResponse>> {
        return this.generalDataApi.getPortfolioOverview(requestParameters);
    }

    /**
     * Return a paginated list of an address's recent realized PnL records, sorted by last active timestamp descending. Up to 1000 records total; up to 100 per page.
     *
     * @summary Get Portfolio Recent PnL
     * @param {GetPortfolioRecentPnLRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetPortfolioRecentPnLResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-portfolio-recent-pn-l Binance API Documentation}
     */
    getPortfolioRecentPnL(
        requestParameters: GetPortfolioRecentPnLRequest
    ): Promise<RestApiResponse<GetPortfolioRecentPnLResponse>> {
        return this.generalDataApi.getPortfolioRecentPnL(requestParameters);
    }

    /**
     * Return the list of blockchains supported by the portfolio (address analysis) feature.
     *
     * @summary Get Portfolio Supported Chains
     * @param {GetPortfolioSupportedChainsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetPortfolioSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-portfolio-supported-chains Binance API Documentation}
     */
    getPortfolioSupportedChains(
        requestParameters: GetPortfolioSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetPortfolioSupportedChainsResponse>> {
        return this.generalDataApi.getPortfolioSupportedChains(requestParameters);
    }

    /**
     * Return the latest realized PnL details for a specific token held by a wallet address, including buy/sell statistics, current balance, holding duration, and PnL support status.
     *
     * @summary Get Portfolio Token Latest PnL
     * @param {GetPortfolioTokenLatestPnLRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetPortfolioTokenLatestPnLResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-portfolio-token-latest-pn-l Binance API Documentation}
     */
    getPortfolioTokenLatestPnL(
        requestParameters: GetPortfolioTokenLatestPnLRequest
    ): Promise<RestApiResponse<GetPortfolioTokenLatestPnLResponse>> {
        return this.generalDataApi.getPortfolioTokenLatestPnL(requestParameters);
    }

    /**
     * Return the list of blockchains supported by the market service.
     *
     * @summary Get Supported Chains
     * @param {GetSupportedChainsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains Binance API Documentation}
     */
    getSupportedChains(
        requestParameters: GetSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetSupportedChainsResponse>> {
        return this.generalDataApi.getSupportedChains(requestParameters);
    }

    /**
     * Return comprehensive metrics for a token, including creator and launch info, holding percentages by address type (smart money, KOL, sniper, bundler, fresh wallet, etc.), and token tags.
     *
     * @summary Get Token Advanced Info
     * @param {GetTokenAdvancedInfoRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenAdvancedInfoResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-token-advanced-info Binance API Documentation}
     */
    getTokenAdvancedInfo(
        requestParameters: GetTokenAdvancedInfoRequest
    ): Promise<RestApiResponse<GetTokenAdvancedInfoResponse>> {
        return this.generalDataApi.getTokenAdvancedInfo(requestParameters);
    }

    /**
     * Return basic metadata for a token: name, symbol, logo, decimals, creator address, creation time, and tag info.
     *
     * @summary Get Token Basic Info
     * @param {GetTokenBasicInfoRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenBasicInfoResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-token-basic-info Binance API Documentation}
     */
    getTokenBasicInfo(
        requestParameters: GetTokenBasicInfoRequest
    ): Promise<RestApiResponse<GetTokenBasicInfoResponse>> {
        return this.generalDataApi.getTokenBasicInfo(requestParameters);
    }

    /**
     * Return developer information for a token, including historical token launch statistics, current holding percentage, and funding source details.
     *
     * @summary Get Token Dev Info
     * @param {GetTokenDevInfoRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenDevInfoResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-token-dev-info Binance API Documentation}
     */
    getTokenDevInfo(
        requestParameters: GetTokenDevInfoRequest
    ): Promise<RestApiResponse<GetTokenDevInfoResponse>> {
        return this.generalDataApi.getTokenDevInfo(requestParameters);
    }

    /**
     * Get the latest price for tokens. Supports batch queries, up to 100 tokens per request.
     *
     * @summary Get Token Price
     * @param {GetTokenPriceRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenPriceResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-token-price Binance API Documentation}
     */
    getTokenPrice(
        requestParameters: GetTokenPriceRequest = {}
    ): Promise<RestApiResponse<GetTokenPriceResponse>> {
        return this.generalDataApi.getTokenPrice(requestParameters);
    }

    /**
     * Return on-chain trade history for a token. Supports tag filtering and wallet address filtering.
     *
     * @summary Get Token Trades
     * @param {GetTokenTradesRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenTradesResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-token-trades Binance API Documentation}
     */
    getTokenTrades(
        requestParameters: GetTokenTradesRequest
    ): Promise<RestApiResponse<GetTokenTradesResponse>> {
        return this.generalDataApi.getTokenTrades(requestParameters);
    }

    /**
     * Get token price and trading data (volume, transactions, market cap, holders, etc.). Supports batch queries for up to 100 tokens.
     *
     * @summary Get Token Trading Info
     * @param {GetTokenTradingInfoRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenTradingInfoResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-token-trading-info Binance API Documentation}
     */
    getTokenTradingInfo(
        requestParameters: GetTokenTradingInfoRequest = {}
    ): Promise<RestApiResponse<GetTokenTradingInfoResponse>> {
        return this.generalDataApi.getTokenTradingInfo(requestParameters);
    }

    /**
     * Return the top liquidity pools for a token, including pool name, protocol, liquidity in USD, pool address, and per-token composition.
     *
     * @summary Get Top Liquidity Pools
     * @param {GetTopLiquidityPoolsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTopLiquidityPoolsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-top-liquidity-pools Binance API Documentation}
     */
    getTopLiquidityPools(
        requestParameters: GetTopLiquidityPoolsRequest
    ): Promise<RestApiResponse<GetTopLiquidityPoolsResponse>> {
        return this.generalDataApi.getTopLiquidityPools(requestParameters);
    }

    /**
     * Return the top profit-making addresses for a token, ranked by realized PnL descending. Includes holding amount, average buy/sell price, realized PnL, and funding source. Up to 100 records. Pagination is not supported.
     *
     * @summary Get Top Traders
     * @param {GetTopTradersRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTopTradersResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#get-top-traders Binance API Documentation}
     */
    getTopTraders(
        requestParameters: GetTopTradersRequest
    ): Promise<RestApiResponse<GetTopTradersResponse>> {
        return this.generalDataApi.getTopTraders(requestParameters);
    }

    /**
     * Search tokens by symbol or contract address.
     *
     * @summary Search Token
     * @param {SearchTokenRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<SearchTokenResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/general-data#search-token Binance API Documentation}
     */
    searchToken(
        requestParameters: SearchTokenRequest
    ): Promise<RestApiResponse<SearchTokenResponse>> {
        return this.generalDataApi.searchToken(requestParameters);
    }

    /**
     * Return the list of supported RWA token issuance platforms and their basic info.
     *
     * @summary Get RWA Token Issuance Platforms
     * @param {GetRwaTokenIssuancePlatformsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetRwaTokenIssuancePlatformsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-token-issuance-platforms Binance API Documentation}
     */
    getRwaTokenIssuancePlatforms(
        requestParameters: GetRwaTokenIssuancePlatformsRequest = {}
    ): Promise<RestApiResponse<GetRwaTokenIssuancePlatformsResponse>> {
        return this.rWADataApi.getRwaTokenIssuancePlatforms(requestParameters);
    }

    /**
     * Get the list of RWA tokens with underlying asset info. Supports filtering by platform and sector tab.
     *
     * @summary Get RWA Token List
     * @param {GetRwaTokenListRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetRwaTokenListResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-token-list Binance API Documentation}
     */
    getRwaTokenList(
        requestParameters: GetRwaTokenListRequest = {}
    ): Promise<RestApiResponse<GetRwaTokenListResponse>> {
        return this.rWADataApi.getRwaTokenList(requestParameters);
    }

    /**
     * Batch query RWA token prices, including on-chain price and underlying reference price.
     *
     * @summary Get RWA Token Price
     * @param {GetRwaTokenPriceRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetRwaTokenPriceResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-token-price Binance API Documentation}
     */
    getRwaTokenPrice(
        requestParameters: GetRwaTokenPriceRequest
    ): Promise<RestApiResponse<GetRwaTokenPriceResponse>> {
        return this.rWADataApi.getRwaTokenPrice(requestParameters);
    }

    /**
     * Get the underlying company information for an RWA token.
     *
     * @summary Get RWA Underlying Info
     * @param {GetRwaUnderlyingInfoRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetRwaUnderlyingInfoResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-underlying-info Binance API Documentation}
     */
    getRwaUnderlyingInfo(
        requestParameters: GetRwaUnderlyingInfoRequest
    ): Promise<RestApiResponse<GetRwaUnderlyingInfoResponse>> {
        return this.rWADataApi.getRwaUnderlyingInfo(requestParameters);
    }

    /**
     * Get market data for the underlying asset of an RWA token.
     *
     * @summary Get RWA Underlying Market Data
     * @param {GetRwaUnderlyingMarketDataRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetRwaUnderlyingMarketDataResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#get-rwa-underlying-market-data Binance API Documentation}
     */
    getRwaUnderlyingMarketData(
        requestParameters: GetRwaUnderlyingMarketDataRequest
    ): Promise<RestApiResponse<GetRwaUnderlyingMarketDataResponse>> {
        return this.rWADataApi.getRwaUnderlyingMarketData(requestParameters);
    }

    /**
     * Search RWA tokens by keyword or contract address.
     *
     * @summary Search RWA Token
     * @param {SearchRwaTokenRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<SearchRwaTokenResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/rwa-data#search-rwa-token Binance API Documentation}
     */
    searchRwaToken(
        requestParameters: SearchRwaTokenRequest
    ): Promise<RestApiResponse<SearchRwaTokenResponse>> {
        return this.rWADataApi.searchRwaToken(requestParameters);
    }

    /**
     * Solana-only counterpart to `/swap`. Shares the full quote → route → vendor `buildSwapTx` → priceImpact → minReceive → instruction-assembly pipeline; the only difference is the response: instead of returning a signed-and-serialized base64 transaction, this endpoint returns the **uncompiled** instruction list plus the address-lookup-table (ALT) address list, leaving v0-transaction compilation, signing, and submission to the caller.
     *
     * Use this when the caller needs to:
     * - prepend / append their own instructions (e.g. fee splitting, custom
     * logging) before signing;
     *
     * - reuse the platform-curated route, slippage, PS-variant rewriting, ALT
     * injection, ComputeBudget overwrite, and ATA batching while still
     * controlling the final wire format.
     *
     *
     * Only supports `binanceChainId=CT_501` (Solana). Other chains return `CHAIN_NOT_SUPPORTED` (40411). Parameters mirror the Solana subset of `/swap` (no EVM-only `approveTransaction` / `approveAmount` / `gasLimit`).
     *
     * @summary Build Solana Swap Instructions
     * @param {BuildSolanaSwapInstructionsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<BuildSolanaSwapInstructionsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#build-solana-swap-instructions Binance API Documentation}
     */
    buildSolanaSwapInstructions(
        requestParameters: BuildSolanaSwapInstructionsRequest
    ): Promise<RestApiResponse<BuildSolanaSwapInstructionsResponse>> {
        return this.tradingApi.buildSolanaSwapInstructions(requestParameters);
    }

    /**
     * Build the on-chain swap calldata for a previously quoted route. The request is matched against the cached quote by `quoteId` (TTL ~30s); if the entry has expired, `QUOTE_EXPIRED` (40401) is returned, and if the request parameters disagree with the cached quote, `SWAP_QUOTE_MISMATCH` (40462) is returned.
     *
     * @summary Build Swap Transaction
     * @param {BuildSwapTransactionRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<BuildSwapTransactionResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#build-swap-transaction Binance API Documentation}
     */
    buildSwapTransaction(
        requestParameters: BuildSwapTransactionRequest
    ): Promise<RestApiResponse<BuildSwapTransactionResponse>> {
        return this.tradingApi.buildSwapTransaction(requestParameters);
    }

    /**
     * Query multiple DEX vendors in parallel and return the priced routes sorted by `toTokenAmount` (descending). Each route carries an independent `quoteId` (TTL ~30s) that the swap endpoint consumes to construct calldata for the chosen route.
     *
     * @summary Get Aggregated Quote
     * @param {GetAggregatedQuoteRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetAggregatedQuoteResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#get-aggregated-quote Binance API Documentation}
     */
    getAggregatedQuote(
        requestParameters: GetAggregatedQuoteRequest
    ): Promise<RestApiResponse<GetAggregatedQuoteResponse>> {
        return this.tradingApi.getAggregatedQuote(requestParameters);
    }

    /**
     * Return blockchain networks supported by the DEX aggregator. The supported list is dynamically configured server-side and may change over time.
     * Pass `binanceChainId` to filter to a single chain; omit it to get the full list.
     *
     * @summary Get Aggregator Supported Chains
     * @param {GetAggregatorSupportedChainsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetAggregatorSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#get-aggregator-supported-chains Binance API Documentation}
     */
    getAggregatorSupportedChains(
        requestParameters: GetAggregatorSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetAggregatorSupportedChainsResponse>> {
        return this.tradingApi.getAggregatorSupportedChains(requestParameters);
    }

    /**
     * Build the on-chain transaction data needed to approve the DEX router to spend a user's ERC-20 token before a swap. Calldata is encoded per the ERC-20 ABI standard (`approve()` selector + spender + amount).
     *
     * @summary Get ERC-20 Approve Transaction
     * @param {GetErc20ApproveTransactionRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetErc20ApproveTransactionResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#get-erc20-approve-transaction Binance API Documentation}
     */
    getErc20ApproveTransaction(
        requestParameters: GetErc20ApproveTransactionRequest
    ): Promise<RestApiResponse<GetErc20ApproveTransactionResponse>> {
        return this.tradingApi.getErc20ApproveTransaction(requestParameters);
    }

    /**
     * Query the settlement status of an RFQ order by its platform `orderId` (returned by `POST /order/submit`). Poll this endpoint until `status` reaches a terminal state: `FILLED` (settled on-chain) or `FAILED` (settlement failed).
     *
     * @summary Get RFQ Order Status
     * @param {GetRfqOrderStatusRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetRfqOrderStatusResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#get-rfq-order-status Binance API Documentation}
     */
    getRfqOrderStatus(
        requestParameters: GetRfqOrderStatusRequest
    ): Promise<RestApiResponse<GetRfqOrderStatusResponse>> {
        return this.tradingApi.getRfqOrderStatus(requestParameters);
    }

    /**
     * Look up the on-chain status of a DEX swap by `binanceChainId` + `txHash`.
     * Response semantics:
     * - Transaction not found: `data` is `null` (not HTTP 404).
     * - Transaction failed: `status=failed` with `errorMsg`; aggregator
     * business fields (`txType`, `dexRouter`, `fromTokenDetails`,
     * `toTokenDetails`) are `null`.
     *
     * - Transaction succeeded: `status=success` with full token details
     * when an aggregator event is present.
     *
     * @summary Get Transaction Status
     * @param {GetTransactionStatusRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTransactionStatusResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#get-transaction-status Binance API Documentation}
     */
    getTransactionStatus(
        requestParameters: GetTransactionStatusRequest
    ): Promise<RestApiResponse<GetTransactionStatusResponse>> {
        return this.tradingApi.getTransactionStatus(requestParameters);
    }

    /**
     * Submit a signed RFQ order to the backend for on-chain settlement via the corresponding vendor relayer. Only used when `executionMode=RFQ` (equity / RWA tokens such as Ondo and BStock).
     *
     **Flow**: `GET /quote` → pick an RFQ route → `GET /swap` → sign `rfq.typedDataToSign` with EIP-712 (`eth_signTypedData_v4`) → call this endpoint → poll `GET /order/{orderId}` until `FILLED` or `FAILED`.
     *
     **Idempotency**: Submitting with the same `requestId` within 30 minutes returns the original result without re-calling the vendor. Use a new UUID for each distinct order; reuse the same UUID when retrying.
     *
     * @summary Submit RFQ Order
     * @param {SubmitRfqOrderRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<SubmitRfqOrderResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/trading-api#submit-rfq-order Binance API Documentation}
     */
    submitRfqOrder(
        requestParameters: SubmitRfqOrderRequest
    ): Promise<RestApiResponse<SubmitRfqOrderResponse>> {
        return this.tradingApi.submitRfqOrder(requestParameters);
    }

    /**
     * Broadcast a client-signed transaction to the chain via the Binance Web3 API relay. Returns the transaction hash and an internal `orderId` you can use to track on-chain status via the post-transaction service.
     * Optional MEV protection (EVM chains only) routes the transaction through a private mempool to mitigate front-running and sandwich attacks.
     *
     * @summary Broadcast Transactions
     * @param {BroadcastTransactionsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<BroadcastTransactionsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#broadcast-transactions Binance API Documentation}
     */
    broadcastTransactions(
        requestParameters: BroadcastTransactionsRequest
    ): Promise<RestApiResponse<BroadcastTransactionsResponse>> {
        return this.transactionApi.broadcastTransactions(requestParameters);
    }

    /**
     * Look up broadcast orders previously submitted via `/pre-transaction/broadcast-transaction`. Filter by `txStatus` or `orderId`, paginate with `cursor`.
     *
     * @summary Get Broadcast Orders
     * @param {GetBroadcastOrdersRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetBroadcastOrdersResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-broadcast-orders Binance API Documentation}
     */
    getBroadcastOrders(
        requestParameters: GetBroadcastOrdersRequest
    ): Promise<RestApiResponse<GetBroadcastOrdersResponse>> {
        return this.transactionApi.getBroadcastOrders(requestParameters);
    }

    /**
     * Estimate the gas limit (or compute-unit ceiling on Solana) for an unsigned transaction.
     * Provide either `evmTx` for EVM chains or `solTx` for Solana, matching the value of `binanceChainId`.
     *
     * @summary Get Gas Limit
     * @param {GetGasLimitRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetGasLimitResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-gas-limit Binance API Documentation}
     */
    getGasLimit(
        requestParameters: GetGasLimitRequest
    ): Promise<RestApiResponse<GetGasLimitResponse>> {
        return this.transactionApi.getGasLimit(requestParameters);
    }

    /**
     * Query the current network gas price for the specified chain. The response shape varies by chain family:
     * - EVM chains return both `evmLegacyGasPrice` (legacy gasPrice) and
     * `eip1559GasPrice` (baseFee + priority/max fees) when EIP-1559 is supported.
     * - Solana returns `solanaGasPrice` (compute-unit prices and Jito tips).
     * Fields not applicable to the chain family are returned as `null`.
     *
     * @summary Get Gas Price
     * @param {GetGasPriceRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetGasPriceResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-gas-price Binance API Documentation}
     */
    getGasPrice(
        requestParameters: GetGasPriceRequest
    ): Promise<RestApiResponse<GetGasPriceResponse>> {
        return this.transactionApi.getGasPrice(requestParameters);
    }

    /**
     * Return the blockchain networks supported by the Transaction service for gas estimation, simulation, and broadcasting. The list is dynamically configured server-side and may change over time.
     *
     * @summary Get Transaction Supported Chains
     * @param {GetTransactionSupportedChainsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTransactionSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#get-transaction-supported-chains Binance API Documentation}
     */
    getTransactionSupportedChains(
        requestParameters: GetTransactionSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetTransactionSupportedChainsResponse>> {
        return this.transactionApi.getTransactionSupportedChains(requestParameters);
    }

    /**
     * Simulate transaction execution off-chain to predict its outcome before broadcasting. The response includes the predicted execution status, balance changes per affected account/token, and ERC-20 allowance changes (EVM chains).
     * Provide either `evmTx` (EVM chains) or `solTx` (Solana) matching `binanceChainId`.
     *
     * @summary Simulate Transactions
     * @param {SimulateTransactionsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<SimulateTransactionsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/transaction-api#simulate-transactions Binance API Documentation}
     */
    simulateTransactions(
        requestParameters: SimulateTransactionsRequest
    ): Promise<RestApiResponse<SimulateTransactionsResponse>> {
        return this.transactionApi.simulateTransactions(requestParameters);
    }

    /**
     * Return all token balances held by an address across one or more chains, with pagination support. Set `excludeRiskToken=true` to filter out airdrop-risk and honeypot tokens (honeypot detection currently applies only to ETH / BSC / SOL / BASE).
     *
     * @summary Get All Token Balances by Address
     * @param {GetAllTokenBalancesByAddressRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetAllTokenBalancesByAddressResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/wallet-api#get-all-token-balances-by-address Binance API Documentation}
     */
    getAllTokenBalancesByAddress(
        requestParameters: GetAllTokenBalancesByAddressRequest = {}
    ): Promise<RestApiResponse<GetAllTokenBalancesByAddressResponse>> {
        return this.walletApi.getAllTokenBalancesByAddress(requestParameters);
    }

    /**
     * Return token balances for a specific list of (chain, contract) pairs. Up to 20 entries per request. Set `excludeRiskToken="0"` to exclude risk-flagged tokens (default), or `"1"` to include them.
     *
     * @summary Get Token Balances by Address
     * @param {GetTokenBalancesByAddressRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTokenBalancesByAddressResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/wallet-api#get-token-balances-by-address Binance API Documentation}
     */
    getTokenBalancesByAddress(
        requestParameters: GetTokenBalancesByAddressRequest
    ): Promise<RestApiResponse<GetTokenBalancesByAddressResponse>> {
        return this.walletApi.getTokenBalancesByAddress(requestParameters);
    }

    /**
     * Look up the full on-chain transaction detail by `binanceChainId` + `txHash`. Returns one or more entries describing transaction inputs, outputs, internal calls, and token transfers.
     *
     * @summary Get Transaction Detail by Hash
     * @param {GetTransactionDetailByHashRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTransactionDetailByHashResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/wallet-api#get-transaction-detail-by-hash Binance API Documentation}
     */
    getTransactionDetailByHash(
        requestParameters: GetTransactionDetailByHashRequest = {}
    ): Promise<RestApiResponse<GetTransactionDetailByHashResponse>> {
        return this.walletApi.getTransactionDetailByHash(requestParameters);
    }

    /**
     * Return on-chain transaction history for a wallet address across one or more chains. Results are limited to the most recent 6 months and sorted by time (descending). Supports cursor pagination, time-range filtering, and token-contract filtering.
     *
     * @summary Get Transactions by Address
     * @param {GetTransactionsByAddressRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetTransactionsByAddressResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/wallet-api#get-transactions-by-address Binance API Documentation}
     */
    getTransactionsByAddress(
        requestParameters: GetTransactionsByAddressRequest
    ): Promise<RestApiResponse<GetTransactionsByAddressResponse>> {
        return this.walletApi.getTransactionsByAddress(requestParameters);
    }

    /**
     * Return blockchain networks for which the Wallet service can return balances. The supported list is dynamically configured server-side and may change over time. Pass `binanceChainId` to filter to a single chain; omit to get the full list.
     *
     * @summary Get Wallet Supported Chains
     * @param {GetWalletSupportedChainsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetWalletSupportedChainsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/rest-api/wallet-api#get-wallet-supported-chains Binance API Documentation}
     */
    getWalletSupportedChains(
        requestParameters: GetWalletSupportedChainsRequest = {}
    ): Promise<RestApiResponse<GetWalletSupportedChainsResponse>> {
        return this.walletApi.getWalletSupportedChains(requestParameters);
    }
}
