/**
 * Binance Web3 WebSocket Streams
 *
 * Real-time on-chain data streaming over WebSocket for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    WebsocketStreamsBase,
    WebsocketStream,
    assertParamExists,
    replaceWebsocketStreamsPlaceholders,
    createStreamHandler,
} from '@binance/common';
import type {
    CandlestickStreamResponse,
    MarketStatsStreamResponse,
    PriceStreamResponse,
    RealTimeTradesStreamResponse,
} from '../types';

const MarketApiParamCreator = function () {
    return {
        /**
         * Push token candlestick (K-line) data in real time. The current (unclosed) candle keeps updating as new trades occur.
         *
         * Update Speed: Real-time
         *
         * @summary Candlestick Stream
         * @param {string} bar K-line interval. Enum: 1s, 5s, 30s, 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M.
         * @param {string} chainId Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
         * @param {string} contractAddress Token contract address.
         * @param {string} [id] Unique WebSocket request ID.
         *
         * @throws {RequiredError}
         */
        candlestickStream: (
            bar: string,
            chainId: string,
            contractAddress: string,
            id?: string
        ): string => {
            // verify required parameter 'bar' is not null or undefined
            assertParamExists('candlestickStream', 'bar', bar);
            // verify required parameter 'chainId' is not null or undefined
            assertParamExists('candlestickStream', 'chainId', chainId);
            // verify required parameter 'contractAddress' is not null or undefined
            assertParamExists('candlestickStream', 'contractAddress', contractAddress);

            return replaceWebsocketStreamsPlaceholders(
                '/w3w@onchainos@pub@candles@<bar>@<chainId>@<contractAddress>'.slice(1),
                { bar, chainId, contractAddress, id }
            );
        },
        /**
         * Push token market data. Rate-limited to at most once per second per token: if a token's data changes within a 1-second window, the latest snapshot is pushed once (multiple changes are coalesced into the latest value); if there is no change, nothing is pushed.
         *
         * Update Speed: Real-time
         *
         * @summary Market Stats Stream
         * @param {string} chainId Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
         * @param {string} contractAddress Token contract address.
         * @param {string} [id] Unique WebSocket request ID.
         *
         * @throws {RequiredError}
         */
        marketStatsStream: (chainId: string, contractAddress: string, id?: string): string => {
            // verify required parameter 'chainId' is not null or undefined
            assertParamExists('marketStatsStream', 'chainId', chainId);
            // verify required parameter 'contractAddress' is not null or undefined
            assertParamExists('marketStatsStream', 'contractAddress', contractAddress);

            return replaceWebsocketStreamsPlaceholders(
                '/w3w@onchainos@pub@tx-data@<chainId>@<contractAddress>'.slice(1),
                { chainId, contractAddress, id }
            );
        },
        /**
         * Push token price updates. Triggered every time a token's price changes.
         *
         * Update Speed: Real-time
         *
         * @summary Price Stream
         * @param {string} chainId Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
         * @param {string} contractAddress Token contract address.
         * @param {string} [id] Unique WebSocket request ID.
         *
         * @throws {RequiredError}
         */
        priceStream: (chainId: string, contractAddress: string, id?: string): string => {
            // verify required parameter 'chainId' is not null or undefined
            assertParamExists('priceStream', 'chainId', chainId);
            // verify required parameter 'contractAddress' is not null or undefined
            assertParamExists('priceStream', 'contractAddress', contractAddress);

            return replaceWebsocketStreamsPlaceholders(
                '/w3w@onchainos@pub@price@<chainId>@<contractAddress>'.slice(1),
                { chainId, contractAddress, id }
            );
        },
        /**
         * Push real-time token trade history. Triggered on every new transaction.
         *
         * Update Speed: Real-time
         *
         * @summary Real-Time Trades Stream
         * @param {string} chainId Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
         * @param {string} contractAddress Token contract address.
         * @param {string} [id] Unique WebSocket request ID.
         *
         * @throws {RequiredError}
         */
        realTimeTradesStream: (chainId: string, contractAddress: string, id?: string): string => {
            // verify required parameter 'chainId' is not null or undefined
            assertParamExists('realTimeTradesStream', 'chainId', chainId);
            // verify required parameter 'contractAddress' is not null or undefined
            assertParamExists('realTimeTradesStream', 'contractAddress', contractAddress);

            return replaceWebsocketStreamsPlaceholders(
                '/w3w@onchainos@pub@tx@<chainId>@<contractAddress>'.slice(1),
                { chainId, contractAddress, id }
            );
        },
    };
};

/**
 * MarketApi - interface
 * @interface MarketApi
 */
export interface MarketApiInterface {
    /**
     * Push token candlestick (K-line) data in real time. The current (unclosed) candle keeps updating as new trades occur.
     *
     * Update Speed: Real-time
     *
     * @summary Candlestick Stream
     * @param {CandlestickStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<CandlestickStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApiInterface
     */
    candlestickStream(
        requestParameters: CandlestickStreamRequest
    ): WebsocketStream<CandlestickStreamResponse>;

    /**
     * Push token market data. Rate-limited to at most once per second per token: if a token's data changes within a 1-second window, the latest snapshot is pushed once (multiple changes are coalesced into the latest value); if there is no change, nothing is pushed.
     *
     * Update Speed: Real-time
     *
     * @summary Market Stats Stream
     * @param {MarketStatsStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<MarketStatsStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApiInterface
     */
    marketStatsStream(
        requestParameters: MarketStatsStreamRequest
    ): WebsocketStream<MarketStatsStreamResponse>;

    /**
     * Push token price updates. Triggered every time a token's price changes.
     *
     * Update Speed: Real-time
     *
     * @summary Price Stream
     * @param {PriceStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<PriceStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApiInterface
     */
    priceStream(requestParameters: PriceStreamRequest): WebsocketStream<PriceStreamResponse>;

    /**
     * Push real-time token trade history. Triggered on every new transaction.
     *
     * Update Speed: Real-time
     *
     * @summary Real-Time Trades Stream
     * @param {RealTimeTradesStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<RealTimeTradesStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApiInterface
     */
    realTimeTradesStream(
        requestParameters: RealTimeTradesStreamRequest
    ): WebsocketStream<RealTimeTradesStreamResponse>;
}

/**
 * Request parameters for candlestickStream operation in MarketApi.
 * @interface CandlestickStreamRequest
 */
export interface CandlestickStreamRequest {
    /**
     * K-line interval. Enum: 1s, 5s, 30s, 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M.
     * @type {string}
     * @memberof MarketApiCandlestickStream
     */
    readonly bar: string;

    /**
     * Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
     * @type {string}
     * @memberof MarketApiCandlestickStream
     */
    readonly chainId: string;

    /**
     * Token contract address.
     * @type {string}
     * @memberof MarketApiCandlestickStream
     */
    readonly contractAddress: string;

    /**
     * Unique WebSocket request ID.
     * @type {string}
     * @memberof MarketApiCandlestickStream
     */
    readonly id?: string;
}

/**
 * Request parameters for marketStatsStream operation in MarketApi.
 * @interface MarketStatsStreamRequest
 */
export interface MarketStatsStreamRequest {
    /**
     * Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
     * @type {string}
     * @memberof MarketApiMarketStatsStream
     */
    readonly chainId: string;

    /**
     * Token contract address.
     * @type {string}
     * @memberof MarketApiMarketStatsStream
     */
    readonly contractAddress: string;

    /**
     * Unique WebSocket request ID.
     * @type {string}
     * @memberof MarketApiMarketStatsStream
     */
    readonly id?: string;
}

/**
 * Request parameters for priceStream operation in MarketApi.
 * @interface PriceStreamRequest
 */
export interface PriceStreamRequest {
    /**
     * Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
     * @type {string}
     * @memberof MarketApiPriceStream
     */
    readonly chainId: string;

    /**
     * Token contract address.
     * @type {string}
     * @memberof MarketApiPriceStream
     */
    readonly contractAddress: string;

    /**
     * Unique WebSocket request ID.
     * @type {string}
     * @memberof MarketApiPriceStream
     */
    readonly id?: string;
}

/**
 * Request parameters for realTimeTradesStream operation in MarketApi.
 * @interface RealTimeTradesStreamRequest
 */
export interface RealTimeTradesStreamRequest {
    /**
     * Chain identifier, e.g. "1"=Ethereum, "56"=BSC, "CT_501"=Solana. Full supported-chain list: same as the ["supported/chain"](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains) endpoint.
     * @type {string}
     * @memberof MarketApiRealTimeTradesStream
     */
    readonly chainId: string;

    /**
     * Token contract address.
     * @type {string}
     * @memberof MarketApiRealTimeTradesStream
     */
    readonly contractAddress: string;

    /**
     * Unique WebSocket request ID.
     * @type {string}
     * @memberof MarketApiRealTimeTradesStream
     */
    readonly id?: string;
}

/**
 * MarketApi - interface
 * @class MarketApi
 * @extends {WebsocketStreamsBase}
 */
export class MarketApi implements MarketApiInterface {
    private readonly websocketBase: WebsocketStreamsBase;
    private localVarParamCreator;

    constructor(websocketBase: WebsocketStreamsBase) {
        this.websocketBase = websocketBase;
        this.localVarParamCreator = MarketApiParamCreator();
    }

    /**
     * Push token candlestick (K-line) data in real time. The current (unclosed) candle keeps updating as new trades occur.
     *
     * Update Speed: Real-time
     *
     * @summary Candlestick Stream
     * @param {CandlestickStreamRequest} requestParameters Request parameters.
     * @returns {WebsocketStream<CandlestickStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#candlestick-stream Binance API Documentation}
     */
    public candlestickStream(
        requestParameters: CandlestickStreamRequest
    ): WebsocketStream<CandlestickStreamResponse> {
        const stream = this.localVarParamCreator.candlestickStream(
            requestParameters?.bar,
            requestParameters?.chainId,
            requestParameters?.contractAddress,
            requestParameters?.id
        );

        return createStreamHandler<CandlestickStreamResponse>(
            this.websocketBase,
            stream,
            requestParameters?.id
        );
    }

    /**
     * Push token market data. Rate-limited to at most once per second per token: if a token's data changes within a 1-second window, the latest snapshot is pushed once (multiple changes are coalesced into the latest value); if there is no change, nothing is pushed.
     *
     * Update Speed: Real-time
     *
     * @summary Market Stats Stream
     * @param {MarketStatsStreamRequest} requestParameters Request parameters.
     * @returns {WebsocketStream<MarketStatsStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#market-stats-stream Binance API Documentation}
     */
    public marketStatsStream(
        requestParameters: MarketStatsStreamRequest
    ): WebsocketStream<MarketStatsStreamResponse> {
        const stream = this.localVarParamCreator.marketStatsStream(
            requestParameters?.chainId,
            requestParameters?.contractAddress,
            requestParameters?.id
        );

        return createStreamHandler<MarketStatsStreamResponse>(
            this.websocketBase,
            stream,
            requestParameters?.id
        );
    }

    /**
     * Push token price updates. Triggered every time a token's price changes.
     *
     * Update Speed: Real-time
     *
     * @summary Price Stream
     * @param {PriceStreamRequest} requestParameters Request parameters.
     * @returns {WebsocketStream<PriceStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#price-stream Binance API Documentation}
     */
    public priceStream(
        requestParameters: PriceStreamRequest
    ): WebsocketStream<PriceStreamResponse> {
        const stream = this.localVarParamCreator.priceStream(
            requestParameters?.chainId,
            requestParameters?.contractAddress,
            requestParameters?.id
        );

        return createStreamHandler<PriceStreamResponse>(
            this.websocketBase,
            stream,
            requestParameters?.id
        );
    }

    /**
     * Push real-time token trade history. Triggered on every new transaction.
     *
     * Update Speed: Real-time
     *
     * @summary Real-Time Trades Stream
     * @param {RealTimeTradesStreamRequest} requestParameters Request parameters.
     * @returns {WebsocketStream<RealTimeTradesStreamResponse>}
     * @throws {RequiredError}
     * @memberof MarketApi
     * @see {@link https://web3.binance.com/en/dev-docs/catalog/web3-wallet/api/ws-streams/market#real-time-trades-stream Binance API Documentation}
     */
    public realTimeTradesStream(
        requestParameters: RealTimeTradesStreamRequest
    ): WebsocketStream<RealTimeTradesStreamResponse> {
        const stream = this.localVarParamCreator.realTimeTradesStream(
            requestParameters?.chainId,
            requestParameters?.contractAddress,
            requestParameters?.id
        );

        return createStreamHandler<RealTimeTradesStreamResponse>(
            this.websocketBase,
            stream,
            requestParameters?.id
        );
    }
}
